"""User-provided Career / Interview vocabulary fields (114 entries)."""

USER_ENTRIES: list[dict] = [
    {
        "term": 'take ownership of',
        "meaningJa": '〜に責任を持ち、主体的に引き受ける',
        "usageExample": 'I took ownership of the migration and coordinated the rollout across three teams.',
        "descriptionJa": '自分の担当領域だけでなく、自発的に責任を持って推進したことを強調できる。',
    },
    {
        "term": 'work closely with',
        "meaningJa": '〜と密接に協働する',
        "usageExample": 'I worked closely with product managers to translate customer needs into technical requirements.',
        "descriptionJa": '他部門や他ロールのメンバーと合意形成しながら進めたことを説明できる。',
    },
    {
        "term": 'identify the root cause',
        "meaningJa": '根本原因を特定する',
        "usageExample": 'I analyzed the logs, reproduced the failure, and identified the root cause.',
        "descriptionJa": '表面的な症状ではなく、本質的な問題解決まで到達したことを示す問題解決表現。',
    },
    {
        "term": 'drive the project',
        "meaningJa": 'プロジェクトを主体的に推進する',
        "usageExample": 'I drove the project forward by resolving dependencies and aligning the stakeholders.',
        "descriptionJa": '単に参加したのではなく、推進させる中心的な役割を果たしたことを表す。',
    },
    {
        "term": 'resolve the issue',
        "meaningJa": '課題を解決する',
        "usageExample": 'I resolved the issue by correcting the configuration and adding a regression test.',
        "descriptionJa": '成果指向の文脈で、問題に対して具体的な解決策で行えたことを言及できる。',
    },
    {
        "term": 'targeted fix',
        "meaningJa": '狙いを絞った的確な修正',
        "usageExample": 'I implemented a targeted fix instead of applying a broad workaround.',
        "descriptionJa": '暫定処置ではなく、ピンポイントで本質的な修正を行ったことをアピール。',
    },
    {
        "term": 'preventive measures',
        "meaningJa": '再発防止策、予防策',
        "usageExample": 'I introduced preventive measures such as automated validation and clearer runbooks.',
        "descriptionJa": '障害を直すだけでなく、再発を防ぐ仕組みまで考えたことを示せる。',
    },
    {
        "term": 'assess the risk',
        "meaningJa": 'リスクを評価・分析する',
        "usageExample": 'Before the release, I assessed the risk and proposed a gradual rollout.',
        "descriptionJa": '変更やリリースに伴うリスクを未然に洗い出して対策を講じた実績。',
    },
    {
        "term": 'risk assessment',
        "meaningJa": 'リスク評価',
        "usageExample": 'I conducted a risk assessment covering security, availability, and operational cost.',
        "descriptionJa": '判断に至った体系的なリスク分析を名詞として表現できる。',
    },
    {
        "term": 'evaluate the impact',
        "meaningJa": '影響を評価する',
        "usageExample": 'We evaluated the impact using conversion rate, latency, and support-volume data.',
        "descriptionJa": '変更や施策の効果を指標で計測したことを示す。',
    },
    {
        "term": 'take the lead',
        "meaningJa": '主導する、先頭に立つ',
        "usageExample": 'I took the lead on the redesign and guided the team through implementation.',
        "descriptionJa": '特別の役職ではなくてもリーダーシップをとったエピソードを語る時。',
    },
    {
        "term": 'support the team',
        "meaningJa": 'チームを支援する',
        "usageExample": 'I supported the team by reviewing designs and helping remove technical blockers.',
        "descriptionJa": '個人プレイではなく、全体の成功に貢献した姿勢を強調できる。',
    },
    {
        "term": 'delegate tasks',
        "meaningJa": 'タスクを委任する',
        "usageExample": "I delegated tasks according to each engineer's expertise and remained accountable for the outcome.",
        "descriptionJa": 'リーダーとして仕事・役割を適切に配分した経験に使える。',
    },
    {
        "term": 'coordinate with',
        "meaningJa": '〜と調整を行う・神調を合わせる',
        "usageExample": 'I coordinated with security and operations to finalize the rollout plan.',
        "descriptionJa": '部署間・ステークホルダー間での合意形成を進めた際に使える。',
    },
    {
        "term": 'collaborate with',
        "meaningJa": '〜と協働する',
        "usageExample": 'I collaborated with platform engineers to design a maintainable deployment process.',
        "descriptionJa": '共通のゴールに向かって他チームと連携した文脈を言い表せる。',
    },
    {
        "term": 'align with',
        "meaningJa": '〜と整合性を取る・方向性を合わせる',
        "usageExample": 'I aligned with the security team before changing the authentication flow.',
        "descriptionJa": '方針や既存の設計・他チームの意図と一致させたことを表す。',
    },
    {
        "term": 'align on',
        "meaningJa": '〜について合意・認識合わせをする',
        "usageExample": 'We aligned on the naming convention before starting implementation.',
        "descriptionJa": '設計・仕様・基準などを着手前にすり合わせ、align on 命名として一致を明示。',
    },
    {
        "term": 'keep communication transparent',
        "meaningJa": 'コミュニケーションを透明に保つ',
        "usageExample": 'I kept communication transparent by sharing risks and progress every week.',
        "descriptionJa": '情報の隠蔽を防ぎ、進捗やリスクをオープンにした姿勢を表し、信頼関係の構築に使える。',
    },
    {
        "term": 'reach out to',
        "meaningJa": '〜に相談する・働きかける',
        "usageExample": 'I reached out to domain experts when the requirements were unclear.',
        "descriptionJa": '不明点や課題の解決のために、必要な専門家・担当者に自ら連絡したアプローチ。',
    },
    {
        "term": 'valuable feedback',
        "meaningJa": '貴重なフィードバック',
        "usageExample": 'I collected valuable feedback and used it to simplify the design.',
        "descriptionJa": '他者からの助言を柔軟に受け入れて改善につなげたことを表現する。',
    },
    {
        "term": 'share knowledge',
        "meaningJa": '知識を共有する',
        "usageExample": 'I shared knowledge through design reviews and short technical workshops.',
        "descriptionJa": '得た知見やノウハウをチーム全体へ展開した実績を示す。',
    },
    {
        "term": 'next steps',
        "meaningJa": '今後のステップ、次の行動',
        "usageExample": 'I summarized the decision and clarified the next steps for each team.',
        "descriptionJa": '議論や会議の結びに、次のアクションへ落とし込んだことを言及。',
    },
    {
        "term": 'accelerate delivery',
        "meaningJa": '開発・提供スピードを加速する',
        "usageExample": 'I automated the verification process to accelerate delivery without lowering quality.',
        "descriptionJa": '品質を維持しつつ、リリースまでのスピードを向上させた実績に使える。',
    },
    {
        "term": 'contribute to',
        "meaningJa": '〜に貢献する',
        "usageExample": 'I contributed to the platform by improving its deployment tooling.',
        "descriptionJa": '自身のアクションが基盤・成果・他チームの効率化へどう役立ったかを示す。',
    },
    {
        "term": 'positive impact',
        "meaningJa": '良い影響、良い効果',
        "usageExample": 'The change had a positive impact on both reliability and developer productivity.',
        "descriptionJa": '定量成果をまとめる際や、成果を広義に捉える時に使える表現。',
    },
    {
        "term": 'successfully completed',
        "meaningJa": '無事に完了した',
        "usageExample": 'We successfully completed the migration without customer-facing downtime.',
        "descriptionJa": 'STAR形式のResult（成果）部分で、完遂した実績を語る際に最適。',
    },
    {
        "term": 'from scratch',
        "meaningJa": 'ゼロから、何もない状態から',
        "usageExample": 'I built the pipeline from scratch and documented it for the team.',
        "descriptionJa": '既存コードの修正や既存枠組みではなく、新しくゼロから構築した主体性を強調できる。',
    },
    {
        "term": 'end-to-end',
        "meaningJa": '端から端まで、一貫して',
        "usageExample": 'I owned the feature end-to-end, from design through production monitoring.',
        "descriptionJa": '設計・実装・テスト・リリース・運用まで、全行程をカバーした範囲の広さをアピール。',
    },
    {
        "term": 'make a decision',
        "meaningJa": '意思決定をする',
        "usageExample": 'I made a decision after comparing the operational cost and reliability of both options.',
        "descriptionJa": '判断に至った根拠やトレードオフを明確にしつつ、意図的で主導した決断。',
    },
    {
        "term": 'decided to',
        "meaningJa": '〜することを決めた',
        "usageExample": 'We decided to prioritize reliability before adding new functionality.',
        "descriptionJa": '状況を分析した結果として何を選択したかをシンプルに示す。',
    },
    {
        "term": 'trade-off',
        "meaningJa": 'トレードオフ、トレードオフの考慮',
        "usageExample": 'The main trade-off was faster delivery versus long-term maintainability.',
        "descriptionJa": '一方を高めるために他方を犠牲にする関係性を明示する言語。',
    },
    {
        "term": 'review the requirements',
        "meaningJa": '要件を確認・レビューする',
        "usageExample": 'I reviewed the requirements with the stakeholders before estimating the work.',
        "descriptionJa": '着手前に要件の齟齬（そご）がないかを事前に検討し、認識違いを防いだ文脈。',
    },
    {
        "term": 'final scope',
        "meaningJa": '最終的に確定した範囲',
        "usageExample": 'Once we agreed on the final scope, I produced a realistic delivery plan.',
        "descriptionJa": '最終的な実装範囲・成果物の合意に達した状態を表現できる。',
    },
    {
        "term": 'focus on',
        "meaningJa": '〜に集中する、重点を置く',
        "usageExample": 'I focused on the highest-risk components first.',
        "descriptionJa": '限られた時間やリソースの中で優先度を絞って対応した姿勢を示す。',
    },
    {
        "term": 'short-term solution',
        "meaningJa": '短期的な応急処置',
        "usageExample": 'I proposed a short-term solution while we designed a more sustainable architecture.',
        "descriptionJa": '応急処置と恒久対策（長期解決策）を区別して説明した実績に使える。',
    },
    {
        "term": 'expected outcome',
        "meaningJa": '期待される成果',
        "usageExample": 'I defined the expected outcome before selecting the technical approach.',
        "descriptionJa": '目標成果をあらかじめ定義し、逆算して実装手法を決めた思考プロセス。',
    },
    {
        "term": 'experience with',
        "meaningJa": '〜を使った経験',
        "usageExample": 'I have five years of experience with distributed systems and cloud infrastructure.',
        "descriptionJa": '自らの技術スタックや経験年数を簡潔に提示する基本表現。',
    },
    {
        "term": 'opportunity to',
        "meaningJa": '〜する機会',
        "usageExample": 'I used the opportunity to lead a cross-functional migration project.',
        "descriptionJa": '新しい挑戦や学習の機会を前向きに捉えたことを示す。',
    },
    {
        "term": 'interested in',
        "meaningJa": '〜に関心がある',
        "usageExample": 'I am particularly interested in platform engineering and developer productivity.',
        "descriptionJa": '志望動機や今後関わりたい専門分野を伝える際に使える。',
    },
    {
        "term": 'track progress',
        "meaningJa": '進捗状況を追跡する',
        "usageExample": 'I tracked progress against weekly milestones and raised blockers early.',
        "descriptionJa": '進捗管理を行い、継続的に状況を把握していたことを示す。',
    },
    {
        "term": 'expected behavior',
        "meaningJa": '期待される動作',
        "usageExample": 'I documented the expected behavior and compared it with the production logs.',
        "descriptionJa": '不具合調査で、正しい仕様と実際の挙動の切り分けを行ったことを示す。',
    },
    {
        "term": 'current situation',
        "meaningJa": '現状、現在の状況',
        "usageExample": 'I began by explaining the current situation and the limitations of the existing design.',
        "descriptionJa": '概況（現状分析）から前提課題・制約を整理するときに言いやすい。',
    },
    {
        "term": 'as a result',
        "meaningJa": 'その結果として',
        "usageExample": 'As a result, release preparation time decreased from two days to three hours.',
        "descriptionJa": '行動と結果の論理的つながりを保ち、数言的で明確な説明に役立つ。',
    },
    {
        "term": 'resulted in',
        "meaningJa": '〜という結果をもたらした',
        "usageExample": 'The optimization resulted in lower latency and fewer timeouts.',
        "descriptionJa": '自身のアクションによって生じた具体的な成果への結びつけで用いる。',
    },
    {
        "term": 'operational gaps',
        "meaningJa": '運用上の不足・抜け漏れ',
        "usageExample": 'During the review, I identified operational gaps in monitoring and incident response.',
        "descriptionJa": '運用プロセスの課題に気付き、不備を発見したことを表す。',
    },
    {
        "term": 'design details',
        "meaningJa": '設計の詳細',
        "usageExample": 'I filled in the missing design details before handing the proposal to the implementation team.',
        "descriptionJa": '抽象的な提案を具体的な設計レベルまで落とし込んだ文脈に使える。',
    },
    {
        "term": 'project priorities',
        "meaningJa": 'プロジェクトの優先順位',
        "usageExample": 'I revisited the plan when the project priorities changed.',
        "descriptionJa": '優先度の変更に応じて計画やリソースを割り振り直した実績。',
    },
    {
        "term": 'scope and complexity',
        "meaningJa": '範囲と複雑さ',
        "usageExample": 'I estimated the timeline based on the scope and complexity of the migration.',
        "descriptionJa": 'プロジェクトの「規模（スコープ）」と「技術的難易度」を考慮して見積もりした根拠。',
    },
    {
        "term": 'short-term and long-term',
        "meaningJa": '短期的と長期的',
        "usageExample": 'I separated the improvements into short-term and long-term actions.',
        "descriptionJa": '目の前の課題解決と長期の改善を区別した計画性をアピール。',
    },
    {
        "term": 'make sure',
        "meaningJa": '確実にする、確認する',
        "usageExample": 'I added automated checks to make sure the data remained consistent.',
        "descriptionJa": '事故・不備を防ぐために自発的に手段を講じた文脈で使える。',
    },
    {
        "term": 'make sense',
        "meaningJa": '理にかなう、筋が通っている',
        "usageExample": 'It made sense to consolidate the components because they shared the same lifecycle.',
        "descriptionJa": '特定の設計手法やアプローチを選んだ理由を説明する際に使える。',
    },
    {
        "term": 'look into',
        "meaningJa": '〜を詳しく調べる',
        "usageExample": 'I looked into the intermittent failures and found a race condition.',
        "descriptionJa": '問題や不具合を調査・特定した行動を直接示す。',
    },
    {
        "term": 'move forward',
        "meaningJa": '前に進める、次の段階へ進む',
        "usageExample": 'Once we reached agreement, we moved forward with implementation.',
        "descriptionJa": '合意形成後の迅速な決定・実行へ押し進めたことを表す。',
    },
    {
        "term": 'roll out',
        "meaningJa": 'リリースする、順次展開する',
        "usageExample": 'We rolled out the feature to a small user group before the full release.',
        "descriptionJa": '段階的・計画的に新機能や変更を運用適用したプロセス。',
    },
    {
        "term": 'action items',
        "meaningJa": '具体的な対応項目',
        "usageExample": 'I converted the discussion into action items with clear owners and deadlines.',
        "descriptionJa": '会議や論議を実行可能なタスクへと落とし込んだ文脈。',
    },
    {
        "term": 'clear goal',
        "meaningJa": '明確な目標',
        "usageExample": 'I set a clear goal of reducing recovery time by at least 20%.',
        "descriptionJa": '抽象的な課題ではなく、測定可能で明確な目標を設定したこと。',
    },
    {
        "term": 'best approach',
        "meaningJa": '最善のアプローチ・手法',
        "usageExample": 'I evaluated three options and recommended the best approach for our constraints.',
        "descriptionJa": '複数の選択肢から条件・制約に最も適した手段を選択・提案した。',
    },
    {
        "term": 'current understanding',
        "meaningJa": '現在の理解・把握状況',
        "usageExample": 'I summarized my current understanding and asked the team to confirm it.',
        "descriptionJa": '認識の齟齬を防ぐため、前提をチームに共有してすり合わせたプロセスの説明。',
    },
    {
        "term": 'prioritize this work',
        "meaningJa": 'この作業の優先度を高くする',
        "usageExample": 'We prioritized this work because it affected a critical customer journey.',
        "descriptionJa": '業務の優先順位を判断し、理由とともに決定した実績。',
    },
    {
        "term": 'started the analysis',
        "meaningJa": '分析を開始した',
        "usageExample": 'I started the analysis by mapping the failure patterns across environments.',
        "descriptionJa": '問題解決や開発の初期の行動を具体的に述べる、STAR形式のActionとしての表現。',
    },
    {
        "term": 'address issues',
        "meaningJa": '課題・問題に対応する',
        "usageExample": 'We addressed issues in the build pipeline that were delaying releases.',
        "descriptionJa": '単に問題を認識しただけでなく、解決に向けて対応したこと。',
    },
    {
        "term": 'investigate the issue',
        "meaningJa": '問題の原因・状況を調査する',
        "usageExample": 'I investigated the issue by tracing permissions across the entire request path.',
        "descriptionJa": 'トラブルに対し自ら主導で調査を進めたアクション。',
    },
    {
        "term": 'clarify requirements',
        "meaningJa": '要件を明確にする',
        "usageExample": 'I met with the business team to clarify requirements and define acceptance criteria.',
        "descriptionJa": '曖昧だった条件や仕様を関係者から引き出し・整理した経験。',
    },
    {
        "term": 'define the scope',
        "meaningJa": '対象範囲を定義する',
        "usageExample": 'I defined the scope early to prevent the project from expanding uncontrollably.',
        "descriptionJa": 'スコープの肥大化（スコープクリープ）を防ぐために初めに枠組みを定義したこと。',
    },
    {
        "term": 'weigh the pros and cons',
        "meaningJa": '長所と短所を比較検討する',
        "usageExample": 'I weighed the pros and cons of centralizing the service before making a recommendation.',
        "descriptionJa": 'メリット・デメリットを客観的に比較して判断を下した根拠を示す。',
    },
    {
        "term": 'learn from others',
        "meaningJa": '他者から学ぶ',
        "usageExample": 'I learned from experienced engineers and incorporated their review practices into my work.',
        "descriptionJa": '他メンバーや過去の事例から学び、業務の質の向上に活かしている姿勢。',
    },
    {
        "term": 'streamline routine tasks',
        "meaningJa": '定型業務を効率化・簡素化する',
        "usageExample": 'I streamlined routine tasks so the team could focus on higher-value engineering work.',
        "descriptionJa": '定常作業の改善や自動化でチーム全体の成果を向上させることに貢献。',
    },
    {
        "term": 'automate daily work processes',
        "meaningJa": '日常業務プロセスを自動化する',
        "usageExample": 'I automated daily work processes and saved the team several hours each week.',
        "descriptionJa": '手作業の削減や効率化の実績として数値とともに表現できる。',
    },
    {
        "term": 'ensure consistency',
        "meaningJa": '一貫性を確保する',
        "usageExample": 'I introduced a shared template to ensure consistency across all services.',
        "descriptionJa": '設計・運用の方法や品質のばらつきを揃え組織全体で標準化した実績。',
    },
    {
        "term": 'stay on schedule',
        "meaningJa": '予定どおり進める',
        "usageExample": 'I reduced the initial scope so we could stay on schedule without compromising critical quality.',
        "descriptionJa": '期日を守るために行なった工夫やトレードオフ決定の結果として使う。',
    },
    {
        "term": 'cross-functional scope',
        "meaningJa": '複数職種・複数領域にまたがる範囲',
        "usageExample": 'The project had a cross-functional scope involving engineering, security, and operations.',
        "descriptionJa": '影響範囲や関係者の幅広さ、組織横断プロジェクトだったことを説明できる。',
    },
    {
        "term": 'make an informed decision',
        "meaningJa": '十分な情報に基づいて判断する',
        "usageExample": 'I gathered usage data and security requirements to make an informed decision.',
        "descriptionJa": '勘や経験だけでなく、情報やデータ・根拠を収集して判断した姿勢。',
    },
    {
        "term": 'make a technical decision',
        "meaningJa": '技術的な意思決定を行う',
        "usageExample": 'I made the technical decision to separate the services based on their scaling requirements.',
        "descriptionJa": 'アーキテクチャや技術選定における決断のロジックを示す。',
    },
    {
        "term": 'promote continuous improvement',
        "meaningJa": '継続的な改善を推進する',
        "usageExample": 'I introduced regular retrospectives to promote continuous improvement.',
        "descriptionJa": '単発の対応ではなく、チーム文化として改善の仕組みづくりを行ったこと。',
    },
    {
        "term": 'solve complex problems',
        "meaningJa": '複雑な問題を解決する',
        "usageExample": 'I enjoy solving complex problems that require technical depth and stakeholder coordination.',
        "descriptionJa": '高度な技術的課題や、関係者の調整が必要な複雑な課題に対応できる能力を示す。',
    },
    {
        "term": 'work independently',
        "meaningJa": '自律的に仕事を進める',
        "usageExample": 'I worked independently on the investigation while keeping the team updated.',
        "descriptionJa": 'マイクロマネジメントを受けずに高い自律性を持って対応できること。',
    },
    {
        "term": 'take a data-driven approach',
        "meaningJa": 'データに基づくアプローチを取る',
        "usageExample": 'I took a data-driven approach and prioritized failures with the highest customer impact.',
        "descriptionJa": '主観ではなくデータに基づいて分析や意思決定を行ったことを示す。',
    },
    {
        "term": 'provide guidance',
        "meaningJa": '指導・アドバイスを提供する',
        "usageExample": 'I provided guidance to junior engineers during the design and review phases.',
        "descriptionJa": 'メンターやシニアとして後輩の手助けや育成をした実績に使える。',
    },
    {
        "term": 'align stakeholders',
        "meaningJa": 'ステークホルダー（利害関係者）の方向性を揃える',
        "usageExample": 'I aligned stakeholders around a shared rollout plan and success criteria.',
        "descriptionJa": '複数部署や異なる意見の利害関係者を調整し、合意をまとめたこと。',
    },
    {
        "term": 'provide knowledge transfer',
        "meaningJa": '知識引き継ぎ・ナレッジ共有を行う',
        "usageExample": 'I provided knowledge transfer so the operations team could maintain the service independently.',
        "descriptionJa": '開発後に運用・他チームへナレッジをスムーズに引き継いだ実績。',
    },
    {
        "term": 'drive the transformation forward',
        "meaningJa": '変革・改善を推し進める',
        "usageExample": 'I helped drive the transformation forward by turning broad goals into executable milestones.',
        "descriptionJa": '組織や運用の大きな改革・改善を主導した場面に使える。',
    },
    {
        "term": 'keep discussions solution-oriented',
        "meaningJa": '議論を解決志向に保つ',
        "usageExample": 'During the disagreement, I kept the discussion solution-oriented and focused on shared goals.',
        "descriptionJa": '意見の対立が起きた際に、建設的な議論に導いた実績。',
    },
    {
        "term": 'proactively enhance',
        "meaningJa": '先回りして強化・改善する',
        "usageExample": 'I proactively enhanced the test framework before the project entered its critical phase.',
        "descriptionJa": '指示される前や問題が起きる前に、自主的に対策を行った実績を示す。',
    },
    {
        "term": 'improve monitoring coverage',
        "meaningJa": '監視範囲を改善する',
        "usageExample": 'I improved monitoring coverage by adding missing alerts and dashboards.',
        "descriptionJa": 'システムの可視性や検知能力を高めるため監視範囲を広げた実績。',
    },
    {
        "term": 'provide visibility into',
        "meaningJa": '〜を可視化する、見られるようにする',
        "usageExample": 'The dashboard provided visibility into deployment health and resource usage.',
        "descriptionJa": '不透明だったデータや運用状況を視覚化して把握できるようにした功績。',
    },
    {
        "term": 'work within the scope',
        "meaningJa": 'スコープの範囲内で作業する',
        "usageExample": 'I worked within the agreed scope and documented additional requests for a later phase.',
        "descriptionJa": 'スコープ肥大化（スコープクリープ）を防ぎ、計画通りの枠組み内で成果を出したこと。',
    },
    {
        "term": 'provide timelines',
        "meaningJa": 'スケジュール・見通しを提示する',
        "usageExample": 'After reviewing the requirements, I provided timelines with clear assumptions and risks.',
        "descriptionJa": '根拠ある見積もりに基づいた具体的な完成・リリース目標を設定・提示した。',
    },
    {
        "term": 'align on common goals',
        "meaningJa": '共通の目標について意識を合わせる',
        "usageExample": 'I brought the teams together to align on common goals before discussing implementation details.',
        "descriptionJa": '実装の詳細に踏み込む前に、全体の共通目標を整理・共有したこと。',
    },
    {
        "term": 'execute in a phased manner',
        "meaningJa": '段階的に実行する',
        "usageExample": 'We executed the migration in a phased manner to limit operational risk.',
        "descriptionJa": '一括（ビッグバン）変更のリスクを避け、リスク管理をして段階的に実行したこと。',
    },
    {
        "term": 'make a measurable impact',
        "meaningJa": '測定可能な明確なインパクト（成果）を生む',
        "usageExample": 'I made a measurable impact by reducing deployment time by 40%.',
        "descriptionJa": '数字や指標など定量的成果（KPI向上等）をあげた際のアピール表現。',
    },
    {
        "term": 'take action',
        "meaningJa": '行動を起こす、対策を実行する',
        "usageExample": 'Once I confirmed the risk, I took action before it affected production.',
        "descriptionJa": '問題の観察だけに終始するのではなく、実際の対処・対応へ動いた主導性を示す。',
    },
    {
        "term": 'follow through on',
        "meaningJa": '〜を最後（最後までやり遂げる）',
        "usageExample": 'I followed through on every action item and confirmed the fixes in production.',
        "descriptionJa": '途中で投げ出さずに最後まで責任を持ってやり完了させた報告。',
    },
    {
        "term": 'work toward a goal',
        "meaningJa": '目標の達成に向けて取り組む',
        "usageExample": 'We worked toward a shared goal of restoring the service safely.',
        "descriptionJa": 'チームや個人のゴールに向かって一貫した取り組みを完了させた過程。',
    },
    {
        "term": 'improve future outcomes',
        "meaningJa": '今後の成果・結果を改善する',
        "usageExample": 'We used feedback to improve future outcomes and refine the program.',
        "descriptionJa": '事後振り返り（レトロスペクティブ）を通じて、将来の質の向上へ活かした文脈。',
    },
    {
        "term": 'take constraints into consideration',
        "meaningJa": '制約条件を考慮に入れる',
        "usageExample": 'I took security, cost, and delivery constraints into consideration before selecting the architecture.',
        "descriptionJa": '技術面だけでなく、ビジネス上の制限や制約を踏まえて判断した実績。',
    },
    {
        "term": 'proactively onboard new members',
        "meaningJa": '新しいメンバーを先回りして受け入れ、立ち上がりを支援する',
        "usageExample": 'I proactively onboarded new members by preparing documentation and pairing with them during their first sprint.',
        "descriptionJa": '新規参入者の早期オンボーディングのための手厚いサポートやメンター能力を表現できる。',
    },
    {
        "term": 'step up when the team needs you',
        "meaningJa": 'チームがピンチの時や必要な場面で、主導権をとってサポートする',
        "usageExample": 'I stepped up when the team needed an interim technical lead during a critical release.',
        "descriptionJa": '突発的な緊急事態や役割の空白に対し、自発的に責任を引き受け対処した実績。',
    },
    {
        "term": 'adapt to changes',
        "meaningJa": '変化に適応する',
        "usageExample": 'I adapted to changing priorities by revising the plan and reallocating testing effort.',
        "descriptionJa": '優先順位、リスク、制約などの急な変化に応じて柔軟に行動を変更対応した経験。',
    },
    {
        "term": 'execute without unnecessary delay',
        "meaningJa": '不必要な遅延なしに速やかに実行する',
        "usageExample": 'Once the scope was clear, I executed the recovery plan without unnecessary delay.',
        "descriptionJa": '無駄な躊躇（ちゅうちょ）なく、スムーズかつ迅速に実行に移した敏捷性。',
    },
    {
        "term": 'strike a better balance',
        "meaningJa": 'より良いバランスを取る、うまい折衷案を見つける',
        "usageExample": 'I proposed a hybrid strategy to strike a better balance between autonomy and consistency.',
        "descriptionJa": '二律背反する要素（スピードと品質、自由度と管理など）のバランスを取った技術的判断。',
    },
    {
        "term": 'reduce friction',
        "meaningJa": '手間や摩擦、障害を減らす',
        "usageExample": 'I standardized the setup process to reduce friction for engineers joining the project.',
        "descriptionJa": 'オンボーディングや開発プロセスの負荷・摩擦を軽減し、作業効率・体験を向上させた実績。',
    },
    {
        "term": 'meet expectations',
        "meaningJa": '期待に応える、要求水準を満たす',
        "usageExample": "I adjusted the implementation to meet the stakeholders' expectations without weakening security.",
        "descriptionJa": 'ステークホルダーの意図や期待値を踏まえ、それに応えるために行動したことを表す。',
    },
    {
        "term": 'work with limited bandwidth',
        "meaningJa": '限られた時間・人的余裕の中で取り組む',
        "usageExample": 'We had to work with limited bandwidth, so I prioritized the highest-risk scenarios first.',
        "descriptionJa": 'リソース不足・時間制限のある厳しい状況下で、優先順位を設けて対応した実績。',
    },
    {
        "term": 'miss out on',
        "meaningJa": '〜を逃す、〜を機会を取りこぼす',
        "usageExample": 'Without a shared review process, we could miss out on useful contributions from other teams.',
        "descriptionJa": 'プロセスの欠陥やリスクとして「〜を逃す」可能性の指摘。',
    },
    {
        "term": 'identify common pain points',
        "meaningJa": '共通して直面する課題や痛点を特定する',
        "usageExample": 'I interviewed several teams to identify common pain points in the deployment process.',
        "descriptionJa": '組織内の不満や不便の根本原因を明確化して環境改善を図った実績。',
    },
    {
        "term": 'work alongside the team',
        "meaningJa": 'チームと並行して協力して働く',
        "usageExample": 'I worked alongside the team for two sprints to establish the new automation practices.',
        "descriptionJa": '上からの指示だけではなく、一定期間チームに入り込み伴走型で共に適応・支援した経験。',
    },
    {
        "term": 'improve your skills',
        "meaningJa": '自分のスキルを向上させる',
        "usageExample": 'I improved my skills in availability by handling incidents and studying their failure patterns.',
        "descriptionJa": '実務経験や学習を通じて技術力向上を継続している姿勢を示す。',
    },
    {
        "term": 'allow time for learning and investigation',
        "meaningJa": '学習と調査のための時間を確保する',
        "usageExample": 'Because the domain was new to us, I allowed time for learning and investigation in the estimate.',
        "descriptionJa": '未知の技術領域に対し、見積もり段階で学習期間を確保した計画性。',
    },
    {
        "term": 'account for work in the plan',
        "meaningJa": '作業を作業計画にあらかじめ考慮・盛り込む',
        "usageExample": 'I accounted for migration testing and rollback preparation in the delivery plan.',
        "descriptionJa": '必要な作業（テストや移行・リハーサル等）を漏れなく予備時間・リスク管理として計画に含めた。',
    },
]
