"""User-provided Design / Architecture vocabulary fields (106 entries)."""

USER_ENTRIES: list[dict] = [{'term': 'lean towards an option',
  'meaningJa': '選択肢のうち一つに傾いている',
  'usageExample': 'We lean towards the relational option because future reporting requires joins.',
  'descriptionJa': '設計議論で複数案のうち一方向に傾いている状態を述べる表現。'},
 {'term': 'an appropriate approach',
  'meaningJa': '妥当な進め方・設計方針',
  'usageExample': 'Please review whether event sourcing is an appropriate approach for this audit trail.',
  'descriptionJa': '提案する設計方針が妥当かどうか確認を求める際に使う。'},
 {'term': 'resource-based approach',
  'meaningJa': 'リソース単位で構成する設計方針',
  'usageExample': 'We use a resource-based approach so each endpoint represents a stable domain entity.',
  'descriptionJa': 'APIやシステムをリソース単位で設計する方針を説明する。'},
 {'term': 'schema-less design',
  'meaningJa': '固定スキーマを持たない設計',
  'usageExample': 'A schema-less design may suit preferences whose nested fields change frequently.',
  'descriptionJa': '固定スキーマを持たない柔軟なデータ設計を指す。'},
 {'term': 'generalized design',
  'meaningJa': '特定用途に偏らない汎用化された設計',
  'usageExample': 'The goal is a generalized design to let us add new preference types without changing the storage '
                  'model.',
  'descriptionJa': '特定用途に偏らない汎用的な設計方針を述べる。'},
 {'term': 'design constraints',
  'meaningJa': '設計上の制約事項',
  'usageExample': 'These design constraints require stable identifiers and RESTful endpoints.',
  'descriptionJa': '設計上守るべき制約条件を列挙・確認するときに使う。'},
 {'term': 'challenge your assumptions',
  'meaningJa': '前提条件を疑う・再検証する',
  'usageExample': 'The architecture team wants to challenge your assumptions about peak traffic.',
  'descriptionJa': '設計の前提条件を疑い、再検証するよう促す表現。'},
 {'term': 'compare DB alternatives',
  'meaningJa': 'データベースの代替案を比較する',
  'usageExample': 'The ADR should compare DB alternatives against query patterns and operational cost.',
  'descriptionJa': 'ADRなどでデータベースの代替案を比較するときに使う。'},
 {'term': 'a special case',
  'meaningJa': '例外処理や特別なケース',
  'usageExample': 'Account recovery is a special case because the normal authentication context is unavailable.',
  'descriptionJa': '通常フローとは異なる例外ケースを設計で扱う際に使う。'},
 {'term': 'distinguish between design and implementation',
  'meaningJa': '設計と実装の違いを明確にする',
  'usageExample': 'The ADR should distinguish between design and implementation so the decision remains stable.',
  'descriptionJa': '設計判断と実装詳細を分けて文書化する必要性を述べる。'},
 {'term': 'bypass downstream guards',
  'meaningJa': '後続のガード処理を迂回する',
  'usageExample': 'This change must not bypass downstream guards that enforce eligibility rules.',
  'descriptionJa': '後続のガード処理を迂回してはならないと警告する表現。'},
 {'term': 'break existing behavior',
  'meaningJa': '既存の挙動を壊す',
  'usageExample': 'Changing the middleware order may break existing behavior for returning users.',
  'descriptionJa': '変更が既存の挙動を壊す可能性があると述べる。'},
 {'term': 'based on agreement',
  'meaningJa': '合意に基づいて',
  'usageExample': 'Based on agreement, performance tests will use mocked upstream services.',
  'descriptionJa': 'チーム合意に基づいて方針や作業を進めることを示す。'},
 {'term': 'long-term fix',
  'meaningJa': '恒久的な修正・根本解決',
  'usageExample': 'Schema versioning is the long-term fix; the parser fallback is temporary.',
  'descriptionJa': '暫定対応ではなく恒久的な根本解決策を指す。'},
 {'term': 'fallback JSON',
  'meaningJa': '代替用・退避用のJSONデータ',
  'usageExample': 'We return a fallback JSON when the remote configuration is unavailable.',
  'descriptionJa': '本番データが利用不可のとき返す代替JSONを指す。'},
 {'term': 'default fallbacks',
  'meaningJa': 'デフォルトの代替手段・代用値',
  'usageExample': 'The client can serve as default fallbacks during an outage.',
  'descriptionJa': '障害時や未設定時に使うデフォルトの代替値を指す。'},
 {'term': 'a common pattern',
  'meaningJa': '複数チームで共有できる共通パターン',
  'usageExample': 'This ownership transfer could become a common pattern for small cross-squad features.',
  'descriptionJa': '他チームでも再利用できる共通パターンとして設計する意図を述べる。'},
 {'term': 'extend it easily',
  'meaningJa': '容易に拡張できる',
  'usageExample': 'Keep the policy model generic so we can extend it easily for new roles.',
  'descriptionJa': '将来の拡張が容易な設計にしておくべきだと述べる。'},
 {'term': 'future use cases',
  'meaningJa': '将来想定される利用ケース',
  'usageExample': 'The storage key should accommodate future use cases without a breaking migration.',
  'descriptionJa': '将来想定される利用ケースを設計に織り込む必要性を述べる。'},
 {'term': 'proper setup',
  'meaningJa': '前提条件を揃えた適正な構成',
  'usageExample': 'We need a proper setup for backups, migrations, and access control.',
  'descriptionJa': 'バックアップやアクセス制御など前提条件を整えた構成を指す。'},
 {'term': 'cross-squad dependency',
  'meaningJa': '複数スクワッド間にまたがる依存関係',
  'usageExample': 'This endpoint creates a cross-squad dependency that must be reflected in the delivery plan.',
  'descriptionJa': '複数スクワッドにまたがる依存関係を設計で扱う表現。'},
 {'term': 'external dependencies',
  'meaningJa': '外部依存関係',
  'usageExample': 'The gateway should not pass external dependencies to avoid affecting other applications.',
  'descriptionJa': '外部システムへの依存関係を設計で明示・管理する表現。'},
 {'term': 'page responsibilities',
  'meaningJa': '各ページの役割・責務の境界',
  'usageExample': 'The architecture document should define page responsibilities and navigation boundaries.',
  'descriptionJa': '各ページの役割と責務の境界を設計文書で定義する表現。'},
 {'term': 'technical ownership',
  'meaningJa': '特定のコンポーネントやシステムの技術的責任',
  'usageExample': 'Technical ownership belongs to the platform team, while prioritization stays with the squad lead.',
  'descriptionJa': 'コンポーネントやシステムの技術的責任の所在を述べる。'},
 {'term': 'increased responsibility',
  'meaningJa': 'より大きな管理責任・責務',
  'usageExample': 'Moving the service inside the boundary increases responsibility for retention and access control.',
  'descriptionJa': '設計変更により管理責任が大きくなることを示す。'},
 {'term': 'cost of cross-squad coordination',
  'meaningJa': 'スクワッド間調整にかかるコスト',
  'usageExample': 'The cost of cross-squad coordination may exceed the implementation cost for this small change.',
  'descriptionJa': 'スクワッド間調整コストが実装コストを上回る可能性を述べる。'},
 {'term': 'implementation cost',
  'meaningJa': '開発・実装にかかる工数やコスト',
  'usageExample': 'We should compare the implementation cost with the operational savings.',
  'descriptionJa': '開発・実装にかかる工数やコストを比較検討するときに使う。'},
 {'term': 'the scopes are yet to be finalized',
  'meaningJa': 'スコープが未確定である',
  'usageExample': 'The scopes are yet to be finalized, so the key structure should remain flexible.',
  'descriptionJa': 'スコープが未確定のため設計を柔軟に保つ必要があると述べる。'},
 {'term': 'outside the scope',
  'meaningJa': '今回の対象範囲外',
  'usageExample': 'Data migration for legacy users is outside the scope of this migration.',
  'descriptionJa': '今回の対象範囲外であることを明確にする表現。'},
 {'term': 'in this scope',
  'meaningJa': '今回の対象範囲内',
  'usageExample': 'We will update the preferences API in this scope.',
  'descriptionJa': '今回の対象範囲内で対応することを示す。'},
 {'term': 'future scopes',
  'meaningJa': '今後の検討範囲・拡張範囲',
  'usageExample': 'There are concerns regarding future scopes, so the identifier decision needs further discussion.',
  'descriptionJa': '今後の検討範囲や拡張範囲に関する懸念を述べる。'},
 {'term': 'resource-based endpoints',
  'meaningJa': 'リソース（概念）単位に特化したエンドポイント',
  'usageExample': 'We split the API into resource-based endpoints for users and cards.',
  'descriptionJa': 'リソース単位に分割したAPIエンドポイント設計を指す。'},
 {'term': 'API contract',
  'meaningJa': 'APIインターフェースの契約・取り決め',
  'usageExample': 'The API contract must distinguish user identifiers from card identifiers.',
  'descriptionJa': 'APIのインターフェース契約・取り決めを設計で定義する表現。'},
 {'term': 'separate user identifiers from card identifiers',
  'meaningJa': 'ユーザーIDとカードIDの識別子を区別する',
  'usageExample': 'We should separate user identifiers from card identifiers to avoid ambiguous resources.',
  'descriptionJa': '異なるエンティティの識別子を混同しない設計を述べる。'},
 {'term': 'proper entity identifier',
  'meaningJa': '適切な実体・エンティティの識別子',
  'usageExample': 'Prefer a proper entity identifier rather than an unrelated card ID.',
  'descriptionJa': 'ドメインエンティティに適切な識別子を使うべきだと述べる。'},
 {'term': 'common schema',
  'meaningJa': '全体で共有する共通のスキーマ',
  'usageExample': 'Define a common schema for identifiers used across all OpenAPI paths.',
  'descriptionJa': '複数サービス間で共有する共通スキーマを定義する表現。'},
 {'term': 'schema mismatch',
  'meaningJa': '定義・不一致による不整合や不統一',
  'usageExample': 'The client and server must map enum values to resolve the schema mismatch.',
  'descriptionJa': 'クライアントとサーバー間のスキーマ不一致を解消する表現。'},
 {'term': 'generated OpenAPI schema',
  'meaningJa': 'コードなどから自動生成されたOpenAPI定義（スキーマ）',
  'usageExample': 'Runtime validation and the generated OpenAPI schema must expose the same enum values.',
  'descriptionJa': 'コードから自動生成されたOpenAPI定義を設計で参照する表現。'},
 {'term': 'schema versioning',
  'meaningJa': 'スキーマにバージョンを持たせて変化を管理すること',
  'usageExample': 'Consider schema versioning to allow modern clients to parse configuration during the transition.',
  'descriptionJa': 'スキーマ変更をバージョン管理で段階的に移行する設計手法。'},
 {'term': 'backward compatible',
  'meaningJa': '以前の形式や仕様との互換性を保つこと',
  'usageExample': 'The new fields should be backward compatible with the previous response shape.',
  'descriptionJa': '新旧仕様の互換性を保つ設計方針を述べる。'},
 {'term': 'breaking changes',
  'meaningJa': '仕様変更により必要となる非互換な変更',
  'usageExample': 'Breaking changes on BFF side should be announced before non-engineering teams begin testing.',
  'descriptionJa': '非互換な仕様変更が必要になることを事前に周知する表現。'},
 {'term': 'support two schemas',
  'meaningJa': '新旧2つのデータ形式（スキーマ）を移行期間中に両立させること',
  'usageExample': 'The client should support two schemas before the producer changes its format.',
  'descriptionJa': '移行期間中に新旧2つのスキーマを両立させる設計を述べる。'},
 {'term': 'make the endpoint flexible',
  'meaningJa': 'エンドポイントに柔軟性を持たせる',
  'usageExample': 'We should make the endpoint flexible enough to add new preference categories.',
  'descriptionJa': '将来の拡張に備えエンドポイントに柔軟性を持たせる表現。'},
 {'term': 'extend the interface',
  'meaningJa': 'インターフェース（外部との接点・接続形式）を拡張する',
  'usageExample': 'We can extend the interface with an explicit audience field while preserving defaults.',
  'descriptionJa': '既存インターフェースを拡張しつつ後方互換を保つ設計を述べる。'},
 {'term': 'improve the interface and LLD',
  'meaningJa': 'インターフェースと詳細設計（LLD）を改善する',
  'usageExample': 'We should improve the interface and LLD so the default behavior is explicit.',
  'descriptionJa': 'インターフェースと詳細設計を改善する必要性を述べる。'},
 {'term': 'default behavior',
  'meaningJa': '明示的な指定がない場合の既定の動作',
  'usageExample': 'Document the default behavior when the audience field is omitted.',
  'descriptionJa': '明示的指定がない場合の既定動作を設計文書で定義する表現。'},
 {'term': 'business exceptions',
  'meaningJa': '業務ルール・ユースケース上の例外パターン',
  'usageExample': 'The design document should capture business exceptions for suspended accounts.',
  'descriptionJa': '業務ルール上の例外パターンを設計文書に記載する表現。'},
 {'term': 'state transitions',
  'meaningJa': '状態（ステータス）の遷移',
  'usageExample': 'Tests must cover state transitions from pending to active and rejected.',
  'descriptionJa': 'エンティティの状態遷移を設計・テストで扱う表現。'},
 {'term': 'relational queries',
  'meaningJa': 'テーブル間の関係を利用するクエリ',
  'usageExample': 'Choose a relational database if future use cases require relational queries.',
  'descriptionJa': 'テーブル間の関係を利用するクエリ要件を設計判断に使う表現。'},
 {'term': 'persistence layer',
  'meaningJa': 'データを永続保存する層',
  'usageExample': 'User preferences belong in the persistence layer rather than a transient cache.',
  'descriptionJa': 'データ永続化層への配置を設計で決定するときに使う。'},
 {'term': 'stored client-side unregulated',
  'meaningJa': 'クライアント側に無制限に保存されている',
  'usageExample': 'If data is stored client-side unregulated, so retention rules are not enforced.',
  'descriptionJa': 'クライアント側に無制限保存されるリスクを指摘する表現。'},
 {'term': 'cached mapping incomplete',
  'meaningJa': 'キャッシュされた対応関係（マップデータ）の不足や不完全な状態',
  'usageExample': 'A failed update can cause the cached mapping incomplete after account creation.',
  'descriptionJa': 'キャッシュされた対応関係が不完全になる問題を述べる。'},
 {'term': 'get the latest mapping on every request',
  'meaningJa': 'リクエストごとに最新の対応関係を取得する',
  'usageExample': 'For critical workflows, we get the latest mapping on every request instead of reading stale cache '
                  'data.',
  'descriptionJa': '重要フローでは毎リクエスト最新マッピングを取得する設計。'},
 {'term': 'instead of using the cache',
  'meaningJa': 'キャッシュを使わない',
  'usageExample': 'The read path calls the authoritative service instead of using the cache.',
  'descriptionJa': 'キャッシュではなく正規データソースを参照する設計判断。'},
 {'term': 'cache the response',
  'meaningJa': 'レスポンス（応答データ）をキャッシュする',
  'usageExample': 'We can cache the response briefly to reduce repeated upstream calls.',
  'descriptionJa': 'レスポンスを短時間キャッシュして負荷を下げる設計を述べる。'},
 {'term': 'objects within objects',
  'meaningJa': 'オブジェクトの中にネストされたオブジェクト',
  'usageExample': 'We store nested preferences as objects within objects without a disruptive schema change.',
  'descriptionJa': 'ネストされたオブジェクト構造でデータを保持する設計。'},
 {'term': 'mock external dependencies',
  'meaningJa': '外部依存先モジュールをモック（模擬化）に置き換える',
  'usageExample': 'Integration tests should mock external dependencies to isolate the service under test.',
  'descriptionJa': '統合テストで外部依存をモック化する設計方針。'},
 {'term': 'avoid unnecessary loads',
  'meaningJa': '不要な高負荷を避ける',
  'usageExample': 'The profile header component should avoid unnecessary loads on the profile service.',
  'descriptionJa': '不要な高負荷を避ける設計・実装方針を述べる。'},
 {'term': 'reduce expensive API calls',
  'meaningJa': 'コストの高いAPI呼び出しを減らす',
  'usageExample': 'A short-lived cache can reduce expensive API calls on every page transition.',
  'descriptionJa': 'コストの高いAPI呼び出しを減らす設計判断を述べる。'},
 {'term': 'no heavy processing',
  'meaningJa': '負荷の高い処理（重い処理）を行わない',
  'usageExample': 'The BFF layer does only validation only, with no heavy processing on the backend.',
  'descriptionJa': 'BFFなどで重い処理を行わない設計方針を述べる。'},
 {'term': 'API-level performance risk',
  'meaningJa': 'API単位（処理レベル）でのパフォーマンス低下リスク',
  'usageExample': 'API-level performance risk seems to be relatively low because the handler performs no additional '
                  'I/O.',
  'descriptionJa': 'API単位でのパフォーマンス低下リスクを評価する表現。'},
 {'term': 'higher latency',
  'meaningJa': 'レイテンシー（応答速度）の増大・遅延',
  'usageExample': 'Any higher latency must remain visible in the monitoring histogram.',
  'descriptionJa': 'レイテンシ増大を監視で可視化する必要があると述べる。'},
 {'term': 'reflect real latency',
  'meaningJa': '実際の遅延（レイテンシー）を正しく反映する',
  'usageExample': 'Ensure trace sampling is set to reflect real latency in production.',
  'descriptionJa': '本番の実際のレイテンシを正しく反映する設計を述べる。'},
 {'term': 'performance improvements',
  'meaningJa': 'パフォーマンス（応答性・処理能力）の向上・改善',
  'usageExample': 'A smaller payload offers meaningful performance improvements for large configuration files.',
  'descriptionJa': 'ペイロード削減などによる性能改善効果を述べる。'},
 {'term': 'ensure compatibility with the latest frameworks',
  'meaningJa': '最新のフレームワーク・ライブラリとの互換性を確保する',
  'usageExample': 'The build script must ensure compatibility with the latest frameworks.',
  'descriptionJa': '最新フレームワークとの互換性を確保する設計要件。'},
 {'term': 'reduce the risk of',
  'meaningJa': '〜のリスクを軽減・低減させる',
  'usageExample': 'Sanitizing logs helps to reduce the risk of exposing diagnostic data.',
  'descriptionJa': '特定のリスクを軽減する設計・運用対策を述べる。'},
 {'term': 'diagnostic data being exposed',
  'meaningJa': '診断用・ログ情報が外部に露出すること',
  'usageExample': 'Careless error logging must prevent diagnostic data being exposed in the browser console.',
  'descriptionJa': '診断情報が外部に露出するリスクを防ぐ設計を述べる。'},
 {'term': 'edge cases we may have missed',
  'meaningJa': '見落としている可能性のある例外・特殊ケース',
  'usageExample': 'Please flag any edge cases we may have missed before the rollout.',
  'descriptionJa': '見落とし得る例外ケースを確認してほしいと依頼する表現。'},
 {'term': 'regression risk',
  'meaningJa': '仕様変更・修正によってデグレ（先祖返り・機能不全）が発生するリスク',
  'usageExample': 'What is the regression risk for clients still using the legacy identifier?',
  'descriptionJa': '仕様変更によるデグレリスクを評価・確認する表現。'},
 {'term': 'potential side effects',
  'meaningJa': '起こり得る副作用・予期せぬ影響',
  'usageExample': 'We should assess potential side effects on the legacy application before merging.',
  'descriptionJa': 'マージ前に想定される副作用を評価する表現。'},
 {'term': 'prevent PII leaks',
  'meaningJa': '個人情報（PII）の漏洩を防ぐ',
  'usageExample': 'Log masks for structured error fields to prevent PII leaks through application logs.',
  'descriptionJa': 'ログ等から個人情報漏洩を防ぐ設計対策を述べる。'},
 {'term': 'unmasked PII',
  'meaningJa': 'マスキング（伏字処理）されていない個人情報',
  'usageExample': 'An error response may contain unmasked PII and must not be written to the console.',
  'descriptionJa': 'マスキングされていない個人情報が含まれるリスクを指摘する。'},
 {'term': 'publicly exposed',
  'meaningJa': 'インターネットなどから誰でもアクセス可能な状態になっている',
  'usageExample': 'Internal endpoints should not be publicly exposed through feature-flag maps.',
  'descriptionJa': '内部エンドポイントが外部公開されるリスクを述べる。'},
 {'term': 'attack surface management',
  'meaningJa': '攻撃対象領域（アタックサーフェス）を網羅的に把握・管理する脅威管理',
  'usageExample': 'Effective attack surface management should detect publicly reachable internal endpoints.',
  'descriptionJa': '攻撃対象領域を網羅的に把握・管理するセキュリティ設計。'},
 {'term': 'access control',
  'meaningJa': '利用者やシステムに応じたアクセス権限を制御する仕組み',
  'usageExample': 'The gateway provides access control based on audience and authentication state.',
  'descriptionJa': '利用者や認証状態に応じたアクセス権限制御を述べる。'},
 {'term': 'assume true in the case of failure',
  'meaningJa': '失敗時に「真（True/許可）」と仮定して処理を継続する危険な設計',
  'usageExample': 'We must not assume true in the case of failure for a security-sensitive flag.',
  'descriptionJa': '失敗時に許可と仮定する危険な設計パターンを警告する。'},
 {'term': 'rollback mechanism',
  'meaningJa': '変更・リリースを元に戻すための切り戻し手順や仕組み',
  'usageExample': 'We should test the rollback mechanism before routing production traffic to the new stack.',
  'descriptionJa': 'リリースを元に戻す切り戻し手順・仕組みを設計する表現。'},
 {'term': 'risk of rollback',
  'meaningJa': '切り戻し（ロールバック）に伴うリスク（データ不整合など）',
  'usageExample': 'The risk of rollback is high if the old schema cannot read newly written records.',
  'descriptionJa': 'ロールバックに伴うデータ不整合などのリスクを評価する。'},
 {'term': 'rollback immediately',
  'meaningJa': '異常（デグレ・エラー率高騰など）を検知した際に即座に旧バージョンへ切り戻す対応',
  'usageExample': 'If the error rate crosses the threshold, we must rollback immediately.',
  'descriptionJa': '異常検知時に即座に旧バージョンへ切り戻す対応を述べる。'},
 {'term': 'phase out',
  'meaningJa': '段階的に廃止・廃版（非推奨）にしていくこと',
  'usageExample': 'We will phase out the legacy token after all clients adopt the new identity model.',
  'descriptionJa': 'レガシー機能を段階的に廃止していく移行計画を述べる。'},
 {'term': 'switch to the new endpoint',
  'meaningJa': '新しいエンドポイントへ切り替える',
  'usageExample': 'Clients can switch to the new endpoint after staging compatibility tests pass.',
  'descriptionJa': '新エンドポイントへの切り替えタイミングを述べる。'},
 {'term': 'organize the parts that need replacing',
  'meaningJa': '置き換えが必要な部品・モジュールを整理・特定する',
  'usageExample': 'Before migration, organize the parts that need replacing and identify their owners.',
  'descriptionJa': '移行前に置き換え対象を整理・特定する表現。'},
 {'term': 'migrated without much hassle',
  'meaningJa': '大きな問題や手間もなくスムーズに移行完了できたこと',
  'usageExample': 'The records can be migrated without much hassle because the model has no joins.',
  'descriptionJa': '大きな問題なくスムーズに移行完了できたことを述べる。'},
 {'term': 'in the meantime',
  'meaningJa': '暫定運用期間中・本番対応までのつなぎ',
  'usageExample': 'We can keep using the existing verifier in the meantime while the shared service is being built.',
  'descriptionJa': '本格対応までの暫定期間中の運用方針を述べる。'},
 {'term': 'still in the testing phase',
  'meaningJa': 'まだテスト段階にあるため変更や仕様追加が起こり得る状態',
  'usageExample': 'The feature flag logic is still in the testing phase and must not target production branches.',
  'descriptionJa': 'まだテスト段階であり本番適用すべきでないと述べる。'},
 {'term': 'target sandbox branches rather than master',
  'meaningJa': 'masterブランチ（本番）ではなく検証用（サンボックス）ブランチに対して作業・変更を適用する',
  'usageExample': 'Please target sandbox branches rather than master for this initial prototype.',
  'descriptionJa': '本番ではなくサンドボックスブランチを対象にする指示。'},
 {'term': 'revert only these specific endpoints',
  'meaningJa': '全体のリバースではなく問題のあった特定の修正部分・エンドポイントのみを取り消す（リバートする）',
  'usageExample': 'If the schedule slips, revert only these specific endpoints instead of the entire release.',
  'descriptionJa': '全体ではなく問題の特定エンドポイントのみリバートする判断。'},
 {'term': 'avoid breaking the existing flow',
  'meaningJa': '既存の処理フローを壊さないように配慮・設計する',
  'usageExample': 'We can use a redirect order to avoid breaking the existing flow.',
  'descriptionJa': '既存処理フローを壊さないよう配慮する設計方針。'},
 {'term': 'all aligned on',
  'meaningJa': '〜について全体の認識・合意が取れている',
  'usageExample': 'Please confirm we are all aligned on extending the interface before changing the producer schema.',
  'descriptionJa': 'チーム全体の認識・合意が取れているか確認する表現。'},
 {'term': 'reach an agreement',
  'meaningJa': '合意に達する・双方で方針を決定する',
  'usageExample': 'We hope to reach an agreement with the upstream team on the schema transition.',
  'descriptionJa': '関係チーム間で方針の合意に達することを述べる。'},
 {'term': 'concerns about this direction',
  'meaningJa': 'この方向性（方針・設計）に対する懸念・不安',
  'usageExample': 'Does anyone have any concerns about this direction before we update the LLD?',
  'descriptionJa': '提案された設計方向性への懸念を確認する表現。'},
 {'term': 'aligned with what you had in mind',
  'meaningJa': 'あなたが想定していた内容・意図と一致している',
  'usageExample': 'Please confirm whether this boundary is aligned with what you had in mind.',
  'descriptionJa': '相手の想定と設計が一致しているか確認する表現。'},
 {'term': 'summarize the discussion',
  'meaningJa': '議論のポイントや結論を短くまとめる',
  'usageExample': 'To summarize the discussion, the client will support both schemas during migration.',
  'descriptionJa': '設計議論の要点や結論を短くまとめる表現。'},
 {'term': 'centralize the discussion',
  'meaningJa': '議論・検討事項を1つの場所に集約する',
  'usageExample': 'Let us centralize the discussion in this thread so decision log stays visible.',
  'descriptionJa': '意思決定ログを残すため議論を一箇所に集約する表現。'},
 {'term': 'the overall direction looks fine',
  'meaningJa': '全体的な方向性には問題ない',
  'usageExample': 'The overall direction looks fine to me, but the error path needs explicit tests.',
  'descriptionJa': '全体的な設計方向性に問題がないと述べる。'},
 {'term': 'no concerns from my side',
  'meaningJa': '自分の観点からは懸念（不都合）はない',
  'usageExample': 'No concerns from my side; please continue with the interface update.',
  'descriptionJa': '自分の観点からは懸念がないと述べる。'},
 {'term': 'open to the first option',
  'meaningJa': '第一案（選択肢1）を受け入れる準備がある・好意的である',
  'usageExample': 'I am open to the first option if we document its operational limits.',
  'descriptionJa': '第一案を受け入れる意思があることを述べる。'},
 {'term': 'one thing to confirm',
  'meaningJa': '確認しておきたい点が一つある',
  'usageExample': 'One thing to confirm is whether the old endpoint remains in scope.',
  'descriptionJa': '確認しておきたい点が一つあると切り出す表現。'},
 {'term': 'identify the exact agreement you need',
  'meaningJa': '必要な合意（合意事項）の具体的内容を明確にする',
  'usageExample': 'Before contacting the platform team, identify the exact agreement you need.',
  'descriptionJa': '必要な合意事項の具体内容を明確にする表現。'},
 {'term': 'keep the background as extra',
  'meaningJa': '背景情報は補足（おまけ）程度に留めておく・冗長に書かない',
  'usageExample': 'State the contract decision first and keep the background as extra.',
  'descriptionJa': '背景情報は補足程度に留め要点を先に述べる表現。'},
 {'term': 'vendor lock-in',
  'meaningJa': '特定ベンダーの製品・サービスへの依存（ロックイン）',
  'usageExample': 'Evaluate vendor lock-in and exportability in the database decision record.',
  'descriptionJa': '特定ベンダーへの依存リスクを設計判断で評価する表現。'},
 {'term': 'make data consistent across platforms',
  'meaningJa': '複数プラットフォーム間でデータを一致させる',
  'usageExample': 'Server-side preferences make data consistent across platforms and devices.',
  'descriptionJa': '複数プラットフォーム間でデータ整合を保つ設計を述べる。'},
 {'term': 'consistency and reliability',
  'meaningJa': '整合性と信頼性',
  'usageExample': 'Moving preferences to server-side storage improves consistency and reliability.',
  'descriptionJa': 'サーバー側保存による整合性と信頼性の向上を述べる。'},
 {'term': 'future mitigation',
  'meaningJa': '再発防止に向けた今後の軽減策',
  'usageExample': 'The incident review should include future mitigation for missed alerts and reduced traffic.',
  'descriptionJa': '再発防止に向けた今後の軽減策を設計・レビューに含める表現。'},
 {'term': 'find a workaround',
  'meaningJa': '暫定的な回避策（代替案）を見つける',
  'usageExample': 'I will find a workaround while the shared test environment is unavailable.',
  'descriptionJa': '恒久対応までの暫定的な回避策を見つける表現。'},
 {'term': 'just an assumption',
  'meaningJa': 'まだ検証・確定されていない仮定にすぎない',
  'usageExample': 'The expected throughput is just an assumption until we run a representative load test.',
  'descriptionJa': 'まだ検証されていない仮定であることを明示する表現。'}]
