#!/usr/bin/env python3
"""Generate Design / Architecture vocabulary markdown files (106 entries)."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from design_vocabulary_user_data import USER_ENTRIES

ROOT = Path(__file__).resolve().parents[1]
VOCAB_DIR = ROOT / "docs" / "vocabulary"
SCENE = "Design / Architecture"
START_ID = 368

DIFFICULTY_ORDER = {"Beginner": 0, "Intermediate": 1, "Advanced": 2}

METADATA: dict[str, dict] = {'lean towards an option': {'type': 'phrase',
                            'partOfSpeech': 'verb phrase',
                            'pronunciation': '/liːn təˈwɔːdz ən ˈɒpʃn/',
                            'meaning': 'to favor one option',
                            'description': 'State a tentative preference for one design option among several.',
                            'difficulty': 'Intermediate'},
 'an appropriate approach': {'type': 'phrase',
                             'partOfSpeech': 'noun phrase',
                             'pronunciation': '/ən əˈprəʊpriət əˈprəʊtʃ/',
                             'meaning': 'a suitable design approach',
                             'description': 'Ask whether a proposed pattern fits the problem and constraints.',
                             'difficulty': 'Intermediate'},
 'resource-based approach': {'type': 'phrase',
                             'partOfSpeech': 'noun phrase',
                             'pronunciation': '/rɪˈsɔːs beɪst əˈprəʊtʃ/',
                             'meaning': 'design organized around resources',
                             'description': 'Structure APIs or systems around stable domain resources.',
                             'difficulty': 'Intermediate'},
 'schema-less design': {'type': 'phrase',
                        'partOfSpeech': 'noun phrase',
                        'pronunciation': '/ˈskiːmə les dɪˈzaɪn/',
                        'meaning': 'design without a fixed schema',
                        'description': 'Use flexible storage when fields change often and structure varies.',
                        'difficulty': 'Advanced'},
 'generalized design': {'type': 'phrase',
                        'partOfSpeech': 'noun phrase',
                        'pronunciation': '/ˈdʒenrəlaɪzd dɪˈzaɪn/',
                        'meaning': 'broad reusable design',
                        'description': 'Aim for a generic model that supports new types without schema churn.',
                        'difficulty': 'Advanced'},
 'design constraints': {'type': 'phrase',
                        'partOfSpeech': 'noun phrase',
                        'pronunciation': '/dɪˈzaɪn kənˈstreɪnts/',
                        'meaning': 'limits on the design',
                        'description': 'List requirements or limits that shape architecture choices.',
                        'difficulty': 'Intermediate'},
 'challenge your assumptions': {'type': 'phrase',
                                'partOfSpeech': 'verb phrase',
                                'pronunciation': '/ˈtʃælɪndʒ jɔːr əˈsʌmpʃnz/',
                                'meaning': 'to question your assumptions',
                                'description': 'Ask the team to re-examine beliefs about load, scope, or behavior.',
                                'difficulty': 'Advanced'},
 'compare DB alternatives': {'type': 'phrase',
                             'partOfSpeech': 'verb phrase',
                             'pronunciation': '/kəmˈpeə diː biː ɔːlˈtɜːnətɪvz/',
                             'meaning': 'to compare database options',
                             'description': 'Evaluate database choices against queries, cost, and operations.',
                             'difficulty': 'Advanced'},
 'a special case': {'type': 'phrase',
                    'partOfSpeech': 'noun phrase',
                    'pronunciation': '/ə ˈspeʃl keɪs/',
                    'meaning': 'an exceptional case',
                    'description': 'Call out a flow that differs from the normal path or rules.',
                    'difficulty': 'Beginner'},
 'distinguish between design and implementation': {'type': 'phrase',
                                                   'partOfSpeech': 'verb phrase',
                                                   'pronunciation': '/dɪˈstɪŋɡwɪʃ bɪˈtwiːn dɪˈzaɪn ænd '
                                                                    'ˌɪmplɪmenˈteɪʃn/',
                                                   'meaning': 'to separate design from implementation',
                                                   'description': 'Keep ADR decisions stable by separating intent from '
                                                                  'code details.',
                                                   'difficulty': 'Advanced'},
 'bypass downstream guards': {'type': 'phrase',
                              'partOfSpeech': 'verb phrase',
                              'pronunciation': '/ˈbaɪpɑːs ˌdaʊnˈstriːm ɡɑːdz/',
                              'meaning': 'to skip downstream checks',
                              'description': 'Warn that a change must not skip later validation or policy checks.',
                              'difficulty': 'Advanced'},
 'break existing behavior': {'type': 'phrase',
                             'partOfSpeech': 'verb phrase',
                             'pronunciation': '/breɪk ɪɡˈzɪstɪŋ bɪˈheɪvjə/',
                             'meaning': 'to break current behavior',
                             'description': 'Flag that a change may alter behavior existing clients rely on.',
                             'difficulty': 'Intermediate'},
 'based on agreement': {'type': 'phrase',
                        'partOfSpeech': 'prepositional phrase',
                        'pronunciation': '/beɪst ɒn əˈɡriːmənt/',
                        'meaning': 'according to what was agreed',
                        'description': 'State that a plan follows a prior team agreement.',
                        'difficulty': 'Beginner'},
 'long-term fix': {'type': 'phrase',
                   'partOfSpeech': 'noun phrase',
                   'pronunciation': '/lɒŋ tɜːm fɪks/',
                   'meaning': 'a permanent fix',
                   'description': 'Contrast a durable solution with a temporary workaround.',
                   'difficulty': 'Beginner'},
 'fallback JSON': {'type': 'phrase',
                   'partOfSpeech': 'noun phrase',
                   'pronunciation': '/ˈfɔːlbæk ˈdʒeɪsɒn/',
                   'meaning': 'backup JSON payload',
                   'description': 'Return default JSON when remote configuration is unavailable.',
                   'difficulty': 'Intermediate'},
 'default fallbacks': {'type': 'phrase',
                       'partOfSpeech': 'noun phrase',
                       'pronunciation': '/dɪˈfɔːlt ˈfɔːlbæks/',
                       'meaning': 'default backup values',
                       'description': 'Use built-in defaults when upstream data or services fail.',
                       'difficulty': 'Intermediate'},
 'a common pattern': {'type': 'phrase',
                      'partOfSpeech': 'noun phrase',
                      'pronunciation': '/ə ˈkɒmən ˈpætn/',
                      'meaning': 'a shared reusable pattern',
                      'description': 'Suggest a solution other teams could reuse for similar features.',
                      'difficulty': 'Beginner'},
 'extend it easily': {'type': 'phrase',
                      'partOfSpeech': 'verb phrase',
                      'pronunciation': '/ɪkˈstend ɪt ˈiːzɪli/',
                      'meaning': 'to extend it with little effort',
                      'description': 'Keep models generic so new roles or types need minimal change.',
                      'difficulty': 'Intermediate'},
 'future use cases': {'type': 'phrase',
                      'partOfSpeech': 'noun phrase',
                      'pronunciation': '/ˈfjuːtʃə juːs ˈkeɪsɪz/',
                      'meaning': 'anticipated future needs',
                      'description': 'Design keys or APIs to support needs that may come later.',
                      'difficulty': 'Beginner'},
 'proper setup': {'type': 'phrase',
                  'partOfSpeech': 'noun phrase',
                  'pronunciation': '/ˈprɒpə ˈsetʌp/',
                  'meaning': 'correct foundational setup',
                  'description': 'Ensure backups, migrations, and access control are in place.',
                  'difficulty': 'Beginner'},
 'cross-squad dependency': {'type': 'phrase',
                            'partOfSpeech': 'noun phrase',
                            'pronunciation': '/krɒs skwɒd dɪˈpendənsi/',
                            'meaning': 'dependency across squads',
                            'description': 'Note when work spans teams and must appear in delivery plans.',
                            'difficulty': 'Intermediate'},
 'external dependencies': {'type': 'phrase',
                           'partOfSpeech': 'noun phrase',
                           'pronunciation': '/ɪkˈstɜːnl dɪˈpendənsiz/',
                           'meaning': 'dependencies on outside systems',
                           'description': 'Discuss upstream or third-party systems the design relies on.',
                           'difficulty': 'Intermediate'},
 'page responsibilities': {'type': 'phrase',
                           'partOfSpeech': 'noun phrase',
                           'pronunciation': '/peɪdʒ rɪˌspɒnsəˈbɪlətiz/',
                           'meaning': "each page's role and scope",
                           'description': 'Define which UI pages own which features and navigation.',
                           'difficulty': 'Intermediate'},
 'technical ownership': {'type': 'phrase',
                         'partOfSpeech': 'noun phrase',
                         'pronunciation': '/ˈteknɪkl ˈəʊnəʃɪp/',
                         'meaning': 'technical responsibility for a component',
                         'description': 'Clarify which team owns implementation and maintenance.',
                         'difficulty': 'Intermediate'},
 'increased responsibility': {'type': 'phrase',
                              'partOfSpeech': 'noun phrase',
                              'pronunciation': '/ɪnˈkriːst rɪˌspɒnsəˈbɪləti/',
                              'meaning': 'greater operational responsibility',
                              'description': 'Explain that moving a service adds retention or access duties.',
                              'difficulty': 'Intermediate'},
 'cost of cross-squad coordination': {'type': 'phrase',
                                      'partOfSpeech': 'noun phrase',
                                      'pronunciation': '/kɒst əv krɒs skwɒd kəʊˌɔːdɪˈneɪʃn/',
                                      'meaning': 'overhead of coordinating across squads',
                                      'description': 'Weigh coordination effort against benefit for small changes.',
                                      'difficulty': 'Intermediate'},
 'implementation cost': {'type': 'phrase',
                         'partOfSpeech': 'noun phrase',
                         'pronunciation': '/ˌɪmplɪmenˈteɪʃn kɒst/',
                         'meaning': 'effort to build the change',
                         'description': 'Compare engineering effort with expected operational savings.',
                         'difficulty': 'Beginner'},
 'the scopes are yet to be finalized': {'type': 'phrase',
                                        'partOfSpeech': 'clause',
                                        'pronunciation': '/ðə skəʊps ɑː jet tuː biː ˈfaɪnəlaɪzd/',
                                        'meaning': 'scope is not yet decided',
                                        'description': 'Say scope is still open and structures should stay flexible.',
                                        'difficulty': 'Intermediate'},
 'outside the scope': {'type': 'phrase',
                       'partOfSpeech': 'prepositional phrase',
                       'pronunciation': '/ˈaʊtsaɪd ðə skəʊp/',
                       'meaning': 'not included in this effort',
                       'description': 'Exclude work that belongs to another project or phase.',
                       'difficulty': 'Beginner'},
 'in this scope': {'type': 'phrase',
                   'partOfSpeech': 'prepositional phrase',
                   'pronunciation': '/ɪn ðɪs skəʊp/',
                   'meaning': 'within this effort',
                   'description': 'State what will be delivered in the current project boundary.',
                   'difficulty': 'Intermediate'},
 'future scopes': {'type': 'phrase',
                   'partOfSpeech': 'noun phrase',
                   'pronunciation': '/ˈfjuːtʃə skəʊps/',
                   'meaning': 'later planned scope',
                   'description': 'Discuss extensions deferred to future phases or decisions.',
                   'difficulty': 'Intermediate'},
 'resource-based endpoints': {'type': 'phrase',
                              'partOfSpeech': 'noun phrase',
                              'pronunciation': '/rɪˈsɔːs beɪst ˈendpɔɪnts/',
                              'meaning': 'endpoints organized by resource',
                              'description': 'Split APIs into endpoints aligned with domain entities.',
                              'difficulty': 'Intermediate'},
 'API contract': {'type': 'phrase',
                  'partOfSpeech': 'noun phrase',
                  'pronunciation': '/ˌeɪ piː ˈkɒntrækt/',
                  'meaning': 'agreed API interface',
                  'description': 'Define identifiers, shapes, and rules clients and servers share.',
                  'difficulty': 'Intermediate'},
 'separate user identifiers from card identifiers': {'type': 'phrase',
                                                     'partOfSpeech': 'verb phrase',
                                                     'pronunciation': '/ˈseprət ˈjuːzə aɪˈdentɪfaɪəz frɒm kɑːd '
                                                                      'aɪˈdentɪfaɪəz/',
                                                     'meaning': 'to keep user and card IDs distinct',
                                                     'description': 'Avoid ambiguous resources by using the correct '
                                                                    'identifier type.',
                                                     'difficulty': 'Intermediate'},
 'proper entity identifier': {'type': 'phrase',
                              'partOfSpeech': 'noun phrase',
                              'pronunciation': '/ˈprɒpə ˈentɪti aɪˈdentɪfaɪə/',
                              'meaning': 'correct entity identifier',
                              'description': 'Prefer an ID tied to the entity rather than an unrelated one.',
                              'difficulty': 'Intermediate'},
 'common schema': {'type': 'phrase',
                   'partOfSpeech': 'noun phrase',
                   'pronunciation': '/ˈkɒmən ˈskiːmə/',
                   'meaning': 'shared schema definition',
                   'description': 'Define one schema for identifiers used across OpenAPI paths.',
                   'difficulty': 'Intermediate'},
 'schema mismatch': {'type': 'phrase',
                     'partOfSpeech': 'noun phrase',
                     'pronunciation': '/ˈskiːmə ˈmɪsmætʃ/',
                     'meaning': 'inconsistency between schemas',
                     'description': 'Resolve differences between client, server, and generated types.',
                     'difficulty': 'Intermediate'},
 'generated OpenAPI schema': {'type': 'phrase',
                              'partOfSpeech': 'noun phrase',
                              'pronunciation': '/ˈdʒenəreɪtɪd ˌəʊpən ˈeɪpiː ˈskiːmə/',
                              'meaning': 'OpenAPI schema produced from code',
                              'description': 'Ensure generated specs match runtime validation and enums.',
                              'difficulty': 'Intermediate'},
 'schema versioning': {'type': 'phrase',
                       'partOfSpeech': 'noun phrase',
                       'pronunciation': '/ˈskiːmə ˈvɜːʃnɪŋ/',
                       'meaning': 'managing schema changes with versions',
                       'description': 'Version schemas so clients can parse data during migration.',
                       'difficulty': 'Intermediate'},
 'backward compatible': {'type': 'phrase',
                         'partOfSpeech': 'adjective phrase',
                         'pronunciation': '/ˈbækwəd kəmˈpætəbl/',
                         'meaning': 'compatible with earlier versions',
                         'description': 'Add fields or changes without breaking existing clients.',
                         'difficulty': 'Beginner'},
 'breaking changes': {'type': 'phrase',
                      'partOfSpeech': 'noun phrase',
                      'pronunciation': '/ˈbreɪkɪŋ tʃeɪndʒɪz/',
                      'meaning': 'incompatible specification changes',
                      'description': 'Announce API changes that require client updates before rollout.',
                      'difficulty': 'Beginner'},
 'support two schemas': {'type': 'phrase',
                         'partOfSpeech': 'verb phrase',
                         'pronunciation': '/səˈpɔːt tuː ˈskiːməz/',
                         'meaning': 'to handle old and new schemas',
                         'description': 'Let clients read both formats during a producer migration.',
                         'difficulty': 'Intermediate'},
 'make the endpoint flexible': {'type': 'phrase',
                                'partOfSpeech': 'verb phrase',
                                'pronunciation': '/meɪk ði ˈendpɔɪnt ˈfleksəbl/',
                                'meaning': 'to allow endpoint extension',
                                'description': 'Design endpoints so new categories can be added later.',
                                'difficulty': 'Intermediate'},
 'extend the interface': {'type': 'phrase',
                          'partOfSpeech': 'verb phrase',
                          'pronunciation': '/ɪkˈstend ði ˈɪntəfeɪs/',
                          'meaning': 'to expand the interface',
                          'description': 'Add fields or endpoints while preserving default behavior.',
                          'difficulty': 'Intermediate'},
 'improve the interface and LLD': {'type': 'phrase',
                                   'partOfSpeech': 'verb phrase',
                                   'pronunciation': '/ɪmˈpruːv ði ˈɪntəfeɪs ænd ˌel el ˈdiː/',
                                   'meaning': 'to improve interface and low-level design',
                                   'description': 'Clarify defaults and details in the interface and LLD docs.',
                                   'difficulty': 'Intermediate'},
 'default behavior': {'type': 'phrase',
                      'partOfSpeech': 'noun phrase',
                      'pronunciation': '/dɪˈfɔːlt bɪˈheɪvjə/',
                      'meaning': 'behavior when nothing is specified',
                      'description': 'Document what happens when optional fields are omitted.',
                      'difficulty': 'Beginner'},
 'business exceptions': {'type': 'phrase',
                         'partOfSpeech': 'noun phrase',
                         'pronunciation': '/ˈbɪznəs ɪkˈsepʃnz/',
                         'meaning': 'business-rule exception cases',
                         'description': 'Capture account or workflow exceptions in the design doc.',
                         'difficulty': 'Intermediate'},
 'state transitions': {'type': 'phrase',
                       'partOfSpeech': 'noun phrase',
                       'pronunciation': '/steɪt trænˈzɪʃnz/',
                       'meaning': 'changes between states',
                       'description': 'Require tests for valid and invalid status changes.',
                       'difficulty': 'Intermediate'},
 'relational queries': {'type': 'phrase',
                        'partOfSpeech': 'noun phrase',
                        'pronunciation': '/rɪˈleɪʃənl ˈkwɪəriz/',
                        'meaning': 'queries using table relationships',
                        'description': 'Choose a relational DB when joins and relations matter.',
                        'difficulty': 'Intermediate'},
 'persistence layer': {'type': 'phrase',
                       'partOfSpeech': 'noun phrase',
                       'pronunciation': '/pəˈsɪstəns ˈleɪə/',
                       'meaning': 'layer that stores data durably',
                       'description': 'Place durable user data in storage, not transient cache.',
                       'difficulty': 'Intermediate'},
 'stored client-side unregulated': {'type': 'phrase',
                                    'partOfSpeech': 'adjective phrase',
                                    'pronunciation': '/stɔːd ˈklaɪənt saɪd ʌnˈreɡjuleɪtɪd/',
                                    'meaning': 'stored on the client without controls',
                                    'description': 'Flag uncontrolled client storage that breaks retention rules.',
                                    'difficulty': 'Advanced'},
 'cached mapping incomplete': {'type': 'phrase',
                               'partOfSpeech': 'noun phrase',
                               'pronunciation': '/kæʃt ˈmæpɪŋ ˌɪnkəmˈpliːt/',
                               'meaning': 'incomplete cached mapping data',
                               'description': 'Describe stale or partial ID mappings after failed updates.',
                               'difficulty': 'Advanced'},
 'get the latest mapping on every request': {'type': 'phrase',
                                             'partOfSpeech': 'verb phrase',
                                             'pronunciation': '/ɡet ðə ˈleɪtɪst ˈmæpɪŋ ɒn ˈevri rɪˈkwest/',
                                             'meaning': 'to fetch fresh mapping each request',
                                             'description': 'Read authoritative mapping data instead of stale cache.',
                                             'difficulty': 'Advanced'},
 'instead of using the cache': {'type': 'phrase',
                                'partOfSpeech': 'prepositional phrase',
                                'pronunciation': '/ɪnˈsted əv ˈjuːzɪŋ ðə kæʃ/',
                                'meaning': 'rather than using the cache',
                                'description': 'Call the source service directly when cache risk is too high.',
                                'difficulty': 'Intermediate'},
 'cache the response': {'type': 'phrase',
                        'partOfSpeech': 'verb phrase',
                        'pronunciation': '/kæʃ ðə rɪˈspɒns/',
                        'meaning': 'to store the response in cache',
                        'description': 'Cache briefly to cut repeated upstream calls.',
                        'difficulty': 'Intermediate'},
 'objects within objects': {'type': 'phrase',
                            'partOfSpeech': 'noun phrase',
                            'pronunciation': '/ˈɒbdʒɪkts wɪˈðɪn ˈɒbdʒɪkts/',
                            'meaning': 'nested objects inside objects',
                            'description': 'Model nested preferences without a disruptive schema change.',
                            'difficulty': 'Advanced'},
 'mock external dependencies': {'type': 'phrase',
                                'partOfSpeech': 'verb phrase',
                                'pronunciation': '/mɒk ɪkˈstɜːnl dɪˈpendənsiz/',
                                'meaning': 'to replace external deps with mocks',
                                'description': 'Isolate the service under test in integration tests.',
                                'difficulty': 'Intermediate'},
 'avoid unnecessary loads': {'type': 'phrase',
                             'partOfSpeech': 'verb phrase',
                             'pronunciation': '/əˈvɔɪd ʌnˈnesəsri ləʊdz/',
                             'meaning': 'to avoid needless load',
                             'description': 'Keep UI components from overcalling backend services.',
                             'difficulty': 'Intermediate'},
 'reduce expensive API calls': {'type': 'phrase',
                                'partOfSpeech': 'verb phrase',
                                'pronunciation': '/rɪˈdjuːs ɪkˈspensɪv ˌeɪ piː ˈkɔːlz/',
                                'meaning': 'to cut costly API calls',
                                'description': 'Use short-lived cache to limit heavy upstream traffic.',
                                'difficulty': 'Intermediate'},
 'no heavy processing': {'type': 'phrase',
                         'partOfSpeech': 'noun phrase',
                         'pronunciation': '/nəʊ ˈhevi ˈprəʊsesɪŋ/',
                         'meaning': 'no intensive backend processing',
                         'description': 'Keep the BFF layer thin with validation only.',
                         'difficulty': 'Advanced'},
 'API-level performance risk': {'type': 'phrase',
                                'partOfSpeech': 'noun phrase',
                                'pronunciation': '/ˌeɪ piː ˈlevəl pəˈfɔːməns rɪsk/',
                                'meaning': 'performance risk at the API layer',
                                'description': 'Assess latency or I/O risk for a specific API handler.',
                                'difficulty': 'Advanced'},
 'higher latency': {'type': 'phrase',
                    'partOfSpeech': 'noun phrase',
                    'pronunciation': '/ˈhaɪə ˈleɪtənsi/',
                    'meaning': 'increased response delay',
                    'description': 'Ensure monitoring shows any added latency clearly.',
                    'difficulty': 'Beginner'},
 'reflect real latency': {'type': 'phrase',
                          'partOfSpeech': 'verb phrase',
                          'pronunciation': '/rɪˈflekt rɪəl ˈleɪtənsi/',
                          'meaning': 'to show true latency in metrics',
                          'description': 'Configure tracing so production latency is measured accurately.',
                          'difficulty': 'Intermediate'},
 'performance improvements': {'type': 'phrase',
                              'partOfSpeech': 'noun phrase',
                              'pronunciation': '/pəˈfɔːməns ɪmˈpruːvmənts/',
                              'meaning': 'gains in speed or efficiency',
                              'description': 'Highlight payload or path changes that improve response time.',
                              'difficulty': 'Beginner'},
 'ensure compatibility with the latest frameworks': {'type': 'phrase',
                                                     'partOfSpeech': 'verb phrase',
                                                     'pronunciation': '/ɪnˈʃʊə kəmˌpætəˈbɪləti wɪð ðə ˈleɪtɪst '
                                                                      'ˈfreɪmwɜːks/',
                                                     'meaning': 'to stay compatible with new frameworks',
                                                     'description': 'Verify build scripts work with current framework '
                                                                    'versions.',
                                                     'difficulty': 'Intermediate'},
 'reduce the risk of': {'type': 'phrase',
                        'partOfSpeech': 'verb phrase',
                        'pronunciation': '/rɪˈdjuːs ðə rɪsk əv/',
                        'meaning': 'to lower the risk of',
                        'description': 'Use sanitization or guards to limit exposure risk.',
                        'difficulty': 'Intermediate'},
 'diagnostic data being exposed': {'type': 'phrase',
                                   'partOfSpeech': 'noun phrase',
                                   'pronunciation': '/ˌdaɪəɡˈnɒstɪk ˈdeɪtə ˈbiːɪŋ ɪkˈspəʊzd/',
                                   'meaning': 'diagnostic data leaking out',
                                   'description': 'Prevent logs or errors from leaking debug data to clients.',
                                   'difficulty': 'Advanced'},
 'edge cases we may have missed': {'type': 'phrase',
                                   'partOfSpeech': 'noun phrase',
                                   'pronunciation': '/edʒ keɪsɪz wiː meɪ hæv mɪst/',
                                   'meaning': 'edge cases we might have overlooked',
                                   'description': 'Ask reviewers to flag rare cases before rollout.',
                                   'difficulty': 'Intermediate'},
 'regression risk': {'type': 'phrase',
                     'partOfSpeech': 'noun phrase',
                     'pronunciation': '/rɪˈɡreʃn rɪsk/',
                     'meaning': 'risk of breaking existing behavior',
                     'description': 'Assess whether legacy clients may break after a change.',
                     'difficulty': 'Beginner'},
 'potential side effects': {'type': 'phrase',
                            'partOfSpeech': 'noun phrase',
                            'pronunciation': '/pəˈtenʃl saɪd ɪˈfekts/',
                            'meaning': 'possible unintended effects',
                            'description': 'Review impact on legacy apps before merging a design change.',
                            'difficulty': 'Beginner'},
 'prevent PII leaks': {'type': 'phrase',
                       'partOfSpeech': 'verb phrase',
                       'pronunciation': '/prɪˈvent piː aɪ aɪ liːks/',
                       'meaning': 'to stop personal data leaks',
                       'description': 'Mask structured error fields so logs do not expose PII.',
                       'difficulty': 'Intermediate'},
 'unmasked PII': {'type': 'phrase',
                  'partOfSpeech': 'noun phrase',
                  'pronunciation': '/ʌnˈmɑːskt piː aɪ aɪ/',
                  'meaning': 'personal data without masking',
                  'description': 'Block error responses with raw PII from reaching consoles.',
                  'difficulty': 'Advanced'},
 'publicly exposed': {'type': 'phrase',
                      'partOfSpeech': 'adjective phrase',
                      'pronunciation': '/ˈpʌblɪkli ɪkˈspəʊzd/',
                      'meaning': 'reachable from the public internet',
                      'description': 'Ensure internal endpoints are not exposed via flags or routes.',
                      'difficulty': 'Intermediate'},
 'attack surface management': {'type': 'phrase',
                               'partOfSpeech': 'noun phrase',
                               'pronunciation': '/əˈtæk ˈsɜːfɪs ˈmænɪdʒmənt/',
                               'meaning': 'managing exposed attack vectors',
                               'description': 'Track and reduce publicly reachable internal endpoints.',
                               'difficulty': 'Advanced'},
 'access control': {'type': 'phrase',
                    'partOfSpeech': 'noun phrase',
                    'pronunciation': '/ˈækses kənˈtrəʊl/',
                    'meaning': 'control of who can access what',
                    'description': 'Gate routes by audience, auth state, or role.',
                    'difficulty': 'Beginner'},
 'assume true in the case of failure': {'type': 'phrase',
                                        'partOfSpeech': 'verb phrase',
                                        'pronunciation': '/əˈsjuːm truː ɪn ðə keɪs əv ˈfeɪljə/',
                                        'meaning': 'to treat failure as allowed',
                                        'description': 'Reject fail-open designs for security-sensitive flags.',
                                        'difficulty': 'Advanced'},
 'rollback mechanism': {'type': 'phrase',
                        'partOfSpeech': 'noun phrase',
                        'pronunciation': '/ˈrəʊlbæk ˈmekənɪzm/',
                        'meaning': 'way to revert a release',
                        'description': 'Test how to revert traffic or config before going live.',
                        'difficulty': 'Intermediate'},
 'risk of rollback': {'type': 'phrase',
                      'partOfSpeech': 'noun phrase',
                      'pronunciation': '/rɪsk əv ˈrəʊlbæk/',
                      'meaning': 'risk when rolling back',
                      'description': 'Warn when rollback may fail due to schema or data mismatch.',
                      'difficulty': 'Intermediate'},
 'rollback immediately': {'type': 'phrase',
                          'partOfSpeech': 'verb phrase',
                          'pronunciation': '/ˈrəʊlbæk ɪˈmiːdiətli/',
                          'meaning': 'to revert right away',
                          'description': 'Revert to the old version when error rates cross a threshold.',
                          'difficulty': 'Intermediate'},
 'phase out': {'type': 'phrase',
               'partOfSpeech': 'verb phrase',
               'pronunciation': '/feɪz aʊt/',
               'meaning': 'to retire gradually',
               'description': 'Deprecate legacy tokens after clients adopt the new model.',
               'difficulty': 'Beginner'},
 'switch to the new endpoint': {'type': 'phrase',
                                'partOfSpeech': 'verb phrase',
                                'pronunciation': '/swɪtʃ tuː ðə njuː ˈendpɔɪnt/',
                                'meaning': 'to move to the new endpoint',
                                'description': 'Move clients after staging compatibility tests pass.',
                                'difficulty': 'Intermediate'},
 'organize the parts that need replacing': {'type': 'phrase',
                                            'partOfSpeech': 'verb phrase',
                                            'pronunciation': '/ˈɔːɡənaɪz ðə pɑːts ðæt niːd rɪˈpleɪsɪŋ/',
                                            'meaning': 'to list components to replace',
                                            'description': 'Inventory modules to swap and assign owners before '
                                                           'migration.',
                                            'difficulty': 'Advanced'},
 'migrated without much hassle': {'type': 'phrase',
                                  'partOfSpeech': 'clause',
                                  'pronunciation': '/maɪˈɡreɪtɪd wɪˈðaʊt mʌtʃ ˈhæsl/',
                                  'meaning': 'migrated smoothly with little trouble',
                                  'description': 'Say migration was easy because the model had no joins.',
                                  'difficulty': 'Advanced'},
 'in the meantime': {'type': 'phrase',
                     'partOfSpeech': 'adverb phrase',
                     'pronunciation': '/ɪn ðə miːnˈtaɪm/',
                     'meaning': 'meanwhile',
                     'description': 'Keep interim behavior until the shared service is ready.',
                     'difficulty': 'Intermediate'},
 'still in the testing phase': {'type': 'phrase',
                                'partOfSpeech': 'clause',
                                'pronunciation': '/stɪl ɪn ðə ˈtestɪŋ feɪz/',
                                'meaning': 'still being tested',
                                'description': 'Say logic is experimental and must not hit production yet.',
                                'difficulty': 'Advanced'},
 'target sandbox branches rather than master': {'type': 'phrase',
                                                'partOfSpeech': 'verb phrase',
                                                'pronunciation': '/ˈtɑːɡɪt ˈsændbɒks ˈbrɑːntʃɪz ˈrɑːðə ðæn ˈmɑːstə/',
                                                'meaning': 'to apply changes to sandbox branches only',
                                                'description': 'Direct prototypes to sandbox branches, not production.',
                                                'difficulty': 'Advanced'},
 'revert only these specific endpoints': {'type': 'phrase',
                                          'partOfSpeech': 'verb phrase',
                                          'pronunciation': '/rɪˈvɜːt ˈəʊnli ðiːz spəˈsɪfɪk ˈendpɔɪnts/',
                                          'meaning': 'to revert only selected endpoints',
                                          'description': 'Roll back targeted endpoints instead of the full release.',
                                          'difficulty': 'Advanced'},
 'avoid breaking the existing flow': {'type': 'phrase',
                                      'partOfSpeech': 'verb phrase',
                                      'pronunciation': '/əˈvɔɪd ˈbreɪkɪŋ ði ɪɡˈzɪstɪŋ fləʊ/',
                                      'meaning': 'to preserve the current flow',
                                      'description': 'Use redirects or compat layers to keep current user paths.',
                                      'difficulty': 'Beginner'},
 'all aligned on': {'type': 'phrase',
                    'partOfSpeech': 'clause',
                    'pronunciation': '/ɔːl əˈlaɪnd ɒn/',
                    'meaning': 'everyone agrees on',
                    'description': 'Confirm shared understanding before changing producer schemas.',
                    'difficulty': 'Beginner'},
 'reach an agreement': {'type': 'phrase',
                        'partOfSpeech': 'verb phrase',
                        'pronunciation': '/riːtʃ ən əˈɡriːmənt/',
                        'meaning': 'to come to an agreement',
                        'description': 'Settle schema or interface decisions with upstream teams.',
                        'difficulty': 'Beginner'},
 'concerns about this direction': {'type': 'phrase',
                                   'partOfSpeech': 'noun phrase',
                                   'pronunciation': '/kənˈsɜːnz əˈbaʊt ðɪs daɪˈrekʃn/',
                                   'meaning': 'worries about this approach',
                                   'description': 'Invite concerns before updating the low-level design.',
                                   'difficulty': 'Intermediate'},
 'aligned with what you had in mind': {'type': 'phrase',
                                       'partOfSpeech': 'clause',
                                       'pronunciation': '/əˈlaɪnd wɪð wɒt juː hæd ɪn maɪnd/',
                                       'meaning': 'matching your intent',
                                       'description': "Check whether a boundary matches the stakeholder's intent.",
                                       'difficulty': 'Advanced'},
 'summarize the discussion': {'type': 'phrase',
                              'partOfSpeech': 'verb phrase',
                              'pronunciation': '/ˈsʌməraɪz ðə dɪˈskʌʃn/',
                              'meaning': 'to recap the discussion',
                              'description': 'Restate decisions and next steps at the end of a review.',
                              'difficulty': 'Beginner'},
 'centralize the discussion': {'type': 'phrase',
                               'partOfSpeech': 'verb phrase',
                               'pronunciation': '/ˈsentrəlaɪz ðə dɪˈskʌʃn/',
                               'meaning': 'to keep discussion in one place',
                               'description': 'Keep design threads in one channel for a visible decision log.',
                               'difficulty': 'Intermediate'},
 'the overall direction looks fine': {'type': 'phrase',
                                      'partOfSpeech': 'clause',
                                      'pronunciation': '/ði ˈəʊvərɔːl daɪˈrekʃn lʊks faɪn/',
                                      'meaning': 'the general approach seems acceptable',
                                      'description': 'Approve the broad direction while noting follow-up items.',
                                      'difficulty': 'Beginner'},
 'no concerns from my side': {'type': 'phrase',
                              'partOfSpeech': 'clause',
                              'pronunciation': '/nəʊ kənˈsɜːnz frɒm maɪ saɪd/',
                              'meaning': 'I have no concerns',
                              'description': 'Signal approval and ask the team to proceed.',
                              'difficulty': 'Beginner'},
 'open to the first option': {'type': 'phrase',
                              'partOfSpeech': 'clause',
                              'pronunciation': '/ˈəʊpən tuː ðə fɜːst ˈɒpʃn/',
                              'meaning': 'willing to accept option one',
                              'description': 'Accept the first proposal if limits are documented.',
                              'difficulty': 'Beginner'},
 'one thing to confirm': {'type': 'phrase',
                          'partOfSpeech': 'clause',
                          'pronunciation': '/wʌn θɪŋ tuː kənˈfɜːm/',
                          'meaning': 'one point to verify',
                          'description': 'Raise a single clarification before moving forward.',
                          'difficulty': 'Beginner'},
 'identify the exact agreement you need': {'type': 'phrase',
                                           'partOfSpeech': 'verb phrase',
                                           'pronunciation': '/aɪˈdentɪfaɪ ði ɪɡˈzækt əˈɡriːmənt juː niːd/',
                                           'meaning': 'to clarify required agreement',
                                           'description': 'Define the specific decision needed before contacting '
                                                          'another team.',
                                           'difficulty': 'Advanced'},
 'keep the background as extra': {'type': 'phrase',
                                  'partOfSpeech': 'verb phrase',
                                  'pronunciation': '/kiːp ðə ˈbækɡraʊnd æz ˈekstrə/',
                                  'meaning': 'to treat background as supplementary',
                                  'description': 'Lead with the decision; keep context brief and secondary.',
                                  'difficulty': 'Advanced'},
 'vendor lock-in': {'type': 'phrase',
                    'partOfSpeech': 'noun phrase',
                    'pronunciation': '/ˈvendə lɒk ɪn/',
                    'meaning': 'dependency on one vendor',
                    'description': 'Evaluate portability when choosing platforms or databases.',
                    'difficulty': 'Advanced'},
 'make data consistent across platforms': {'type': 'phrase',
                                           'partOfSpeech': 'verb phrase',
                                           'pronunciation': '/meɪk ˈdeɪtə kənˈsɪstənt əˈkrɒs ˈplætfɔːmz/',
                                           'meaning': 'to keep data consistent everywhere',
                                           'description': 'Use server-side storage so all clients see the same data.',
                                           'difficulty': 'Intermediate'},
 'consistency and reliability': {'type': 'phrase',
                                 'partOfSpeech': 'noun phrase',
                                 'pronunciation': '/kənˈsɪstənsi ænd rɪˌlaɪəˈbɪləti/',
                                 'meaning': 'data consistency and reliability',
                                 'description': 'Argue for server-side prefs to improve trust in shared state.',
                                 'difficulty': 'Intermediate'},
 'future mitigation': {'type': 'phrase',
                       'partOfSpeech': 'noun phrase',
                       'pronunciation': '/ˈfjuːtʃə ˌmɪtɪˈɡeɪʃn/',
                       'meaning': 'future steps to reduce recurrence',
                       'description': 'Record follow-up actions after an incident review.',
                       'difficulty': 'Intermediate'},
 'find a workaround': {'type': 'phrase',
                       'partOfSpeech': 'verb phrase',
                       'pronunciation': '/faɪnd ə ˈwɜːkəraʊnd/',
                       'meaning': 'to find a temporary fix',
                       'description': 'Use an interim solution while a dependency is unavailable.',
                       'difficulty': 'Beginner'},
 'just an assumption': {'type': 'phrase',
                        'partOfSpeech': 'noun phrase',
                        'pronunciation': '/dʒʌst ən əˈsʌmpʃn/',
                        'meaning': 'only an unverified assumption',
                        'description': 'Mark throughput or load figures as unvalidated until tested.',
                        'difficulty': 'Beginner'}}

USAGE_EXAMPLE_JA: dict[str, str] = {'lean towards an option': '将来のレポートにJOINが必要なため、リレーショナル案に傾いている。',
 'an appropriate approach': '監査証跡にイベントソーシングが妥当な進め方かレビューしてほしい。',
 'resource-based approach': '各エンドポイントが安定したドメインエンティティを表すよう、リソース単位で構成している。',
 'schema-less design': 'ネストフィールドが頻繁に変わる設定には、固定スキーマを持たない設計が向く。',
 'generalized design': 'ストレージモデルを変えずに新しい設定タイプを追加できる汎用設計が目標だ。',
 'design constraints': 'これらの設計制約により、安定した識別子とRESTfulエンドポイントが必要だ。',
 'challenge your assumptions': 'アーキテクチャチームはピークトラフィックに関する前提の再検証を求めている。',
 'compare DB alternatives': 'ADRでDB代替案をクエリパターンと運用コストと比較すべきだ。',
 'a special case': '通常の認証コンテキストが使えないため、アカウント復旧は特別なケースだ。',
 'distinguish between design and implementation': 'ADRは設計と実装を分け、決定が安定するようにすべきだ。',
 'bypass downstream guards': 'この変更は資格ルールを強制する後続ガードを迂回してはならない。',
 'break existing behavior': 'ミドルウェア順序の変更は、既存ユーザーの挙動を壊す可能性がある。',
 'based on agreement': '合意に基づき、性能テストは上流サービスをモック化して行う。',
 'long-term fix': 'スキーマバージョニングが恒久対応で、パーサーのフォールバックは暫定だ。',
 'fallback JSON': 'リモート設定が利用不可のとき、フォールバックJSONを返す。',
 'default fallbacks': '障害時、クライアントがデフォルトの代替値として機能できる。',
 'a common pattern': 'この所有権移譲は、小規模なクロススクワッド機能の共通パターンになり得る。',
 'extend it easily': '新しいロール向けに容易に拡張できるよう、ポリシーモデルは汎用的に保つ。',
 'future use cases': '破壊的移行なしで将来の利用ケースに対応できるよう、ストレージキーを設計する。',
 'proper setup': 'バックアップ、マイグレーション、アクセス制御の適正な構成が必要だ。',
 'cross-squad dependency': 'このエンドポイントはクロススクワッド依存を生み、計画に反映すべきだ。',
 'external dependencies': '他アプリへの影響を避けるため、ゲートウェイは外部依存を渡さない。',
 'page responsibilities': 'アーキテクチャ文書で各ページの責務とナビゲーション境界を定義すべきだ。',
 'technical ownership': '技術的責任はプラットフォームチーム、優先順位はスクワッドリードが担う。',
 'increased responsibility': '境界内にサービスを移すと、保持とアクセス制御の責務が増える。',
 'cost of cross-squad coordination': 'この小変更では、スクワッド間調整コストが実装コストを上回る可能性がある。',
 'implementation cost': '実装コストと運用削減効果を比較すべきだ。',
 'the scopes are yet to be finalized': 'スコープは未確定のため、キー構造は柔軟に保つべきだ。',
 'outside the scope': 'レガシーユーザーのデータ移行は、今回の移行スコープ外だ。',
 'in this scope': '今回のスコープでは設定APIを更新する。',
 'future scopes': '将来スコープへの懸念があるため、識別子の決定には追加議論が必要だ。',
 'resource-based endpoints': 'APIをユーザーとカード向けのリソース単位エンドポイントに分割した。',
 'API contract': 'API契約はユーザー識別子とカード識別子を区別しなければならない。',
 'separate user identifiers from card identifiers': 'あいまいなリソースを避けるため、ユーザーIDとカードIDを区別すべきだ。',
 'proper entity identifier': '無関係なカードIDより、適切なエンティティ識別子を優先する。',
 'common schema': '全OpenAPIパスで使う識別子の共通スキーマを定義する。',
 'schema mismatch': 'クライアントとサーバーは列挙値をマッピングし、スキーマ不一致を解消する。',
 'generated OpenAPI schema': 'ランタイム検証と生成OpenAPIスキーマは同じ列挙値を公開する必要がある。',
 'schema versioning': '移行期間中も新クライアントが設定を解析できるよう、スキーマバージョニングを検討する。',
 'backward compatible': '新フィールドは以前のレスポンス形式と後方互換であるべきだ。',
 'breaking changes': 'BFF側の破壊的変更は、非エンジニアチームのテスト前に告知すべきだ。',
 'support two schemas': 'プロデューサーが形式を変える前に、クライアントは新旧2スキーマを両立させる。',
 'make the endpoint flexible': '新しい設定カテゴリを追加できるよう、エンドポイントに柔軟性を持たせる。',
 'extend the interface': 'デフォルトを維持しつつ、明示的なオーディエンスフィールドでインターフェースを拡張できる。',
 'improve the interface and LLD': '既定動作を明確にするため、インターフェースとLLDを改善すべきだ。',
 'default behavior': 'オーディエンスフィールド省略時の既定動作を文書化する。',
 'business exceptions': '設計文書には停止アカウントの業務例外を記載すべきだ。',
 'state transitions': 'テストはpendingからactive、rejectedへの状態遷移をカバーする必要がある。',
 'relational queries': '将来の利用ケースでリレーショナルクエリが必要なら、リレーショナルDBを選ぶ。',
 'persistence layer': 'ユーザー設定は一時キャッシュではなく、永続化層に置くべきだ。',
 'stored client-side unregulated': 'クライアント側に無制限保存されると、保持ルールが適用されない。',
 'cached mapping incomplete': '更新失敗により、アカウント作成後にキャッシュマッピングが不完全になる。',
 'get the latest mapping on every request': '重要フローでは、古いキャッシュではなくリクエストごとに最新マッピングを取得する。',
 'instead of using the cache': '読み取りパスはキャッシュではなく、正規サービスを呼び出す。',
 'cache the response': '上流呼び出しを減らすため、レスポンスを短時間キャッシュできる。',
 'objects within objects': '破壊的スキーマ変更なしで、ネスト設定をオブジェクト内オブジェクトとして保存する。',
 'mock external dependencies': '統合テストでは外部依存をモック化し、対象サービスを分離する。',
 'avoid unnecessary loads': 'プロフィールヘッダーはプロフィールサービスへの不要な負荷を避けるべきだ。',
 'reduce expensive API calls': '短命キャッシュでページ遷移ごとの高コストAPI呼び出しを減らせる。',
 'no heavy processing': 'BFF層は検証のみとし、バックエンドで重い処理は行わない。',
 'API-level performance risk': 'ハンドラが追加I/Oを行わないため、API単位の性能リスクは比較的低い。',
 'higher latency': 'レイテンシー増加は監視ヒストグラムで可視化され続けなければならない。',
 'reflect real latency': '本番の実レイテンシーを反映するよう、トレースサンプリングを設定する。',
 'performance improvements': '小さなペイロードは大規模設定ファイルで有意な性能改善をもたらす。',
 'ensure compatibility with the latest frameworks': 'ビルドスクリプトは最新フレームワークとの互換性を確保する必要がある。',
 'reduce the risk of': 'ログのサニタイズは診断データ露出のリスクを低減する。',
 'diagnostic data being exposed': 'ブラウザコンソールへの診断データ露出を防ぐため、エラーログは慎重に扱う。',
 'edge cases we may have missed': 'ロールアウト前に、見落としている例外ケースがあれば指摘してほしい。',
 'regression risk': 'レガシー識別子を使うクライアントのデグレリスクはどの程度か。',
 'potential side effects': 'マージ前に、レガシーアプリへの潜在的副作用を評価すべきだ。',
 'prevent PII leaks': '構造化エラーフィールドをマスクし、ログ経由のPII漏洩を防ぐ。',
 'unmasked PII': 'エラーレスポンスにマスクされていないPIIが含まれる可能性があり、コンソール出力禁止。',
 'publicly exposed': '内部エンドポイントをフィーチャーフラグマップ経由で公開してはならない。',
 'attack surface management': '効果的なアタックサーフェス管理は、公開到達可能な内部EPを検出すべきだ。',
 'access control': 'ゲートウェイはオーディエンスと認証状態に基づくアクセス制御を提供する。',
 'assume true in the case of failure': 'セキュリティ重要フラグで失敗時に真と仮定してはならない。',
 'rollback mechanism': '本番トラフィックを新スタックへ向ける前に、ロールバック手順をテストすべきだ。',
 'risk of rollback': '旧スキーマが新規レコードを読めない場合、ロールバックリスクは高い。',
 'rollback immediately': 'エラー率が閾値を超えたら、即座にロールバックする必要がある。',
 'phase out': '全クライアントが新IDモデルを採用後、レガシートークンを段階的に廃止する。',
 'switch to the new endpoint': 'ステージング互換テスト通過後、クライアントは新エンドポイントへ切り替え可能。',
 'organize the parts that need replacing': '移行前に、置き換えが必要な部品を整理し、担当者を特定する。',
 'migrated without much hassle': 'モデルにJOINがないため、レコードは大きな手間なく移行できる。',
 'in the meantime': '共有サービス構築中は、既存の検証器を暫定利用できる。',
 'still in the testing phase': 'フィーチャーフラグロジックはテスト段階のため、本番ブランチを対象にしてはならない。',
 'target sandbox branches rather than master': '初期プロトタイプはmasterではなくサンドボックスブランチを対象にしてほしい。',
 'revert only these specific endpoints': 'スケジュールが遅れたら、リリース全体ではなく問題EPのみリバートする。',
 'avoid breaking the existing flow': 'リダイレクト順序で既存フローを壊さないようにできる。',
 'all aligned on': 'プロデューサースキーマ変更前に、インターフェース拡張で全体合意があるか確認してほしい。',
 'reach an agreement': 'スキーマ移行について上流チームと合意に達することを望む。',
 'concerns about this direction': 'LLD更新前に、この方向性への懸念はあるか。',
 'aligned with what you had in mind': 'この境界が想定どおりか確認してほしい。',
 'summarize the discussion': '議論をまとめると、移行期間中クライアントは両スキーマをサポートする。',
 'centralize the discussion': '決定ログを見える化するため、このスレッドに議論を集約しよう。',
 'the overall direction looks fine': '全体的な方向性は問題ないが、エラーパスには明示的テストが必要だ。',
 'no concerns from my side': '私の側から懸念はない。インターフェース更新を続けてほしい。',
 'open to the first option': '運用上の限界を文書化すれば、第一案を受け入れられる。',
 'one thing to confirm': '確認点は、旧エンドポイントがスコープ内に残るかどうかだ。',
 'identify the exact agreement you need': 'プラットフォームチームに連絡する前に、必要な合意内容を明確にする。',
 'keep the background as extra': '契約決定を先に述べ、背景情報は補足程度に留める。',
 'vendor lock-in': 'DB決定記録でベンダーロックインとエクスポート性を評価する。',
 'make data consistent across platforms': 'サーバー側設定により、プラットフォームとデバイス間でデータを一致させる。',
 'consistency and reliability': '設定をサーバー側保存に移すと、整合性と信頼性が向上する。',
 'future mitigation': 'インシデントレビューには、見逃しアラートと流量低下への将来対策を含める。',
 'find a workaround': '共有テスト環境が使えない間、暫定回避策を見つける。',
 'just an assumption': '代表負荷テストまで、想定スループットは未検証の仮定にすぎない。'}
def slug(term: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", term.lower()).strip("-")


def word_count(text: str) -> int:
    return len(text.split())


def load_existing_terms() -> set[str]:
    terms: set[str] = set()
    if not VOCAB_DIR.exists():
        return terms
    term_re = re.compile(r'^term:\s*"(.*)"\s*$')
    for path in VOCAB_DIR.glob("*.md"):
        for line in path.read_text(encoding="utf-8").splitlines():
            match = term_re.match(line)
            if match:
                terms.add(match.group(1))
                break
    return terms


def merge_entries() -> tuple[list[dict], list[str]]:
    existing = load_existing_terms()
    skipped: list[str] = []
    merged: list[dict] = []
    for user_index, user in enumerate(USER_ENTRIES):
        term = user["term"]
        if term in existing:
            skipped.append(term)
            continue
        if term not in METADATA:
            raise KeyError(f"Missing METADATA for term: {term}")
        if term not in USAGE_EXAMPLE_JA:
            raise KeyError(f"Missing USAGE_EXAMPLE_JA for term: {term}")
        entry = {**METADATA[term], **user}
        entry["usageExampleJa"] = USAGE_EXAMPLE_JA[term]
        entry["scene"] = SCENE
        entry["_user_index"] = user_index
        merged.append(entry)
    merged.sort(
        key=lambda e: (
            DIFFICULTY_ORDER[e["difficulty"]],
            e["_user_index"],
        )
    )
    for entry in merged:
        del entry["_user_index"]
    return merged, skipped


def validate(entry: dict, entry_id: str) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    term = entry["term"]
    if len(entry["description"]) > 120:
        errors.append(f"{entry_id} {term}: description > 120 chars ({len(entry['description'])})")
    if len(entry["descriptionJa"]) > 80:
        warnings.append(f"{entry_id} {term}: descriptionJa > 80 chars ({len(entry['descriptionJa'])})")
    if word_count(entry["usageExample"]) > 25:
        errors.append(
            f"{entry_id} {term}: usageExample > 25 words ({word_count(entry['usageExample'])})"
        )
    if len(entry["usageExampleJa"]) > 80:
        errors.append(
            f"{entry_id} {term}: usageExampleJa > 80 chars ({len(entry['usageExampleJa'])})"
        )
    return errors, warnings


def render(entry: dict, entry_id: str) -> str:
    return (
        "---\n"
        f'id: "{entry_id}"\n'
        f'term: "{entry["term"]}"\n'
        f'type: "{entry["type"]}"\n'
        f'partOfSpeech: "{entry["partOfSpeech"]}"\n'
        f'pronunciation: "{entry["pronunciation"]}"\n'
        f'description: "{entry["description"]}"\n'
        f'descriptionJa: "{entry["descriptionJa"]}"\n'
        f'meaning: "{entry["meaning"]}"\n'
        f'meaningJa: "{entry["meaningJa"]}"\n'
        f'usageExample: "{entry["usageExample"]}"\n'
        f'usageExampleJa: "{entry["usageExampleJa"]}"\n'
        f'difficulty: "{entry["difficulty"]}"\n'
        f'scene: "{SCENE}"\n'
        "---\n"
    )


def main() -> int:
    entries, skipped = merge_entries()
    VOCAB_DIR.mkdir(parents=True, exist_ok=True)
    seen: set[str] = set()
    all_errors: list[str] = []
    all_warnings: list[str] = []
    counts = {"Beginner": 0, "Intermediate": 0, "Advanced": 0}

    if skipped:
        print(f"Skipped duplicates ({len(skipped)}):")
        for term in skipped:
            print(f"  - {term}")

    for idx, entry in enumerate(entries, start=START_ID):
        term = entry["term"]
        if term in seen:
            all_errors.append(f"Duplicate term: {term}")
            continue
        seen.add(term)
        counts[entry["difficulty"]] += 1
        entry_id = f"{idx:04d}"
        errs, warns = validate(entry, entry_id)
        all_errors.extend(errs)
        all_warnings.extend(warns)
        path = VOCAB_DIR / f"{entry_id}_{slug(term)}.md"
        path.write_text(render(entry, entry_id), encoding="utf-8")

    print(f"Wrote {len(entries)} vocabulary files to {VOCAB_DIR}")
    print(
        "Difficulty counts: "
        f"Beginner={counts['Beginner']}, "
        f"Intermediate={counts['Intermediate']}, "
        f"Advanced={counts['Advanced']}"
    )
    if all_warnings:
        print(f"Warnings ({len(all_warnings)}):")
        for warn in all_warnings:
            print(f"  - {warn}")
    if all_errors:
        print(f"Validation failures ({len(all_errors)}):")
        for err in all_errors:
            print(f"  - {err}")
        return 1
    print("All validations passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
