"""User-provided Implementation / Review vocabulary fields (114 entries)."""

USER_ENTRIES: list[dict] = [
    {
        "term": 'introduce a new API',
        "meaningJa": '新しいAPIを導入する',
        "usageExample": 'This PR introduces a new API for retrieving the user notification setting;',
        "descriptionJa": 'ユーザー通知設定を取得する新しいAPIを導入する時に使う。',
    },
    {
        "term": 'enable seamless transitions',
        "meaningJa": 'シームレスな遷移を可能にする',
        "usageExample": 'The shared context enables seamless transitions between the two applications.',
        "descriptionJa": '共有コンテキストにより、2つのアプリケーション間のスムーズな遷移を可能にする時に使う。',
    },
    {
        "term": 'leverage A for persistence',
        "meaningJa": '永続化のためにAを活用する',
        "usageExample": 'The implementation leverages a key-value store for short-lived state persistence.',
        "descriptionJa": '短期間の状態を保存するためにキーバリューストアを活用する際に使う。',
    },
    {
        "term": 'include robust error handling',
        "meaningJa": '堅牢なエラーハンドリングを含む',
        "usageExample": 'The client includes robust error handling for malformed upstream responses.',
        "descriptionJa": '不正な形式の上流レスポンスに対してエラーハンドリングを行う時に使う。',
    },
    {
        "term": 'implement an endpoint',
        "meaningJa": 'エンドポイントを実装する',
        "usageExample": 'This PR implements an endpoint for updating tutorial progress.',
        "descriptionJa": 'チュートリアルの進行状況を更新するエンドポイントを実装する時に使う。',
    },
    {
        "term": 'refactor A to simplify and standardize B',
        "meaningJa": 'Bを簡素化・標準化するためにAをリファクタリングする',
        "usageExample": 'This change refactors the tests to simplify and standardize authentication setup.',
        "descriptionJa": 'テストを整理し、認証設定を簡素化・標準化する変更であることを指す。',
    },
    {
        "term": 'reduce duplication and improve readability',
        "meaningJa": '重複を減らして可読性を向上させる',
        "usageExample": 'The shared helper reduces duplication and improves readability across the test suite.',
        "descriptionJa": '共通ヘルパー関数により、重複を削減しテストコード全体の可読性を向上させた。',
    },
    {
        "term": 'streamline the internal data structures',
        "meaningJa": '内部データ構造を合理化する',
        "usageExample": 'Removing the unused wrapper streamlines the internal data structures.',
        "descriptionJa": '不要なラッパー関数を削除し、データ構造を簡潔にしたことを表す。',
    },
    {
        "term": 'eliminate an unused field',
        "meaningJa": '未使用フィールドを取り除く',
        "usageExample": 'The refactoring eliminates an unused field from the public response.',
        "descriptionJa": '公開レスポンスから不要なフィールドを削除する変更を説明できる。',
    },
    {
        "term": 'remove references throughout the codebase',
        "meaningJa": 'コードベース全体から参照を削除する',
        "usageExample": 'We removed references to the deprecated flag throughout the codebase.',
        "descriptionJa": '非推奨となったフラグの参照をコードベース全体から削除した。',
    },
    {
        "term": 'match the response schema',
        "meaningJa": 'レスポンススキーマに一致させる',
        "usageExample": 'The service mapping was updated to match the simplified response schema.',
        "descriptionJa": '単純化されたAPIの型にレスポンスマッピングを合わせた。',
    },
    {
        "term": 'reflect the new response shape',
        "meaningJa": '新しいレスポンス形式を反映する',
        "usageExample": 'The API documentation now reflects the new response shape.',
        "descriptionJa": '新しいレスポンスの形状に合わせてドキュメントやコードを修正した。',
    },
    {
        "term": 'align the implementation with the API contract',
        "meaningJa": '実装をAPI契約に適合させる',
        "usageExample": 'This PR aligns the implementation with the published API contract.',
        "descriptionJa": 'API仕様書（契約）と実装の差異を埋めたことを示す。',
    },
    {
        "term": 'resolve a schema mismatch',
        "meaningJa": 'スキーマの不一致を解消する',
        "usageExample": 'The change resolves a schema mismatch in the generated enum values.',
        "descriptionJa": '生成コードと型定義、または実装との食い違いを解消したことを指す。',
    },
    {
        "term": 'have a mismatch between A and B',
        "meaningJa": 'AとBの間に不一致がある',
        "usageExample": 'The field had a mismatch between the specification and the runtime model.',
        "descriptionJa": '仕様と実行時モデルの間にあった不整合を説明する際に使う。',
    },
    {
        "term": 'avoid A being interpreted as B',
        "meaningJa": 'AがBとして解釈されるのを避ける',
        "usageExample": 'The naming prevents the field from being interpreted as a serialized property.',
        "descriptionJa": 'フレームワークやコードスキャンによる誤認を防ぐ目的で変更を行う際に使う。',
    },
    {
        "term": 'cause A to appear incorrectly',
        "meaningJa": 'Aが誤って現れる原因となる',
        "usageExample": 'The misconfiguration caused the property to appear incorrectly in the schema.',
        "descriptionJa": '設定ミスなどで間違ったプロパティが表示されていた現象を説明する。',
    },
    {
        "term": 'correctly expose the allowed values',
        "meaningJa": '許可された値を正しく公開する',
        "usageExample": 'The generated schema now correctly exposes the allowed values.',
        "descriptionJa": '許容値のリストがドキュメントやAPI仕様に正しく反映された。',
    },
    {
        "term": 'introduce a breaking response contract change',
        "meaningJa": '互換性のないレスポンス変更を導入する',
        "usageExample": 'Removing this property introduces a breaking response contract change.',
        "descriptionJa": '破壊的変更（利用側に影響が出る変更）を明示する際に使用。',
    },
    {
        "term": 'be backward-compatible',
        "meaningJa": '後方互換性がある',
        "usageExample": 'The new request field is optional, so the change is backward-compatible.',
        "descriptionJa": '既存クライアントに影響を与えない追加・修正であることを伝える。',
    },
    {
        "term": 'support both the new and old formats',
        "meaningJa": '新旧両方の形式に対応する',
        "usageExample": 'The server temporarily supports both the new and old payload formats.',
        "descriptionJa": '移行期間中の新旧形式互換のための変更を行ったことを示す。',
    },
    {
        "term": 'remove the deprecated fields',
        "meaningJa": '非推奨フィールドを削除する',
        "usageExample": 'We will remove the deprecated fields after all clients have migrated.',
        "descriptionJa": '移行期間終了後のクリーンアップを説明する。',
    },
    {
        "term": 'be carried out in the following steps',
        "meaningJa": '次の手順で実施される',
        "usageExample": 'The rollout will be carried out in the following steps.',
        "descriptionJa": '複数サービスにまたがる段階的なデプロイ手順を導入する際に使う。',
    },
    {
        "term": 'be followed by the client release',
        "meaningJa": 'その後にクライアント側をリリースする',
        "usageExample": 'The backend release will be followed by the client release.',
        "descriptionJa": '依存関係のある順序（バックエンド→フロントエンド）を明示する時に使う。',
    },
    {
        "term": 'add A back if B does not cover it',
        "meaningJa": 'BでカバーできなければAを戻す',
        "usageExample": 'We should add the field back if the new model does not cover this case.',
        "descriptionJa": '条件付きの揺り戻しやフォールバック対応の予定を説明する。',
    },
    {
        "term": 'following a suggestion',
        "meaningJa": '提案を受けて、指摘に従って',
        "usageExample": 'Following a suggestion from the API review, I changed the field to a boolean.',
        "descriptionJa": 'レビューコメントで指摘・提案された内容を反映したことを文脈で伝える。',
    },
    {
        "term": 'it was pointed out that',
        "meaningJa": '〜であると指摘された',
        "usageExample": 'It was pointed out that the original name was ambiguous.',
        "descriptionJa": 'レビューや議論で指摘を受けた経緯を記す際に使用。',
    },
    {
        "term": 'rename A for better clarity',
        "meaningJa": 'より明確にするためAの名前を変更する',
        "usageExample": 'I renamed it to `isNameOverlimit` for better clarity.',
        "descriptionJa": '命名意図が不鮮明な変数名・メソッド名を変更したことを伝える。',
    },
    {
        "term": 'migrate away from A',
        "meaningJa": 'Aから段階的に移行する',
        "usageExample": 'We need to migrate away from the proxy-based integration.',
        "descriptionJa": '古い方式や旧ライブラリからの脱却を目指す文脈で使用。',
    },
    {
        "term": 'instead of relying on A',
        "meaningJa": 'Aに依存する代わりに',
        "usageExample": 'Calling the service requests directly instead of relying on a sidecar.',
        "descriptionJa": 'アーキテクチャや処理の向きを変える理由を記述する。',
    },
    {
        "term": 'have more control',
        "meaningJa": 'より細かい制御・主導権を持つ',
        "usageExample": 'Calling the service directly gives us more control over retries and timeouts.',
        "descriptionJa": '自前実装に変更することで制御性を向上させた意図を伝える。',
    },
    {
        "term": 'handle non-JSON responses properly',
        "meaningJa": 'JSON以外のレスポンスを適切に処理する',
        "usageExample": 'The updated logic can handle non-JSON responses properly.',
        "descriptionJa": '上流サービスの例外的なレスポンス形式への対応を説明する。',
    },
    {
        "term": 'cannot migrate everything at once',
        "meaningJa": 'すべてを一度に移行はできない',
        "usageExample": 'We cannot migrate all clients at once, so both formats must coexist temporarily.',
        "descriptionJa": '段階的移行が必要不可欠な理由を説明する。',
    },
    {
        "term": 'improvement might be limited unless',
        "meaningJa": '〜しない限り改善効果は限定的かもしれない',
        "usageExample": 'The performance improvement might be limited unless the downstream calls are also non-blocking.',
        "descriptionJa": 'ボトルネックや局所的な最適化の限界を指摘する際で使う。',
    },
    {
        "term": 'be a laborious task',
        "meaningJa": '手間のかかる作業である',
        "usageExample": 'Migrating every call site in one PR would be a laborious task.',
        "descriptionJa": '作業範囲の限定や段階的な変更を行う妥当性を主張する。',
    },
    {
        "term": 'put a task on hold',
        "meaningJa": 'タスクを保留にする',
        "usageExample": 'We will put the cleanup task on hold until the client migration is complete.',
        "descriptionJa": '外部要因や他作業の完了待ちで保留にする判断を伝える。',
    },
    {
        "term": 'plan to migrate to',
        "meaningJa": '〜への移行を予定する',
        "usageExample": 'We plan to migrate to the versioned endpoint in the next release.',
        "descriptionJa": '将来的な移行スケジュールや方針を伝える。',
    },
    {
        "term": 'add A temporarily',
        "meaningJa": 'Aを一時的に追加する',
        "usageExample": 'This PR adds the identifier temporarily for migration tracking.',
        "descriptionJa": '恒久的ではない、期間限定で必要なコードであることを明記する。',
    },
    {
        "term": 'fall back to A',
        "meaningJa": 'Aにフォールバックする',
        "usageExample": 'If the preferred value is unavailable, we fall back to the latest cached entry.',
        "descriptionJa": '主データが不在の場合の代替ロジックを説明する。',
    },
    {
        "term": 'support partial updates',
        "meaningJa": '部分更新をサポートする',
        "usageExample": 'The method was changed to PATCH to support partial updates.',
        "descriptionJa": 'リクエストの一部のみを変更するPUT/PATCH系の修正理由を述べる。',
    },
    {
        "term": 'have no equivalent call for A',
        "meaningJa": 'Aに相当する呼び出しが存在しない',
        "usageExample": 'The legacy service has no equivalent call for this resource.',
        "descriptionJa": '他システムとのAPI差分や非互換な機能を指摘する。',
    },
    {
        "term": 'the safest way to verify',
        "meaningJa": '検証する最も安全な方法',
        "usageExample": 'The safest way to verify the change was to test it against the current integration branch.',
        "descriptionJa": '検証手順の理由や妥当性をレビュー者に説明する。',
    },
    {
        "term": 'not be treated as canonical',
        "meaningJa": '正式な実装として扱わない',
        "usageExample": 'This temporary patch should not be treated as canonical.',
        "descriptionJa": '仮実装や暫定コードを正式版と混同しないよう注意する。',
    },
    {
        "term": 'be decided separately',
        "meaningJa": '別途決定する',
        "usageExample": 'The cleanup strategy will be decided separately after validation.',
        "descriptionJa": '今のPRスコープ外にし、後続で方針決定・対応することを指定。',
    },
    {
        "term": 'reproduce an error',
        "meaningJa": 'エラーを再現する',
        "usageExample": 'The stub allows us to reproduce the error consistently in development.',
        "descriptionJa": 'バグ修正用の再現検証環境やテストデータの目的を説明する。',
    },
    {
        "term": 'verify an edge case in integration tests',
        "meaningJa": '境界条件を結合テストで確認する',
        "usageExample": 'We verified this edge case in the integration tests.',
        "descriptionJa": 'エッジケースに対するテストの充実度を示す。',
    },
    {
        "term": 'cover the happy path and the failure path',
        "meaningJa": '正常系と異常系をカバーする',
        "usageExample": 'The tests cover the happy path and the downstream failure path.',
        "descriptionJa": 'テスト網羅性をレビューで主張・説明する際に使う。',
    },
    {
        "term": 'increase branch coverage',
        "meaningJa": '分岐カバレッジを高める',
        "usageExample": 'Additional tests increase branch coverage for the fallback logic.',
        "descriptionJa": '条件分岐の全パターンを網羅する目的のテスト追加を指す。',
    },
    {
        "term": 'be covered by unit and integration tests',
        "meaningJa": '単体・結合テストでカバーされている',
        "usageExample": 'The behavior is currently covered by unit and integration tests.',
        "descriptionJa": '既存の動的な信頼性を保証できている理由を述べる。',
    },
    {
        "term": 'consider it passed if the build succeeds',
        "meaningJa": 'ビルドが成功すれば合格とみなす',
        "usageExample": 'For this internal change, consider it passed if the build succeeds in CI.',
        "descriptionJa": 'CIビルドの合格をもって変更の正当性を証明したとみなす。',
    },
    {
        "term": 'CI passed',
        "meaningJa": 'CIが成功した',
        "usageExample": 'CI passed with all unit and integration tests enabled.',
        "descriptionJa": '自動テスト結果報告を報告する際の使用。',
    },
    {
        "term": 'no production code changed',
        "meaningJa": 'プロダクションコードに変更はない',
        "usageExample": 'This PR is documentation-only and does not affect runtime behavior.',
        "descriptionJa": 'リスクが安全でテストコードのみに変更を限定していることを示す。',
    },
    {
        "term": 'be documentation-only',
        "meaningJa": 'ドキュメントのみの変更である',
        "usageExample": 'This PR is documentation-only and does not affect runtime behavior.',
        "descriptionJa": 'コードの挙動に影響がなく安全であることを伝える。',
    },
    {
        "term": 'have no runtime, API, or configuration changes',
        "meaningJa": '実行時・API・設定への変更がない',
        "usageExample": 'There are no runtime, API, or configuration changes in this update.',
        "descriptionJa": '本番環境や他の機能への副作用がないことを示す。',
    },
    {
        "term": 'establish a standard way to',
        "meaningJa": '〜する標準的な方法を確立する',
        "usageExample": 'The PR establishes a standard way to document service interactions.',
        "descriptionJa": 'ガイドラインや共通手法を設計する目的を説明する。',
    },
    {
        "term": 'provide examples that reviewers can follow',
        "meaningJa": 'レビュー担当者が参考にする例を示す',
        "usageExample": 'The document provides examples that reviewers can follow for future migrations.',
        "descriptionJa": 'サンプル手順や判断の基準・レビューの指標を示す。',
    },
    {
        "term": 'keep A as the source while making B primary',
        "meaningJa": 'Aを保管元として維持しつつBを主ソースとする',
        "usageExample": 'We keep PlantUML as the source while making TDD the primary design document.',
        "descriptionJa": '設計資料などのドキュメント構成に関する役割分担を指す。',
    },
    {
        "term": 'avoid inventing unsupported details',
        "meaningJa": 'サポートされていない詳細を独自に作成しない',
        "usageExample": 'The conversion rules avoid inventing unsupported implementation details.',
        "descriptionJa": '非標準な対応や独自の解釈を排除して標準・仕様に従う意図。',
    },
    {
        "term": 'the root cause was that',
        "meaningJa": '根本原因は〜だった',
        "usageExample": 'The root cause was that the ownership lookup ran before input validation.',
        "descriptionJa": 'バグ調査の結果や不具合の直接的な原因を説明する。',
    },
    {
        "term": 'perform A before validating B',
        "meaningJa": 'Bを検証する前にAを実行する',
        "usageExample": 'The previous flow performed a database lookup before validating the identifier.',
        "descriptionJa": '処理順序の不具合（順序逆転による無効処理実行）を示す。',
    },
    {
        "term": 'exceed the supported format boundary',
        "meaningJa": 'サポートされる形式の境界を超える',
        "usageExample": 'The error occurred when the identifier exceeds the supported format boundary.',
        "descriptionJa": '入力値がサポートされているフォーマットや長さの範囲を超えているケースを示す。',
    },
    {
        "term": 'surface an upstream error as a server error',
        "meaningJa": '上流エラーをサーバーエラーとして露出させる',
        "usageExample": 'The old implementation surfaced an upstream validation error as a server error.',
        "descriptionJa": '不適切なエラーハンドリングやステータスコードの変換を指す。',
    },
    {
        "term": 'leave the cached value state or incomplete',
        "meaningJa": 'キャッシュされた値を古い、または不完全な状態にしておく',
        "usageExample": 'A failed update can leave the cached mapping state or incomplete.',
        "descriptionJa": 'キャッシュ不整合や非同期処理での失敗時の危険性を説明する。',
    },
    {
        "term": 'prevent confusion',
        "meaningJa": '混乱を防ぐ',
        "usageExample": 'The enum was renamed to prevent confusion about its business meaning.',
        "descriptionJa": '命名変更や仕様 clarifying の目的として記載する。',
    },
    {
        "term": 'prevent A from being stored',
        "meaningJa": 'Aが保存されるのを防ぐ',
        "usageExample": 'The validation prevents an oversized expiration value from being stored.',
        "descriptionJa": 'バリデーションで不正な値が保存されないようにする。',
    },
    {
        "term": 'prevent an unnecessary call',
        "meaningJa": '不要な呼び出しを防ぐ',
        "usageExample": 'The empty-state check prevents an unnecessary downstream call.',
        "descriptionJa": 'ガード条件による処理省略や性能最適化をアピールする。',
    },
    {
        "term": 'avoid an unnecessary client error',
        "meaningJa": '不必要なクライアントエラーを避ける',
        "usageExample": 'Returning no content avoids an unnecessary client error for expired data.',
        "descriptionJa": '意図しないエラーレスポンスによる不必要なアラートやログ出力を抑止する。',
    },
    {
        "term": 'avoid static-analysis false positives',
        "meaningJa": '静的解析の誤検知を避ける',
        "usageExample": 'The generated repository is excluded to avoid static-analysis false positives.',
        "descriptionJa": '静的解析ツール（SonarQube等）での誤検知を回避する対応。',
    },
    {
        "term": 'return an empty list instead of an error',
        "meaningJa": 'エラーではなく空リストを返す',
        "usageExample": 'The adapter returns an empty list instead of a server error when the upstream body is null.',
        "descriptionJa": 'エラーハンドリングの挙動変更で、データ不在を正常系として扱うケース。',
    },
    {
        "term": 'avoid sending the app to the error page',
        "meaningJa": 'アプリがエラーページへ遷移するのを防ぐ',
        "usageExample": 'The empty response avoids sending the app to the error page for this condition.',
        "descriptionJa": 'バックエンドのレスポンス変更によりアプリ側のUX低下（画面エラー表示）を防ぐ。',
    },
    {
        "term": 'treat A as a non-error response',
        "meaningJa": 'Aをエラーでないレスポンスとして扱う',
        "usageExample": 'A suspended account should be treated as a non-error response with no available options.',
        "descriptionJa": '特定の業務例外ステータスを正常系レスポンスとして分類する。',
    },
    {
        "term": 'mask sensitive paths in logs',
        "meaningJa": 'ログ内の機密パスをマスキングする',
        "usageExample": 'The filter masks sensitive paths in logs before they are exported.',
        "descriptionJa": 'ログ出力におけるセキュリティ保護強化を報告する。',
    },
    {
        "term": 'ensure correct masking behavior',
        "meaningJa": '正しいマスキング動作を保証する',
        "usageExample": 'Test cases ensure correct masking behavior for every protected route.',
        "descriptionJa": 'セキュリティ保護に関するテストの補強内容を示す。',
    },
    {
        "term": 'improve privacy and security in Logging',
        "meaningJa": 'ログのプライバシーとセキュリティを向上させる',
        "usageExample": 'The redaction rules improves privacy and security in logging.',
        "descriptionJa": 'ログ内の感性データ漏洩を防ぎセキュリティ向上させたことを表す。',
    },
    {
        "term": 'verify that unrelated A are unaffected',
        "meaningJa": '無関係な箇所に影響がないことを確認する',
        "usageExample": 'The tests verify that unrelated endpoints are unaffected by the masking rule.',
        "descriptionJa": '共通変更の影響が無関係な箇所に及ばないことを確認する。',
    },
    {
        "term": 'have the potential of leaking A',
        "meaningJa": 'Aを漏洩させる可能性がある',
        "usageExample": 'The raw path request had the potential of leaking credential.',
        "descriptionJa": '修正前の問題としてセキュリティリスクを理由に記述する。',
    },
    {
        "term": 'be consistently masked in logs',
        "meaningJa": 'ログ内で一貫してマスキングされる',
        "usageExample": 'Sensitive identifiers are consistently masked in logs.',
        "descriptionJa": 'ログ出力内の機密情報が一貫して保護される状態を報告する。',
    },
    {
        "term": 'store a hash instead of the whole token',
        "meaningJa": 'トークン全体ではなくハッシュを保存する',
        "usageExample": 'Storing only the hash of the whole token value.',
        "descriptionJa": '生トークンを直接保持せずセキュリティを高めた変更内容。',
    },
    {
        "term": 'save memory',
        "meaningJa": 'メモリ使用量を削減する',
        "usageExample": 'Storing only the JME token value to save memory.',
        "descriptionJa": 'データ軽量化やメモリ効率化の目的を明確に示す。',
    },
    {
        "term": 'only merge when',
        "meaningJa": '〜の場合にのみマージする',
        "usageExample": 'Only merge when both staging environments accept the new key.',
        "descriptionJa": '依存関係やリリース環境の条件付きのマージ手順を記述。',
    },
    {
        "term": 'as part of a security review response',
        "meaningJa": 'セキュリティレビューへの対応の一環として',
        "usageExample": 'The token encryption was updated as part of a security review response.',
        "descriptionJa": '修正がセキュリティレビューへの対応であることを明記する。',
    },
    {
        "term": 'add an additional authentication check',
        "meaningJa": '追加の認証チェックを加える',
        "usageExample": 'This PR adds an additional authentication check to sensitive endpoints.',
        "descriptionJa": '特定エンドポイントの保護レベルを上げるセキュリティ強化。',
    },
    {
        "term": 'catch failures and latencies',
        "meaningJa": '失敗と遅延を検知する',
        "usageExample": 'The performance threshold catch failures and latencies before release.',
        "descriptionJa": '監視ツールやメトリクスによるエラーや遅延の検知について述べる。',
    },
    {
        "term": 'track performance by scenario',
        "meaningJa": 'シナリオ別に性能を追跡する',
        "usageExample": 'The report is split so we can track performance by scenario.',
        "descriptionJa": 'ダッシュボードやメトリクスの可視化範囲を細分化したことを示す。',
    },
    {
        "term": 'reflect real latency',
        "meaningJa": '実際のレイテンシーを反映する',
        "usageExample": 'The histogram boundary was increased to reflect real latency in production.',
        "descriptionJa": '本番環境の実測値に合わせて測定スケールや閾値を修正した。',
    },
    {
        "term": 'make the metrics inaccurate',
        "meaningJa": 'メトリクスを不正確にする',
        "usageExample": 'Capping the histogram too low would make the metrics inaccurate.',
        "descriptionJa": '不適切な設定がモニタリング精度に与過える悪影響について述べる。',
    },
    {
        "term": 'increase the load considerably',
        "meaningJa": '負荷を大幅に増加させる',
        "usageExample": 'Fetching unrelated attributes may increase the load on downstream services considerably.',
        "descriptionJa": '設計上の選択による他システムへの負荷増大リスクを示す。',
    },
    {
        "term": 'cause high latency',
        "meaningJa": '高いレイテンシーを引き起こす',
        "usageExample": 'Uncorrelated attributes on this path was causing high latency.',
        "descriptionJa": 'パフォーマンス劣化や遅延発生の原因調査結果を報告する。',
    },
    {
        "term": 'optimize A not to call B',
        "meaningJa": 'Bを呼び出さないようAを最適化する',
        "usageExample": 'We optimized the summary endpoint not to call two unrelated downstream services.',
        "descriptionJa": '不要なAPI通信を省くことによる最適化を説明する。',
    },
    {
        "term": 'reduce the number of lines for manageability',
        "meaningJa": '管理しやすくするため行数を減らす',
        "usageExample": 'The logic was split into multiple files to reduce the number of lines for manageability.',
        "descriptionJa": '巨大なファイルの分割やコード整理の目的を示す。',
    },
    {
        "term": 'let us focus on the relevant code',
        "meaningJa": '関連するコードに集中できるようにする',
        "usageExample": 'The helper lets reviewers focus on the client code during review.',
        "descriptionJa": 'コードレビューの効率を改善するための工夫を説明する。',
    },
    {
        "term": 'ensure compatibility with the latest frameworks',
        "meaningJa": '最新フレームワークとの互換性を確保する',
        "usageExample": 'The update ensures compatibility with the latest supported frameworks.',
        "descriptionJa": '依存ライブラリのバージョンアップ理由を明記する。',
    },
    {
        "term": 'resolve a production issue',
        "meaningJa": '本番環境の不具合を解消する',
        "usageExample": 'This hotfix resolves a production issue affecting upgraded accounts.',
        "descriptionJa": '修正の緊急性や本番問題の解決目的を伝える。',
    },
    {
        "term": 'preserve a URI template',
        "meaningJa": 'URIテンプレートを保持する',
        "usageExample": 'The router preserves the URI template so the metrics suite can route labels.',
        "descriptionJa": 'メトリクスやタグ作成のために生のURIパターンを保つ。',
    },
    {
        "term": 'result in high cardinality',
        "meaningJa": '高カーディナリティを引き起こす',
        "usageExample": 'Using expanded identifiers in metric labels can result in high cardinality.',
        "descriptionJa": 'メトリクスラベルの動的パラメータ等による高カーディナリティ（データ膨大化）のリスクを説明する。',
    },
    {
        "term": 'keep metric cardinality low',
        "meaningJa": 'メトリクスのカーディナリティを低く保つ',
        "usageExample": 'Route templates keep metric cardinality low across dynamic requests.',
        "descriptionJa": 'モニタリングの負荷・コスト増加を抑える適切な設計手法を示す。',
    },
    {
        "term": 'avoid the same issue when copying code',
        "meaningJa": 'コードをコピーしたときに同じ問題を避ける',
        "usageExample": 'I updated the other call sites to avoid the same issue when copying code.',
        "descriptionJa": 'コピペで同様の不具合が広がらないよう他箇所も直す理由。',
    },
    {
        "term": 'prioritize user experience',
        "meaningJa": 'ユーザー体験を優先する',
        "usageExample": 'For short-lived failure, we prioritize user experience and continue with a safe fallback.',
        "descriptionJa": 'エラー発生時に即座にエラーを出さず、フォールバック等でUXを保つ設計方針。',
    },
    {
        "term": 'have a limited period of negative impact',
        "meaningJa": '悪影響が及ぶ期間が限定的されている',
        "usageExample": 'The state value has a limited period of negative impact because it expires quickly.',
        "descriptionJa": '不具合や互換性の問題の影響が一時的であり、時間の経過で自然解消されることを報告する。',
    },
    {
        "term": 'follow the single-responsibility principle',
        "meaningJa": '単一責任の原則に従う',
        "usageExample": 'The repository was separated from the service to follow the single-responsibility principle.',
        "descriptionJa": 'クラスやモジュールの分割理由として、単一責任原則への準拠を挙げる。',
    },
    {
        "term": 'separate service-level and repository-level tests',
        "meaningJa": 'サービスレベルとリポジトリレベルのテストを分離する',
        "usageExample": 'The integration suite separates service-level and repository-level tests.',
        "descriptionJa": 'テストコード構造の整備やレイヤー別のテストカバレッジ設定を説明する。',
    },
    {
        "term": 'be too tightly coupled to a specific use case',
        "meaningJa": '特定のユースケースに密結合しすぎている',
        "usageExample": 'The shared helper was too tightly coupled to a specific screen flow.',
        "descriptionJa": '共通化されているが汎用性が低く、修正や分離が必要な理由を説明する。',
    },
    {
        "term": 'reuse it across multiple surfaces',
        "meaningJa": '複数の画面・UI層で再利用する',
        "usageExample": 'The response can reuse the response across multiple surfaces without duplicating requests.',
        "descriptionJa": 'APIやコンポーネントを共通化し汎用利用できるようにしたことをアピール。',
    },
    {
        "term": 'have a minimal impact on',
        "meaningJa": '〜への影響が極めて小さい',
        "usageExample": 'The additional entries should have a minimal impact on cache capacity.',
        "descriptionJa": '変更によるリソース消費や他機能への副作用が無視できるレベルであることを示す。',
    },
    {
        "term": 'not move the needle much',
        "meaningJa": '刻みを大きく変えない、大した差を生まない',
        "usageExample": 'Shortening the key further would not move the needle much at this scale.',
        "descriptionJa": 'これ以上の最適化を行っても全体的なインパクトが微小である旨を伝える。',
    },
    {
        "term": 'add a validation layer',
        "meaningJa": '検証層を追加する',
        "usageExample": 'The PR adds a validation layer for external metadata before it reaches the core service.',
        "descriptionJa": 'バリデーションの責務を独立した層として追加する変更。',
    },
    {
        "term": 'transform flat keys into a nested structure',
        "meaningJa": 'フラットなキーを入れ子構造へ変換する',
        "usageExample": 'The adapter transforms flat keys into the nested structure expected by the client.',
        "descriptionJa": 'レスポンスのデータ形式整形（ネスト化）を行う理由。',
    },
    {
        "term": 'check that paired values are complete',
        "meaningJa": '対になる値が揃っていることを確認する',
        "usageExample": 'The validator checks that paired locate values are complete before transformation.',
        "descriptionJa": '関連する複数フィールドの整合性チェック（両方存在するか等）を説明する。',
    },
    {
        "term": 'restrict A to a supported subset',
        "meaningJa": 'Aをサポート対象の一部に制限する',
        "usageExample": 'The renderer restricts Markdown to a supported subset of formatting features.',
        "descriptionJa": '入力値や利用可能な機能のスコープを制限・フィルタリングする。',
    },
    {
        "term": 'force tests to be updated when properties change',
        "meaningJa": 'プロパティ変更時にテストの更新を強要する',
        "usageExample": 'Strict comparison forces tests to be updated when response properties change.',
        "descriptionJa": '型変更やプロパティ追加時にサイレントにテストが通るのを防ぐアサーション。',
    },
    {
        "term": 'ensure consistent handling across the workflow',
        "meaningJa": 'ワークフロー全体で一貫した処理を保障する',
        "usageExample": 'The shared model ensures consistent handling of identifiers across the workflow.',
        "descriptionJa": 'ドメインモデルや処理の流れ全体で処理の一貫性を担保したこと。',
    },
    {
        "term": 'ensure that tests reflect the new requirements',
        "meaningJa": 'テストが新しい要件を反映していることを確認する',
        "usageExample": 'The fixtures were updated to ensure that tests reflect the new data requirements.',
        "descriptionJa": '仕様変更に伴うテストコード・フィクスチャの適正化を述べる。',
    },
    {
        "term": 'make the response easier to consume',
        "meaningJa": 'レスポンスを扱いやすくする',
        "usageExample": 'Replacing the boolean with an enum makes the response easier to consume.',
        "descriptionJa": 'クライアント側が扱いやすいレスポンス形に整える変更。',
    },
    {
        "term": 'align the contract with the actual semantics',
        "meaningJa": '契約を実際の意味に合わせる',
        "usageExample": 'We should align the contract with the actual semantics before clients adopt the new field.',
        "descriptionJa": '公開契約と実装の意味が一致するよう整える。',
    },
]
