"""User-provided Incident Response vocabulary fields (100 entries)."""

USER_ENTRIES: list[dict] = [
    {
        "term": "notice the status had changed",
        "meaningJa": "ステータスが変わったことに気づく",
        "usageExample": "I noticed the incident status had changed to Resolved.",
        "descriptionJa": "インシデントのステータスがResolved（解決済み）になっていたことに共有する。",
    },
    {
        "term": "An alert occurred in this thread as well",
        "meaningJa": "このスレッドでもアラートが発生した",
        "usageExample": "An alert occurred in this thread as well.",
        "descriptionJa": "このスレッド内でもアラートが発生したことを報告する。",
    },
    {
        "term": "The alert keeps getting triggered",
        "meaningJa": "アラートが繰り返し発生している",
        "usageExample": "The alert keeps getting triggered every few minutes.",
        "descriptionJa": "数分おきにアラートが連続発生している状況を共有する。",
    },
    {
        "term": "alerts suddenly started firing frequently",
        "meaningJa": "アラートが突然頻発し始めた",
        "usageExample": "These alerts suddenly started firing frequently after noon.",
        "descriptionJa": "正午過ぎからアラートが突然頻発し始めた事例として共有する。",
    },
    {
        "term": "Is the alert still active?",
        "meaningJa": "アラートがまだ有効か",
        "usageExample": "Is the alert still active, or was it auto-resolved?",
        "descriptionJa": "アラートが現在も発生中か、自動解決したかを確認する。",
    },
    {
        "term": "CPU usage briefly spiked again",
        "meaningJa": "CPU使用率が再び一時的に急上昇した",
        "usageExample": "CPU usage briefly spiked again, but it is decreasing now.",
        "descriptionJa": "一時的にスパイクが発生したものの、現在の傾向とともに報告する。",
    },
    {
        "term": "seeing lots of ... in the logs",
        "meaningJa": "ログに特定の表現が多く表示されている",
        "usageExample": "We are seeing lots of timeout errors in the logs.",
        "descriptionJa": "ログ側で特定パターンが大量にあったことを共有する。",
    },
    {
        "term": "usage is gradually increasing",
        "meaningJa": "使用量が徐々に増加している",
        "usageExample": "Memory usage is gradually increasing, while the hit rate remains stable.",
        "descriptionJa": "集中急増ではないものの、悪化傾向があることを報告する。",
    },
    {
        "term": "successful requests have dropped to zero",
        "meaningJa": "成功リクエストがゼロまで減少した",
        "usageExample": "Successful requests have dropped to zero in the last five minutes.",
        "descriptionJa": "過去5分間で成功リクエスト数がゼロに落ちた致命的影響を述べる。",
    },
    {
        "term": "The error started again",
        "meaningJa": "エラーが再び発生し始めた",
        "usageExample": "The initialization error started again around 18:00.",
        "descriptionJa": "再発のタイミングを報告する。",
    },
    {
        "term": "Be quickly auto-resolved",
        "meaningJa": "短時間で自動解決される",
        "usageExample": "The alerts were quickly auto-resolved, so this may have been a brief spike.",
        "descriptionJa": "瞬間的な誤検知や一時的な問題であったと推測する根拠として共有する。",
    },
    {
        "term": "Might be worth checking what happened",
        "meaningJa": "何が起きたか確認する価値がありそうだ",
        "usageExample": "It might be worth checking what happened during that spike.",
        "descriptionJa": "調査の必要性を提案する際、スパイク発生時の調査を進めると良い旨伝える。",
    },
    {
        "term": "check if there is any impact",
        "meaningJa": "影響があるか確認する",
        "usageExample": "Let me check if there is any impact on production traffic.",
        "descriptionJa": "本番トラフィックへ影響が出ているか等を確認するときに使う。",
    },
    {
        "term": "should not affect ... but let me verify",
        "meaningJa": "影響しない可能性が高いが確認する",
        "usageExample": "This should not affect production, but let me verify.",
        "descriptionJa": "影響無しの可能性を示しつつ、本番環境に影響が無い安全性を保つ。",
    },
    {
        "term": "should not impact the user experience",
        "meaningJa": "ユーザー体験には影響しない見込みである",
        "usageExample": "This should not impact the user experience, but we are verifying it.",
        "descriptionJa": "影響がないと考えているものの、念のため確認中であることを伝達する。",
    },
    {
        "term": "users cannot log in to production",
        "meaningJa": "ユーザーが本番環境にログインできない",
        "usageExample": "Users currently cannot log in to production.",
        "descriptionJa": "ログイン不可など特定機能の障害報告を行う。",
    },
    {
        "term": "might have been affected during the downtime",
        "meaningJa": "停止時間中に影響を受けた可能性がある",
        "usageExample": "Some users might have been affected during the downtime.",
        "descriptionJa": "影響範囲が確定していない段階で可能性を伝える。",
    },
    {
        "term": "at maximum, ... users were impacted",
        "meaningJa": "最大で〜人が影響を受けた",
        "usageExample": "At maximum, 500 users may have been impacted.",
        "descriptionJa": "最悪のケースでの影響人数を試算し、報告として共有する。",
    },
    {
        "term": "evaluate the number of impacted users",
        "meaningJa": "影響ユーザー数を評価する",
        "usageExample": "We need to evaluate the number of impacted users.",
        "descriptionJa": "影響範囲測定のアクションとして明確にする。",
    },
    {
        "term": "have a significant impact on business KPIs",
        "meaningJa": "売上に重大な影響を与える",
        "usageExample": "The incident may have had a significant impact on business KPIs.",
        "descriptionJa": "新規登録数や売上への定量的影響を述べる。",
    },
    {
        "term": "clarify which features were unavailable",
        "meaningJa": "利用不能だった機能を明確にする",
        "usageExample": "We should clarify which features were unavailable during the incident.",
        "descriptionJa": "どの機能が使えなかったかを明確にし、顧客影響の範囲を明確にする。",
    },
    {
        "term": "Identify the impact scope at the user or session level",
        "meaningJa": "ユーザーまたはセッション単位で影響範囲を特定する",
        "usageExample": "Can we identify the impact scope at the user or session level?",
        "descriptionJa": "影響を個別のユーザーやセッション単位で精密に特定する。",
    },
    {
        "term": "limit the impact scope to the target features",
        "meaningJa": "影響範囲を対象機能に限定する",
        "usageExample": "We need to limit the impact scope to the target features.",
        "descriptionJa": "影響を特定機能のみに留め、範囲の拡散を防ぐ。",
    },
    {
        "term": "as long as production is healthy",
        "meaningJa": "本番環境が正常である限り",
        "usageExample": "As long as production is healthy, we can continue investigating during business hours.",
        "descriptionJa": "本番環境が正常であれば、緊急の夜間対応ではなく営業時間内に調査を継続することを提案する。",
    },
    {
        "term": "be safe on the product side",
        "meaningJa": "プロダクト側としては問題ない状態",
        "usageExample": "It seems to be safe on the product side, but the frontend flow still needs investigation.",
        "descriptionJa": "バックエンド側で問題が確認されていないものの、安全が確認できていない部分の調査を継続する。",
    },
    {
        "term": "seem to be the same issue",
        "meaningJa": "同じ問題のように見える",
        "usageExample": "This seems to be the same issue we saw yesterday.",
        "descriptionJa": "以前発生した問題と同じ現象・類似傾向がある事象を共有する。",
    },
    {
        "term": "look slightly different",
        "meaningJa": "少し異なって見える",
        "usageExample": "This error looks slightly different from the previous one.",
        "descriptionJa": "過去の同様事例とは性質やエラーログが少し異なることを指摘する。",
    },
    {
        "term": "doesn't seem to be an app issue",
        "meaningJa": "アプリの問題ではなさそうだ",
        "usageExample": "Based on the downstream logs, it doesn't seem to be an app issue.",
        "descriptionJa": "アプリレイヤーの問題ではないと一次切り分けを行い、別の要因を探る。",
    },
    {
        "term": "the error originates from ...",
        "meaningJa": "エラーの発生元は〜である",
        "usageExample": "The error appears to originate from the routing layer.",
        "descriptionJa": "ルーティング層や特定コンポーネントがエラーの発生起点であることを指摘する。",
    },
    {
        "term": "come from canary",
        "meaningJa": "カナリア環境由来である",
        "usageExample": "The failing requests appear to come from canary, not production.",
        "descriptionJa": "本番トラフィックではなくカナリアからのものであることを明示する。",
    },
    {
        "term": "cannot see errors from production",
        "meaningJa": "本番環境からのエラーは確認できない",
        "usageExample": "We don't see any corresponding server errors from production.",
        "descriptionJa": "調べてみた結果、本番環境側で確認できないことを伝える。存在しない可能性の提示。",
    },
    {
        "term": "find the source",
        "meaningJa": "発生元を特定する",
        "usageExample": "We need to find the source before changing the alert rule.",
        "descriptionJa": "アラートやエラーが発生しているトラフィックのソース（出処）を突き止める。",
    },
    {
        "term": "the URL path seems consistent",
        "meaningJa": "URLパスには一貫性があるようだ",
        "usageExample": "The URL path seems consistent across the recent events.",
        "descriptionJa": "障害イベントの共通点・パターンを指摘し、対象範囲を探る。",
    },
    {
        "term": "confirm whether ... is performing testing",
        "meaningJa": "〜がテストを実行中か確認する",
        "usageExample": "First, let's confirm whether another team is performing testing.",
        "descriptionJa": "負荷テストや他チームの作業が影響していないか共有・確認を入れる。",
    },
    {
        "term": "match the incident timeline",
        "meaningJa": "インシデントの発生時間帯と一致する",
        "usageExample": "The error timestamps match the incident timeline.",
        "descriptionJa": "収集したログやイベントの時刻が障害発生時間と一致した時に使う。",
    },
    {
        "term": "link the events together",
        "meaningJa": "脈々の事象を関連付ける",
        "usageExample": "The traffic drop helped us link the two events together.",
        "descriptionJa": "離れて見えていた事象（例：トラフィック低下とログエラー）が関連していたと気づいた際に使う。",
    },
    {
        "term": "confirm that the root cause is the same",
        "meaningJa": "根本原因が同じか確認する",
        "usageExample": "We should confirm that the root cause is the same for all recent errors.",
        "descriptionJa": "生じた複数箇所のアラート・エラーを一元処理できるか一意原因か確認する。",
    },
    {
        "term": "have no spike and no obvious increase",
        "meaningJa": "スパイクや明確な増加はない",
        "usageExample": "The upstream service has no spike and no obvious increase in errors.",
        "descriptionJa": "調査により特定の異常値や目立った増加が見られないことを報告する。",
    },
    {
        "term": "can't seem to find any relevant logs",
        "meaningJa": "該当するログが見つからない",
        "usageExample": "I can't seem to find any relevant logs for this request.",
        "descriptionJa": "調査に必要なログが見当たらない・出力されていないことを明確にする。",
    },
    {
        "term": "need more details to investigate further",
        "meaningJa": "さらなる調査には詳細が必要である",
        "usageExample": "I need more details to investigate further.",
        "descriptionJa": "情報不足（再現手順や関連ログ等）を指摘し、次のアクションへ促す。",
    },
    {
        "term": "appear to be a consequence of ...",
        "meaningJa": "〜の好結果として現れていると思われる",
        "usageExample": "This appears to be a consequence of the upstream timeout.",
        "descriptionJa": "発生したエラーが一次要因ではなく、二次障害の二次的結果という見解を示す。",
    },
    {
        "term": "seem like a network error",
        "meaningJa": "ネットワークエラーのプロミスに見える",
        "usageExample": "This seems like a network error, but we need the client logs to confirm.",
        "descriptionJa": "ネットワーク要因と推測・仮説として提示する。",
    },
    {
        "term": "I think it is very likely",
        "meaningJa": "その可能性が非常に高いと思う",
        "usageExample": "I think it is very likely that this is a client-side issue.",
        "descriptionJa": "強い確信をしつつ、確定ではないことを保つ。",
    },
    {
        "term": "It seems like the call is failing",
        "meaningJa": "呼び出しが失敗しているようだ",
        "usageExample": "It seems like the upstream call is failing before the response is returned.",
        "descriptionJa": "サービス間通信の失敗が疑われる際に使う。",
    },
    {
        "term": "assuming that's the case",
        "meaningJa": "それが事実だと仮定すると",
        "usageExample": "Assuming that's the case, the duplicate requests may explain the spike.",
        "descriptionJa": "ある推測を前提とした場合の説明や影響範囲を考察する。",
    },
    {
        "term": "I suspect someone is trying to",
        "meaningJa": "誰かが〜しようとしている疑いがある",
        "usageExample": "I suspect someone is trying to probe unsupported endpoints.",
        "descriptionJa": "攻撃や不正アクセスの兆候・あるいは不自然なリクエストがあった際にセキュリティ情報を共有する。",
    },
    {
        "term": "I don't know yet the intensity or scale",
        "meaningJa": "規模や強度はまだわからない",
        "usageExample": "I don't know yet the intensity or scale of the traffic.",
        "descriptionJa": "事象は発生しているが、影響の全体量・全容が未確定であることを明示する。",
    },
    {
        "term": "look like random probing",
        "meaningJa": "ランダムなスキャン/探索のように見える",
        "usageExample": "The requests look like random probing, but we are checking their origin.",
        "descriptionJa": "不審なリクエストのパターンのアセスメント。",
    },
    {
        "term": "possibly due to load testing",
        "meaningJa": "負荷テストの影響の可能性がある",
        "usageExample": "The spike was possibly due to load testing.",
        "descriptionJa": "テストによる影響・誤検知の可能性として挙げる。",
    },
    {
        "term": "if I understand the situation correctly",
        "meaningJa": "状況の理解が正しければ",
        "usageExample": "If I understand the situation correctly, this is isolated to the cache layer.",
        "descriptionJa": "現状の認識を述べつつ間違っていないかのすり合わせをする。",
    },
    {
        "term": "errors could be caused by ...",
        "meaningJa": "エラーは〜が原因の可能性がある",
        "usageExample": "The errors could be caused by stale client-side data.",
        "descriptionJa": "原因の候補・可能性を提示する。",
    },
    {
        "term": "someone likely retries",
        "meaningJa": "ユーザーが再試行している可能性が高い",
        "usageExample": "Someone likely retries after the first request fails.",
        "descriptionJa": "リクエスト数の増加の背景にユーザーの再試行挙動がある可能性を指摘する。",
    },
    {
        "term": "investigate why they failed and later succeeded",
        "meaningJa": "失敗後に成功した理由を調査する",
        "usageExample": "We should investigate why the same sessions failed and later succeeded.",
        "descriptionJa": "時間差で状況が改善・変化した理由を解き明かす時に使う。",
    },
    {
        "term": "cannot be silenced the normal way",
        "meaningJa": "通常の方法ではアラートを停止できない",
        "usageExample": "These alerts cannot be silenced the normal way.",
        "descriptionJa": "アラートの挙動が通常と異なり、別の対応が必要なことを共有する。",
    },
    {
        "term": "Turn them off",
        "meaningJa": "それらを停止する",
        "usageExample": "We may need an additional rule to turn these alerts off temporarily.",
        "descriptionJa": "修正や調査中に一時的に通知をオフにすることを共有する。",
    },
    {
        "term": "suppress alerts",
        "meaningJa": "アラートを抑制する",
        "usageExample": "This rule will suppress alerts for the known error pattern.",
        "descriptionJa": "既知の問題に対して不要な通知を抑制するための設定をする時に使う。",
    },
    {
        "term": "create a silence",
        "meaningJa": "アラート停止設定を作成する",
        "usageExample": "I created a silence for the known warning until tomorrow.",
        "descriptionJa": "一時的に特定の既知アラートの通知を抑止する。",
    },
    {
        "term": "adjust the rules",
        "meaningJa": "アラート条件を調整する",
        "usageExample": "If the alert fires again, we can adjust the rules.",
        "descriptionJa": "誤検知や過剰通知を減らすためルールの見直しを行う。",
    },
    {
        "term": "roll back the change",
        "meaningJa": "変更をロールバックする",
        "usageExample": "We need to determine whether to roll back the change.",
        "descriptionJa": "切り戻し（ロールバック）の検討・実行について話し合う。",
    },
    {
        "term": "manually clear the cache",
        "meaningJa": "キャッシュを手動で消去する",
        "usageExample": "Should we manually clear the cache to restore login temporarily?",
        "descriptionJa": "一時的対処としてキャッシュクリアを提案・実行。",
    },
    {
        "term": "flush and re-scale the cache",
        "meaningJa": "キャッシュを消去し、再スケールする",
        "usageExample": "We might need to flush and re-scale the cache instance.",
        "descriptionJa": "容量不足などへの根本対処として提出する。",
    },
    {
        "term": "upgrade the node type",
        "meaningJa": "ノードタイプをアップグレードする",
        "usageExample": "We are upgrading the node type to restore capacity.",
        "descriptionJa": "リソース不足への対処の実行を報告する。",
    },
    {
        "term": "re-enable login",
        "meaningJa": "ログインを再び有効化する",
        "usageExample": "The temporary cleanup may re-enable login while we prepare a permanent fix.",
        "descriptionJa": "機能制限を解除して暫定対処で回復させる旨を述べる。",
    },
    {
        "term": "delay the problem a bit",
        "meaningJa": "問題の発生を少し先送りする",
        "usageExample": "This may restore service, but it will only delay the problem a bit.",
        "descriptionJa": "応急処置であり、根本解決ではないことを明確にする。",
    },
    {
        "term": "resolve them with some notes",
        "meaningJa": "メモを添えてアラートを解決済みとする",
        "usageExample": "If these are expected errors, let's resolve them with some notes.",
        "descriptionJa": "静観可能・解決済みとしてメモを残しクローズすることを提案する。",
    },
    {
        "term": "take this on",
        "meaningJa": "この対応を引き受ける",
        "usageExample": "If nobody is available, I can take this on.",
        "descriptionJa": "担当者不在時に自発的に対応を引き受ける意思を示す。",
    },
    {
        "term": "working on it",
        "meaningJa": "対応中である",
        "usageExample": "I'm working on it and preparing the configuration change.",
        "descriptionJa": "自身が進行中であることをチームに提示する。",
    },
    {
        "term": "involve the infrastructure team",
        "meaningJa": "インフラチームを巻き込む",
        "usageExample": "We need to bring in the infrastructure team.",
        "descriptionJa": "アプリレイヤーだけでは解決できない場合、他チームへ協力・依頼を求める。",
    },
    {
        "term": "escalate it to them",
        "meaningJa": "彼らへエスカレーションする",
        "usageExample": "Should we escalate it to the owning team?",
        "descriptionJa": "適切な担当チームへの正式な割り振りを提議する。",
    },
    {
        "term": "ping the members",
        "meaningJa": "担当メンバーに連絡する",
        "usageExample": "Can you ping the on-call members for this service?",
        "descriptionJa": "当番や特定メンバーをメンションやチャットで直接呼び出す。",
    },
    {
        "term": "join our call",
        "meaningJa": "障害対応の通話に参加する",
        "usageExample": "Please join our call if you need to share updates or ask questions.",
        "descriptionJa": "同期コミュニケーションが必要な場面で通話参加を促す。",
    },
    {
        "term": "please help",
        "meaningJa": "支援を要請する",
        "usageExample": "I don't have access to the configuration, so please help.",
        "descriptionJa": "権限がない・対応しきれない場合の協力依頼。",
    },
    {
        "term": "lack permissions",
        "meaningJa": "必要な権限がない",
        "usageExample": "I tried to apply the change, but I lack permissions.",
        "descriptionJa": "対処できない理由を明示し、権限所有者への引き継ぎを促す。",
    },
    {
        "term": "post a summary shortly",
        "meaningJa": "まもなく概要を更新する",
        "usageExample": "I have completed the initial investigation, and I'll post a summary shortly.",
        "descriptionJa": "調査・対応の進捗状況を後ほど一括で共有することを告知する。",
    },
    {
        "term": "wait and see",
        "meaningJa": "しばらく様子を見る",
        "usageExample": "The last alert was ten minutes ago, so we'll wait and see.",
        "descriptionJa": "状態変更後に即対応と断定せず、再現の有無を静観する。",
    },
    {
        "term": "the suppression worked",
        "meaningJa": "アラート抑止が機能した",
        "usageExample": "It seems that the suppression worked.",
        "descriptionJa": "抑止設定後に通知が止まったことを報告し、設定完了とする。",
    },
    {
        "term": "should be silenced by now",
        "meaningJa": "今頃はアラートが停止されているはずだ",
        "usageExample": "The known alerts should be silenced by now.",
        "descriptionJa": "設定反映の反映時間を考慮し、確認見込みを伝える。",
    },
    {
        "term": "It looks like there are no more errors",
        "meaningJa": "追加のエラーはなさそうだ",
        "usageExample": "It looks like there are no more errors, but I'll keep monitoring.",
        "descriptionJa": "収束傾向を示しつつ、完全復旧の確認を続ける。",
    },
    {
        "term": "haven't seen any additional errors for ...",
        "meaningJa": "一定時間、追加のエラーが確認されていない",
        "usageExample": "We haven't seen any additional errors for 15 minutes.",
        "descriptionJa": "復旧判断の根拠となる無エラー時間を具体的に伝える。",
    },
    {
        "term": "keep an eye on ...",
        "meaningJa": "〜を引き続き注意して見る",
        "usageExample": "I'll keep an eye on the alert channel overnight.",
        "descriptionJa": "退勤前や深夜待機でも監視を継続することを宣言する。",
    },
    {
        "term": "keep a watch for future issues",
        "meaningJa": "今後の問題発生を注視する",
        "usageExample": "We can resolve the current alerts and keep a watch for future issues.",
        "descriptionJa": "課題の処理完了を告げつつ、経過観察を約束することを報告する。",
    },
    {
        "term": "continue to monitor for some more time",
        "meaningJa": "もうしばらく監視を続ける",
        "usageExample": "Things look stable, but I'll continue to monitor for some more time.",
        "descriptionJa": "安定傾向だが警戒を継続することを伝える。",
    },
    {
        "term": "things look good now",
        "meaningJa": "現状は良好で問題なさそうだ",
        "usageExample": "All services recovered, and things look good now.",
        "descriptionJa": "状況の正常化を伝える。",
    },
    {
        "term": "the service has restarted",
        "meaningJa": "サービスが再起動した",
        "usageExample": "The service has restarted and is accepting requests again.",
        "descriptionJa": "サービス再稼働の報告。",
    },
    {
        "term": "all services recovered",
        "meaningJa": "すべてのサービスが復旧した",
        "usageExample": "All services recovered at approximately 14:20.",
        "descriptionJa": "全体の復旧完了および時刻を報告する。",
    },
    {
        "term": "become available",
        "meaningJa": "利用可能状態に戻る",
        "usageExample": "The cache layer is becoming available again.",
        "descriptionJa": "全面回復前段階の段階的復旧を報告する。",
    },
    {
        "term": "error requests are dropping",
        "meaningJa": "エラーリクエストが減少している",
        "usageExample": "Error requests are dropping and successful requests are increasing.",
        "descriptionJa": "エラー減少と成功増加の傾向から指示。",
    },
    {
        "term": "usage dropped but is steadily increasing",
        "meaningJa": "使用量は一端下がったが徐々に増えている",
        "usageExample": "Usage dropped after the release but is steadily increasing again.",
        "descriptionJa": "一時的な急激な変化の後も動きを注視することを共有する。",
    },
    {
        "term": "full recovery",
        "meaningJa": "完全復旧",
        "usageExample": "It took approximately one hour from detection to full recovery.",
        "descriptionJa": "発生から全面回復までの所要時間を含めた完了報告。",
    },
    {
        "term": "mark it as resolved for now",
        "meaningJa": "一旦解決済みとする",
        "usageExample": "Since no new errors have appeared, I'll mark it as resolved for now.",
        "descriptionJa": "暫定対処後の経過観察中のステータスとして設定する。",
    },
    {
        "term": "once the root cause is identified",
        "meaningJa": "根本原因が特定されたら",
        "usageExample": "Once the root cause is identified, we can adjust the monitoring rules accordingly.",
        "descriptionJa": "原因解明後のアクション（例：監視ルールの調整）を約束する。",
    },
    {
        "term": "due to the maintenance",
        "meaningJa": "メンテナンスが原因で",
        "usageExample": "Some instances retained stale connections due to the maintenance.",
        "descriptionJa": "事前作業やメンテナンスに起因する事象であることを説明する。",
    },
    {
        "term": "be caused by ...",
        "meaningJa": "〜が原因で発生した",
        "usageExample": "The issue may have been caused by runtime optimization after the restart.",
        "descriptionJa": "再起動後の最適化（JIT等）や過負荷など原因を推測・分析する。",
    },
    {
        "term": "root cause analysis",
        "meaningJa": "根本原因分析",
        "usageExample": "Please include this finding in the root cause analysis.",
        "descriptionJa": "障害報告書（ポストモーテム等）の作成において根拠を残す。",
    },
    {
        "term": "take a closer look at ...",
        "meaningJa": "〜をさらに詳しく調べる",
        "usageExample": "We need to take a closer look at the affected sessions.",
        "descriptionJa": "通常調査では判明しない場合、個別・詳細調査を行う。",
    },
    {
        "term": "next actions",
        "meaningJa": "次に実施する対応",
        "usageExample": "Next actions: quantify the impact, improve monitoring, and document the timeline.",
        "descriptionJa": "復旧後・事後対応のアクションとして記載する。",
    },
    {
        "term": "preventive measures",
        "meaningJa": "再発防止策",
        "usageExample": "We need to document the cause and preventive measures.",
        "descriptionJa": "同じ障害の再発を防ぐ仕組みやプロセス改善を提案する。",
    },
    {
        "term": "review in depth",
        "meaningJa": "前提に掘り下げてレビューする",
        "usageExample": "The capacity assumptions should be reviewed in depth.",
        "descriptionJa": "表面的な確認ではなく、設計・計画レベルまで深掘りして検証する。",
    },
    {
        "term": "define the response procedure and decision criteria",
        "meaningJa": "対応手順と判断基準を定義する",
        "usageExample": "We should define the response procedure and decision criteria before the next incident.",
        "descriptionJa": "過去の経験を基に運用・ロールバック・復旧を判断するルールを文書化する。",
    },
    {
        "term": "recover more quickly if a similar issue occurs again",
        "meaningJa": "同様の問題が再発した際に、より急速に復旧する",
        "usageExample": "These changes should help us recover more quickly if a similar issue occurs again.",
        "descriptionJa": "再発防止だけでなく、再発時の復旧時間短縮を目標として述べる。",
    },
]
