"""User-provided Management vocabulary fields (100 entries)."""

USER_ENTRIES: list[dict] = [
    {
        "term": "raise awareness",
        "meaningJa": "依存関係についての認識を高める",
        "usageExample": "I'd like to raise awareness of the dependency before we commit to the timeline.",
        "descriptionJa": "チームメンバーに依存関係の重要性を共有し、責任を果たす重要性を共有する表現。",
    },
    {
        "term": "get everyone on the same page",
        "meaningJa": "全員の認識を揃える",
        "usageExample": "Let's get everyone on the same page before we assign owners.",
        "descriptionJa": "メンバー間で齟齬をなくすために投稿された文章。",
    },
    {
        "term": "tackle different aspects of the same problem",
        "meaningJa": "同じ問題の異なる側面に取り組む",
        "usageExample": "The two groups are tackling different aspects of the same problem, so we should coordinate their work.",
        "descriptionJa": "独立した2つのグループが同一課題の別側面を扱っていると指摘し、連携を促す時に使用。",
    },
    {
        "term": "simplify the participation of",
        "meaningJa": "〜の関与の簡素化を図る",
        "usageExample": "For the pilot, let's simplify the participation of the central review teams.",
        "descriptionJa": "初回検証で中央のプロセスや手続きを必要最小限にし、進行を容易にするときに使う。",
    },
    {
        "term": "figure out the details later",
        "meaningJa": "詳細の議論は後回しにする",
        "usageExample": "Let's agree on the direction now and figure out the details later.",
        "descriptionJa": "朝令暮改で前提に捉われず、まず方針決定を優先したいときに使う。",
    },
    {
        "term": "come back to this once we have an alpha version",
        "meaningJa": "アルファ版ができたらこの点に戻る",
        "usageExample": "Let's come back to the governance model once we have an alpha version.",
        "descriptionJa": "プロトタイプやアルファ版で実際の検証を進め、具体的な判断を行う時に適した表現。",
    },
    {
        "term": "bring the topic to your attention",
        "meaningJa": "この話題に注目を向けてもらう、共有する",
        "usageExample": "I'd like to bring the staffing risk to your attention before the planning meeting.",
        "descriptionJa": "重要課題をエスカレーションするときに、余計な摩擦を生まない表現。",
    },
    {
        "term": "intervene as deemed needed",
        "meaningJa": "必要と判断した介入をする",
        "usageExample": "Please review the situation and intervene as deemed needed.",
        "descriptionJa": "相手の裁量を尊重しながら、必要に応じて適切な手助けや介入を要請するメッセージ。",
    },
    {
        "term": "increase the priority of",
        "meaningJa": "〜の優先度を上げる",
        "usageExample": "The recent incident increased the priority of our monitoring improvements.",
        "descriptionJa": "新しい事実やリスクを根拠に、優先順位を変更したことを説明する表現。",
    },
    {
        "term": "a safety net just in case",
        "meaningJa": "万一に備えた安全装置",
        "usageExample": "The second review is a safety net just in case the automated check misses something.",
        "descriptionJa": "主な手順の代替手段ではなく、免失時のバックアップ手段であることを説明する表現。",
    },
    {
        "term": "the primary ownership still lies in",
        "meaningJa": "一番の主導的な責任は引き続き〜にある",
        "usageExample": "The primary ownership still lies in the service team, even with central support.",
        "descriptionJa": "支援体制を設けても、最終的な自治責任が損なわれないことを確認するときに使う。",
    },
    {
        "term": "make sure they are aware of",
        "meaningJa": "〜を認識している状態にする",
        "usageExample": "Please make sure the reviewers are aware of the deadline and the remaining risk.",
        "descriptionJa": "単なる伝達ではなく、相手の理解まで想定した意識の向上に使う。",
    },
    {
        "term": "pay attention to",
        "meaningJa": "〜にご注意を払う",
        "usageExample": "We should pay attention to handoff delays during the next sprint.",
        "descriptionJa": "重点的に監視する項目を指示する際、幅広いマネジメント場面で使える表現。",
    },
    {
        "term": "park this topic for now",
        "meaningJa": "この話題はいったん保留にする",
        "usageExample": "Let's park this topic for now and return to the staffing decision.",
        "descriptionJa": "会議の脱線を手短に防ぎ、脱線を防いで議論を連れ戻す意志を示す。",
    },
    {
        "term": "the priority is to agree on the scope",
        "meaningJa": "優先すべきはスコープに合意することだ",
        "usageExample": "The priority is to agree on the scope before estimating delivery dates.",
        "descriptionJa": "作業時間と納期に合わせた全一の前に、概論を確定させるときに使う。",
    },
    {
        "term": "everything else can come later",
        "meaningJa": "それ以外は後回しでよい",
        "usageExample": "Let's establish ownership first; everything else can come later.",
        "descriptionJa": "最重要点と後回しで良い箇所を区別し、優先順位を明確にする表現。",
    },
    {
        "term": "with support from",
        "meaningJa": "〜の支援を受けながら",
        "usageExample": "One team will own the proposal, with support from the platform team.",
        "descriptionJa": "主体と支援を明確に区別し、役割分担を表すときに使う。",
    },
    {
        "term": "along with a brief explanation",
        "meaningJa": "簡単な説明を添えて",
        "usageExample": "Please list the risks along with a brief explanation of their impact.",
        "descriptionJa": "一言だけでなく、判定に必要な最小限の小文を添えたいときに便利。",
    },
    {
        "term": "ensure that requirements are covered",
        "meaningJa": "要件が網羅されていることを確認する",
        "usageExample": "The product manager should ensure that the key requirements are covered before approval.",
        "descriptionJa": "漏れが無いかのチェック責任の分担を、明確な報告課題として明示できる。",
    },
    {
        "term": "if applicable",
        "meaningJa": "該当する場合は",
        "usageExample": "Please involve Legal and Security, if applicable.",
        "descriptionJa": "全体に一律強要せず、条件に応じた適用を柔軟に示す表現。",
    },
    {
        "term": "in the long run",
        "meaningJa": "長目的には",
        "usageExample": "In the long run, each domain should have a clearly accountable owner.",
        "descriptionJa": "短期対策と比較して、将来の望ましい状態や設計方針を述べる時に使う。",
    },
    {
        "term": "question the need for",
        "meaningJa": "〜の必要性を問い直す",
        "usageExample": "Adding another approval step makes me question the need for a separate review board.",
        "descriptionJa": "段階を直接否定せず、その個所の必要性の検討を促す表現。",
    },
    {
        "term": "add one more layer to maintain",
        "meaningJa": "保守対象の層をもう一つ増やす",
        "usageExample": "A separate committee would add one more layer to maintain without clear benefits.",
        "descriptionJa": "組織の運用コストや継続的な複雑さを指摘するときに使える表現。",
    },
    {
        "term": "wonder if that's worth it",
        "meaningJa": "それに見合う価値があるか疑問に思う",
        "usageExample": "Given the location cost, I wonder if that's worth it for a temporary process.",
        "descriptionJa": "反対意見を確定させず、費用対効果の検討を提案するときに使う。",
    },
    {
        "term": "a lot of unknowns",
        "meaningJa": "不確実性が多い",
        "usageExample": "There are still a lot of unknowns, so the estimate should remain provisional.",
        "descriptionJa": "不確定要素を明確にし、確定的な見積もりを避ける時期に使える表現。",
    },
    {
        "term": "verify our assumptions",
        "meaningJa": "自分たちの前提を検証する",
        "usageExample": "We should verify our assumptions with users before scaling the solution.",
        "descriptionJa": "仮説ベースの意思決定で、次に確認すべきことを明確にする表現。",
    },
    {
        "term": "a lighter review process",
        "meaningJa": "より軽量なレビュープロセス",
        "usageExample": "For the experiment, a lighter review process may help us learn faster.",
        "descriptionJa": "品質基準を無造作に下げるのではなく、手軽に早期に合わせて学習を速くする考え方を示す。",
    },
    {
        "term": "favour time to market",
        "meaningJa": "市場投入までの軽さを優先する",
        "usageExample": "At this stage, we should favour time to market while keeping the critical controls.",
        "descriptionJa": "難易度段階で速度を優先する段階を、品質や統制とのトレードオフの中で説明できる。",
    },
    {
        "term": "once we get the desired traction",
        "meaningJa": "期待する手応え・支持が得られたら",
        "usageExample": "We can invest in a stricter process once we get the desired traction.",
        "descriptionJa": "面の対応だけでなく投資の判定を、次の投資・後回し化の条件として示すときに使う。",
    },
    {
        "term": "the associated challenges",
        "meaningJa": "それに伴う課題",
        "usageExample": "We must acknowledge the associated challenges before adopting the new operating model.",
        "descriptionJa": "面の対応だけでなくそれに付随する困難やリスクも含めて議論するときに使える。",
    },
    {
        "term": "won't be so straightforward",
        "meaningJa": "それほど直球にはいかない",
        "usageExample": "The re-architecture won't be so straightforward once more teams depend on the service.",
        "descriptionJa": "将来の構成変更をいかに不都合か、早期の問題を提示する表現。",
    },
    {
        "term": "deliver with quality and on time",
        "meaningJa": "品質を保ち、期限通りにお届けする",
        "usageExample": "Our goal is to deliver with quality and on time, without burning out the team.",
        "descriptionJa": "デリバリーの納得感を、品質と期限の両面から明確に示す表現。",
    },
    {
        "term": "a stricter process",
        "meaningJa": "より厳格なプロセス",
        "usageExample": "Once the service becomes business-critical, we will need a stricter process.",
        "descriptionJa": "事業のフェーズや重要性に応じて、徐々に厳格な統制アプローチを提言する。",
    },
    {
        "term": "start a discussion between",
        "meaningJa": "〜の間で議論を始める",
        "usageExample": "We need to start a discussion between Product, QA, and Engineering before the scope is finalized.",
        "descriptionJa": "開催条件を早めに提示、部門横断の対話を始めたいときに使う。",
    },
    {
        "term": "the appropriate team members",
        "meaningJa": "適切なチームメンバー",
        "usageExample": "Please make sure to include the appropriate team members for the security review.",
        "descriptionJa": "特定の人格に限定せず、チーム内に適切な役職の選出を依頼するときに使う。",
    },
    {
        "term": "one to follow up, the other to back up",
        "meaningJa": "一人がフォローし、もう一人が支援・代替する",
        "usageExample": "Let's assign two coordinators: one to follow up, the other to back up.",
        "descriptionJa": "主担当と副担当など、2名による役割の役割分担を、分かりやすく説明できる。",
    },
    {
        "term": "an early heads-up",
        "meaningJa": "事前の早めの案内",
        "usageExample": "This is an early heads-up that our capacity may drop next month.",
        "descriptionJa": "相手が事前に準備できるよう、予兆として情報を共有するときに使う。",
    },
    {
        "term": "although it is quite early",
        "meaningJa": "まだかなり早い段階ではあるが",
        "usageExample": "Although it is quite early, it would help to confirm the reviewer's availability.",
        "descriptionJa": "早めであることを断りつつ、先回りした準備や依頼を提案するときに使う。",
    },
    {
        "term": "complete the handover",
        "meaningJa": "引き継ぎを完了する",
        "usageExample": "Please complete the handover before the current owner goes on leave.",
        "descriptionJa": "概念的な引き継ぎの完了点まで明示し、抜け漏れを防ぐ表現。",
    },
    {
        "term": "confirm availability",
        "meaningJa": "対応可能な時間帯・合力を確認する",
        "usageExample": "Could you confirm your team's availability for the next milestone?",
        "descriptionJa": "人員割り当てスケジュールの前に、実際の対応可能性を確認するときに使う。",
    },
    {
        "term": "a development timeline",
        "meaningJa": "開発スケジュール",
        "usageExample": "We should not commit to a development timeline until the main dependencies are clear.",
        "descriptionJa": "依存関係が明らかになる前までの時期等、時期計画の要領で扱うときの表現。",
    },
    {
        "term": "have some bandwidth",
        "meaningJa": "対応する余力がある",
        "usageExample": "Let us know when your team will have some bandwidth for this work.",
        "descriptionJa": "単なる人手ではなく、実質的に新しい仕事を受け入れられる余力を尋ねる表現。",
    },
    {
        "term": "feel free to reach out to",
        "meaningJa": "遠慮なく〜に連絡する",
        "usageExample": "Feel free to reach out to the platform lead if you need help removing the blocker.",
        "descriptionJa": "相談のハードルを下げ、心理的負荷のハードルを下げる協調的な表現。",
    },
    {
        "term": "shift left",
        "meaningJa": "検討や検証を工程の早い段階に移行する",
        "usageExample": "Let's shift left and involve QA while the requirements are still flexible.",
        "descriptionJa": "レビュー、テスト、セキュリティ、関係者調整を早期化する方針を描く表現。",
    },
    {
        "term": "the timeline doesn't align with yours",
        "meaningJa": "そのスケジュールはあなたの予定と合わない",
        "usageExample": "If the platform timeline doesn't align with ours, we so need an interim option.",
        "descriptionJa": "進捗遅延や別チームの都合の乖離を認識し、代理策の必要性につなげられる。",
    },
    {
        "term": "due to a lack of resources",
        "meaningJa": "リソース不足のため",
        "usageExample": "The work was delayed due to a lack of resources in the owning team.",
        "descriptionJa": "個人ではなく、組織的にリソースが不足していることを客観的に説明する表現。",
    },
    {
        "term": "rely on the solution directly",
        "meaningJa": "その解決策を直接利用する",
        "usageExample": "Instead of building a temporary layer, we wanted to rely on the shared solution directly.",
        "descriptionJa": "迂回路対応を望まず、共通化に直接依存する選択をするときに使う。",
    },
    {
        "term": "check whether the team has the bandwidth",
        "meaningJa": "チームに対応余力があるかを確認する",
        "usageExample": "Could you check whether the team has the bandwidth to support the migration this quarter?",
        "descriptionJa": "仕事を割り当てる前にまず、相手チームの実質的なキャパシティを確認する慎重な表現。",
    },
    {
        "term": "address all stakeholder concerns",
        "meaningJa": "すべての関係者の懸念に対応する",
        "usageExample": "The proposal should address all stakeholder concerns before we seek approval.",
        "descriptionJa": "合意形成のために、各部門の懸念を適切に反映・解消する意図を表す。",
    },
    {
        "term": "not have the luxury of",
        "meaningJa": "〜できるほどの余裕がない",
        "usageExample": "We do not have the luxury of adding a dedicated coordinator this quarter.",
        "descriptionJa": "理想を追求できない現実的な理由を示し、現実的な代替案につなげる表現。",
    },
    {
        "term": "identify the functional owner",
        "meaningJa": "機能上の責任者を特定する",
        "usageExample": "Mapping each domain to a team will help us identify the functional owner.",
        "descriptionJa": "チーム全体ではなく、特定の機能領域の明確な責任者を明確にするときに使う。",
    },
    {
        "term": "for starters",
        "meaningJa": "まず手始めに",
        "usageExample": "For starters, let's document the current owners and open decisions.",
        "descriptionJa": "膨大なタスクを前に、最初の第一歩を示す表現。",
    },
    {
        "term": "just some ideas, not hard requirements",
        "meaningJa": "あくまでアイデアであり、厳格な要件ではない",
        "usageExample": "These are just some ideas, not hard requirements, so please challenge them.",
        "descriptionJa": "たたき台を提示し、相手が安心して修正意見を出せる雰囲気を作る。",
    },
    {
        "term": "highlight risk from a project execution angle",
        "meaningJa": "プロジェクト進行の観点からリスクを明確にする",
        "usageExample": "The weekly review should highlight risk from a project execution angle.",
        "descriptionJa": "技術的リスクだけでなく、依存関係、進捗状況などの運行リスクに重点を当てる表現。",
    },
    {
        "term": "get an overview of the ongoing work",
        "meaningJa": "進行中の作業の概要を把握する",
        "usageExample": "The dashboard should help managers get an overview of the ongoing work.",
        "descriptionJa": "詳細に踏み込みすぎず、マネージャーが全体の姿を見渡したい時に使う。",
    },
    {
        "term": "identify areas that need immediate attention",
        "meaningJa": "すぐに注意が必要な領域を特定する",
        "usageExample": "Use the review to identify areas that need immediate attention, especially unresolved blockers.",
        "descriptionJa": "業務の優先度の判断で、マネージャーの介入が必要な課題を見つけるときに向う。",
    },
    {
        "term": "visualise the remaining workload",
        "meaningJa": "残作業量を可視化する",
        "usageExample": "We need to visualise the remaining workload before accepting another project.",
        "descriptionJa": "感覚ではなく、視覚化で作業量を判断できる状況を作る。",
    },
    {
        "term": "estimate team bandwidth in the short and mid term",
        "meaningJa": "短期中期のチームの出力を見積もる",
        "usageExample": "Let's estimate team bandwidth in the short and mid term before changing the roadmap.",
        "descriptionJa": "直近だけでなく数ヶ月先も含めて、受け入れられる負荷を見積もるときに使う。",
    },
    {
        "term": "leverage automation",
        "meaningJa": "自動化を活用する",
        "usageExample": "We should leverage automation for status updates and keep human reviews focused on decisions.",
        "descriptionJa": "反復作業を自動化し、人間が判断に集中できる運用を提案するときに使う。",
    },
    {
        "term": "agree and clarify company-wide",
        "meaningJa": "全社的に合意し、明確にする",
        "usageExample": "We need to agree and clarify company-wide when an architecture review is required.",
        "descriptionJa": "特定チーム内だけでなく、会社全体の共通ルールにしたいときに使う。",
    },
    {
        "term": "a written trace we can refer to",
        "meaningJa": "後から参照できる書面の記録",
        "usageExample": "Please capture the decision in writing so we have a written trace we can refer to later.",
        "descriptionJa": "口頭合意で終わらせず、文章で記録を残し、後で実務上の参照物として提示する。",
    },
    {
        "term": "standardize the testing phases",
        "meaningJa": "テスト工程を標準化する",
        "usageExample": "We should standardize the testing phases, including their scope and owners.",
        "descriptionJa": "チームごとに異なる工程名、責任、成果物を共通化したいときの明確な表現。",
    },
    {
        "term": "before answering, let me share some assumptions",
        "meaningJa": "回答する前に、いくつか前提条件を共有する",
        "usageExample": "Before answering, let me share some assumptions about capacity and delivery risk.",
        "descriptionJa": "判断の前提条件を先に開示し、誤解によるすれ違いを防ぐ表現。",
    },
    {
        "term": "minimize the process changes",
        "meaningJa": "プロセス変更を最小限に抑える",
        "usageExample": "For this release, let's minimize the process changes and document the longer-term improvement.",
        "descriptionJa": "利用側の負担やリスクを懸念し、変更手順を必要最小限に抑えたい時に使う。",
    },
    {
        "term": "a huge shift",
        "meaningJa": "大幅な転換",
        "usageExample": "Moving to domain-based ownership would be a huge shift for several teams.",
        "descriptionJa": "単なる小修正ではなく、組織、思想、運用に広い影響があることを強調する。",
    },
    {
        "term": "keep in mind that a proper solution will be required",
        "meaningJa": "適切な恒久策が必要になることを頭に置く",
        "usageExample": "We can use the workaround now, keeping in mind that a proper solution will be required.",
        "descriptionJa": "暫定策で時間を稼ぎつつ、それを恒久化させない意識づけをする表現。",
    },
    {
        "term": "not a huge fan of",
        "meaningJa": "〜にはあまり乗り気ではない",
        "usageExample": "I'm not a huge fan of adding another approval without a clear risk reduction.",
        "descriptionJa": "完全拒否で波風を立てず、自分の懸念や不満を伝える角を立てない表現。",
    },
    {
        "term": "easier to monitor",
        "meaningJa": "監視しやすい",
        "usageExample": "A daytime rollout is easier to monitor and gives us more people to respond.",
        "descriptionJa": "段階的リリースや可視化を、問題発生時の早期対応の観点から推奨するときに使う。",
    },
    {
        "term": "treat all releases as equal",
        "meaningJa": "すべてのリレーを等しく扱う",
        "usageExample": "Until the classification is reliable, we should treat all releases as equal.",
        "descriptionJa": "例外的な扱いによる混乱を避け、一律の適用基準を適用するときに使う。",
    },
    {
        "term": "assign the same amount of attention",
        "meaningJa": "同じ程度の注意を向ける",
        "usageExample": "Critical handoffs should receive the same amount of attention across teams.",
        "descriptionJa": "案件ごとの偏りや不均衡を是正し、一律の決定基準を平等に考える指示。",
    },
    {
        "term": "not a bad thing",
        "meaningJa": "悪い話ではない、検討に値する",
        "usageExample": "A regular planning checkpoint is not a bad thing if we keep it lightweight.",
        "descriptionJa": "全面歓迎ではないものの、案の価値を認める控えめな肯定表現。",
    },
    {
        "term": "focus on applications first",
        "meaningJa": "まずアプリケーションに集中する",
        "usageExample": "The broader model matters, but I'd like to focus on applications first.",
        "descriptionJa": "全体構想に気を取られず、目の前の範囲に焦点を絞る指示。",
    },
    {
        "term": "provide time-limited access",
        "meaningJa": "期間限定アクセスを提供する",
        "usageExample": "We can provide time-limited access for exceptional operational work.",
        "descriptionJa": "恒久権限を避け、必要な期限だけ権限を与えるリスク軽減策を表明する。",
    },
    {
        "term": "consider this high priority",
        "meaningJa": "これを優先度が高いと判断する",
        "usageExample": "Because this affects several teams, I consider this high priority.",
        "descriptionJa": "影響範囲や緊急性を理由に、優先度の判断を明示するときに使う。",
    },
    {
        "term": "there is a concern regarding",
        "meaningJa": "〜について懸念がある",
        "usageExample": "There is a concern regarding the support capacity after launch.",
        "descriptionJa": "個人を論的にせず、検討すべき懸念事項を客観的に提示する表現。",
    },
    {
        "term": "save migration cost",
        "meaningJa": "移行コストを抑える",
        "usageExample": "A shared platform may cost more initially but save migration cost later.",
        "descriptionJa": "短期費用と長期費用のトレードオフを説明し、長期的投資を正当化するときに使う。",
    },
    {
        "term": "keep it simple for now",
        "meaningJa": "今段階ではシンプルにしておく",
        "usageExample": "Let's keep it simple for now and add controls as the process matures.",
        "descriptionJa": "初期バージョンで過剰設計を避け、段階的に進める方針を示す。",
    },
    {
        "term": "bare minimum documentation",
        "meaningJa": "必要最小限の文書",
        "usageExample": "We need bare minimum documentation before the pilot begins.",
        "descriptionJa": "ドキュメント作成の負担を軽減し、迅速な本番ラインへ進める方針を示す。",
    },
    {
        "term": "tackle both at the same time",
        "meaningJa": "二つを同時に処理する",
        "usageExample": "Given our current capacity, I am not sure we can tackle both at the same time.",
        "descriptionJa": "同時進行の懸念を示し、計画の絞り込みを提案するときに使う。",
    },
    {
        "term": "a requirement regarding the delivery timing",
        "meaningJa": "納期に関する要件",
        "usageExample": "Is there a firm requirement regarding the delivery timing, or can we adjust the quarter?",
        "descriptionJa": "納期の絶対性と柔軟性を確認し、計画の自由度を確保するときに使う。",
    },
    {
        "term": "prioritize user experience over security",
        "meaningJa": "セキュリティよりユーザー体験を優先する",
        "usageExample": "If we prioritize user experience over security, we should document the accepted risk.",
        "descriptionJa": "二つの価値のどちらを優先するか表明し、その裏に伴うリスクを認識させるときに使う。",
    },
    {
        "term": "keep in mind the risks",
        "meaningJa": "リスクを念頭に置く",
        "usageExample": "We can accept the workaround, but we should keep in mind the operational risks.",
        "descriptionJa": "割り切りを想定しつつ、見過ごしてはいけない課題を関係者に意識させる表現。",
    },
    {
        "term": "leave the final decisions to whoever implements this",
        "meaningJa": "最終判断は実装担当者に委ねる",
        "usageExample": "I can suggest a direction, but I'll leave the final decision to whoever implements this.",
        "descriptionJa": "権限と責任を実行者に委ね、現場の判断を尊重するときに使う。",
    },
    {
        "term": "broaden the topic",
        "meaningJa": "議論の対象を広げる",
        "usageExample": "Let me broaden the topic to include the support and compliance implications.",
        "descriptionJa": "単一の課題から関連領域へ視野を広げ、議論を深めたい時に使う。",
    },
    {
        "term": "give everyone a chance to participate",
        "meaningJa": "全員に参加の機会を与える",
        "usageExample": "I'll share the proposal in the wider channel to give everyone a chance to participate.",
        "descriptionJa": "透明性を確保し、関心の機会を公平に与える姿勢を示す。",
    },
    {
        "term": "suggest the following steps",
        "meaningJa": "以下のステップを提案する",
        "usageExample": "Given the open questions, allow me to suggest the following steps.",
        "descriptionJa": "議論が混迷している状況で、次の行動手順を具体的に提示する表現。",
    },
    {
        "term": "avoid putting everything on one person's shoulders",
        "meaningJa": "一人にすべてを背負わせるのを防ぐ",
        "usageExample": "We should split the roles to avoid putting everything on one person's shoulders.",
        "descriptionJa": "負荷の分散、属人化排除の観点から役割分担を促すときに使う。",
    },
    {
        "term": "count on you and your team",
        "meaningJa": "あなたとチームの支援をあてにする",
        "usageExample": "If infrastructure support is needed, may I count on you and your team?",
        "descriptionJa": "協力関係を直接確認し、支援のコミットメントを取り付ける表現。",
    },
    {
        "term": "see if it complies with",
        "meaningJa": "〜に適合するか確認する",
        "usageExample": "We should inform compliance about the plan and see if it complies with the policy.",
        "descriptionJa": "規定や方針への適合性を事前に確認したいときに使う。",
    },
    {
        "term": "make sure we have a scale-up plan",
        "meaningJa": "スケールアップ計画があることを確認する",
        "usageExample": "Please make sure we have a scale-up plan before the traffic peak.",
        "descriptionJa": "運用の増加時や急増を見越して、準備が整っているかを確認するときに使う。",
    },
    {
        "term": "in my stead",
        "meaningJa": "私の代わりに",
        "usageExample": "You have the full context, so I believe you can present it in my stead.",
        "descriptionJa": "自身が出席・対応できない場合に、代理で対応してもらうことを依頼する表現。",
    },
    {
        "term": "keep members informed",
        "meaningJa": "メンバーに随時情報共有する",
        "usageExample": "Please keep the affected numbers informed while the investigation continues.",
        "descriptionJa": "調査や対応の途中で、継続的に状況を共有することを約束・指示するときに使う。",
    },
    {
        "term": "secure resources to officially start the project",
        "meaningJa": "正式開始に必要なリソースを確保する",
        "usageExample": "We need to secure resources to officially start the project next quarter.",
        "descriptionJa": "アイデア段階から実行フェーズへ移行するための、人員や予算の確保を目的とする表現。",
    },
    {
        "term": "no need to hurry",
        "meaningJa": "急ぐ必要はない",
        "usageExample": "There is no need to hurry until the owner and funding are confirmed.",
        "descriptionJa": "無用な焦りを防ぎ、条件が整うまで適切なペースで進めるよう伝える。",
    },
    {
        "term": "for visibility",
        "meaningJa": "透明性・可視化のために",
        "usageExample": "I'm adding the support lead for visibility; no action is required yet.",
        "descriptionJa": "アクションを即座に要求するのではなく、認知や情報共有を目的として共有する時に使う。",
    },
    {
        "term": "my two cents on this",
        "meaningJa": "この件についての私の私見",
        "usageExample": "Just my two cents on this: keep the update concise and link to the detailed report.",
        "descriptionJa": "意見を述べる際、自分の意見を過度に主張せず控えめかつ建設的に申し出る表現。",
    },
    {
        "term": "concerned that it might look bloated",
        "meaningJa": "情報が多く見えすぎるのではと懸念する",
        "usageExample": "From a management view, I'm concerned that the weekly report might look bloated.",
        "descriptionJa": "内容の重複や肥大化を指摘し、可視性や会議の負担を低減させたい時に使う。",
    },
    {
        "term": "make upcoming changes more predictable and controlled",
        "meaningJa": "今後の変更予定を予測可能で管理されたものにする",
        "usageExample": "Standardizing release windows will make upcoming changes more predictable and controlled.",
        "descriptionJa": "プロセス化やチケット管理の目的を、安定や運用の予測可能性という文脈で説明する。",
    },
    {
        "term": "focus on technical sanity",
        "meaningJa": "技術的な健全性に重点を置く",
        "usageExample": "The engineering review should focus on technical sanity while the PM handles coordination.",
        "descriptionJa": "設計の課題や構成の妥当性、無理な実装ではないか技術的観点から検証と責任に集中するときに使う。",
    },
    {
        "term": "break it down into smaller PRs",
        "meaningJa": "より小さなPRに分割する",
        "usageExample": "To simplify review and risk, I'll break it down into smaller PRs with clear owners.",
        "descriptionJa": "大きな変更意図を小分けにし、レビュー、検証、リスク管理をしやすくする実践的な表現。",
    },
]
