"""User-provided Meetings / Events vocabulary fields (129 entries)."""

USER_ENTRIES: list[dict] = [
    {
        "term": "so far",
        "meaningJa": "これまでのところ、今のところ",
        "usageExample": "So far, we haven't seen any critical issues.",
        "descriptionJa": "現時点で確認されている状況や進捗を共有する際に使う。",
    },
    {
        "term": "still no update",
        "meaningJa": "まだ更新・進展がない",
        "usageExample": "Still no update from the platform team.",
        "descriptionJa": "待っている報告や作業に進展がないことを率直に伝える表現。",
    },
    {
        "term": "not something unexpected",
        "meaningJa": "想定外のことではない",
        "usageExample": "The delayed response is not something unexpected.",
        "descriptionJa": "問題に見える現象が想定・既知のものであると説明する表現。",
    },
    {
        "term": "first of all",
        "meaningJa": "まずはじめに",
        "usageExample": "First of all, let me explain the current behavior.",
        "descriptionJa": "議論や報告の導入部として最初に話すトピックを明確にする。",
    },
    {
        "term": "provide a diagram to support the discussion",
        "meaningJa": "議論を補助する図を提供する",
        "usageExample": "I'll provide a diagram to support the discussion.",
        "descriptionJa": "構成図やフロー図などを提示して説明を補足すると伝える便利な表現。",
    },
    {
        "term": "in the middle of",
        "meaningJa": "〜の最中で、〜に取り組んでいる最中で",
        "usageExample": "I'm in the middle of updating the design document.",
        "descriptionJa": "作業が進行中であり、まだ完了していない状態を表す。",
    },
    {
        "term": "move on to",
        "meaningJa": "次のトピックへ進む",
        "usageExample": "Once the design is approved, we'll move on to implementation.",
        "descriptionJa": "議題や作業のフェーズを次へ進めるときに使う指示語。",
    },
    {
        "term": "regarding",
        "meaningJa": "〜に関して",
        "usageExample": "Regarding the rollout, we still need final approval.",
        "descriptionJa": "特定のトピックを切り出して言及するときに使うフォーマルな表現。",
    },
    {
        "term": "if I'm not mistaken",
        "meaningJa": "私の勘違いでなければ",
        "usageExample": "If I'm not mistaken, this change affects two endpoints.",
        "descriptionJa": "記憶や情報に少し不確実性を持たせながら確認を促す口語的な表現。",
    },
    {
        "term": "need to confirm",
        "meaningJa": "確認する必要がある",
        "usageExample": "I need to confirm the exact scope with the backend team.",
        "descriptionJa": "その場では確定できず、追加確認が必要だと伝える際に使える。",
    },
    {
        "term": "at the moment",
        "meaningJa": "現時点では",
        "usageExample": "At the moment, the task is blocked by an external dependency.",
        "descriptionJa": "現在の暫定的な状況を説明し、将来変わり得る含みを持たせる。",
    },
    {
        "term": "we concluded that",
        "meaningJa": "〜という結論に至った",
        "usageExample": "We concluded that the existing approach is sufficient for now.",
        "descriptionJa": "議論の結論として合意した内容を発表するときに使う。",
    },
    {
        "term": "the reason is because",
        "meaningJa": "その理由は〜だからです",
        "usageExample": "The reason is because the environment is shared with other teams.",
        "descriptionJa": "理由や背景の骨組みを明確にする句で自発的に説明を開始。",
    },
    {
        "term": "ready to release",
        "meaningJa": "リリース準備ができている",
        "usageExample": "Once QA signs off, we'll be ready to release.",
        "descriptionJa": "テストや準備が終わり、リリース可能な状態を示す。",
    },
    {
        "term": "plan out",
        "meaningJa": "具体的に計画する、段取りを組み立てる",
        "usageExample": "We need to plan out which scenarios to include.",
        "descriptionJa": "大まかだけでなく、対策や順番も含めて具体化するときに使う表現。",
    },
    {
        "term": "gradually",
        "meaningJa": "徐々に、段階的に",
        "usageExample": "We'll add the remaining scenarios gradually.",
        "descriptionJa": "一度に行わず段階的、あるいは順調に増やす方針を表す。",
    },
    {
        "term": "from what I understand",
        "meaningJa": "私の理解では",
        "usageExample": "From what I understand, the schema is generated automatically.",
        "descriptionJa": "自分の理解を提示しつつ、相手に訂正の余地を残す丁寧な表現。",
    },
    {
        "term": "in the first place",
        "meaningJa": "そもそも、第一に",
        "usageExample": "In the first place, we need to agree on the ownership.",
        "descriptionJa": "議論の前提や根本的な要因に立ち返るときに使う。",
    },
    {
        "term": "I was wondering if",
        "meaningJa": "〜ではないかと思っていました、〜か伺いたいです",
        "usageExample": "I was wondering if we could automate this check.",
        "descriptionJa": "控えめな提案や質疑応答のための切り出し表現。",
    },
    {
        "term": "I'm not sure how it works",
        "meaningJa": "どう動くのかよく分かりません",
        "usageExample": "I'm not sure how it works under heavy load.",
        "descriptionJa": "仕様や動作の細部が不明で、追加調査が必要だと伝える。",
    },
    {
        "term": "as long as",
        "meaningJa": "〜である限り、〜さえすれば",
        "usageExample": "As long as the contract stays stable, this approach should work.",
        "descriptionJa": "前提条件・保証の成立条件を提示する際に重宝する。",
    },
    {
        "term": "worth looking into",
        "meaningJa": "調べる価値がある",
        "usageExample": "The open-source tool is worth looking into.",
        "descriptionJa": "有益である可能性が高く、調査対象とする価値を言及する際に使う。",
    },
    {
        "term": "as time passes",
        "meaningJa": "時間がたつにつれて",
        "usageExample": "As time passes, more services will adopt the new protocol.",
        "descriptionJa": "中長期的な変化や見通しを表現するときに使う。",
    },
    {
        "term": "bring up one last topic",
        "meaningJa": "最後にもう一つ話題を出す",
        "usageExample": "I'd like to bring up one last topic before we finish.",
        "descriptionJa": "会議やアジェンダの最後に、明確に差し込む打診表現。",
    },
    {
        "term": "before we close",
        "meaningJa": "会議を終える前に",
        "usageExample": "Before we close, let's confirm the action items.",
        "descriptionJa": "終了前の最後の確認や発言を促す際に非常に便利。",
    },
    {
        "term": "what do you guys think?",
        "meaningJa": "皆さんはどう思いますか？",
        "usageExample": "What do you guys think about reusing the same token?",
        "descriptionJa": "チーム全体から率直な意見を募る、口語的で自然な表現。",
    },
    {
        "term": "think otherwise",
        "meaningJa": "別の考えを持つ、異なる見方をする",
        "usageExample": "Does anyone think otherwise?",
        "descriptionJa": "反対意見や異論がないか軽く確認する表現。",
    },
    {
        "term": "what I'm about to mention",
        "meaningJa": "これから私が話そうとしていること",
        "usageExample": "This is related to what I'm about to mention.",
        "descriptionJa": "相手の要望を受け、これから説明する内容に繋げる発言。",
    },
    {
        "term": "according to the needs",
        "meaningJa": "必要に応じて",
        "usageExample": "We can create the endpoints according to the needs of each client.",
        "descriptionJa": "一律ではなく、要件別に判断・分割することを表示。",
    },
    {
        "term": "that being said",
        "meaningJa": "そうは言っても、それをふまえると",
        "usageExample": "That being said, we still need a fallback plan.",
        "descriptionJa": "直前の内容を認めつつ、条件や例外の補足を付け加える表現。",
    },
    {
        "term": "separate the concerns",
        "meaningJa": "関心事・責任・役割を分離する",
        "usageExample": "Moving only the sensitive endpoints helps us separate the concerns.",
        "descriptionJa": "設計上の役割や責務を切り分ける方針を説明する重要領域。",
    },
    {
        "term": "what I have in mind",
        "meaningJa": "私が考えている事、私のイメージ",
        "usageExample": "Let me explain what I have in mind.",
        "descriptionJa": "まだ確定・起草していない自分のアイディアを共有するときに使う。",
    },
    {
        "term": "worth considering",
        "meaningJa": "検討する価値がある",
        "usageExample": "If the performance gain is significant, it's worth considering.",
        "descriptionJa": "条件付きで検討を進めるメリット・余地があることを示す。",
    },
    {
        "term": "that's a really good question",
        "meaningJa": "それはとても良い質問ですね",
        "usageExample": "That's a really good question; let me check the dependency.",
        "descriptionJa": "質問の重要性を認め、前向きに答える好感度な返事。",
    },
    {
        "term": "just ping me",
        "meaningJa": "気軽に連絡してください",
        "usageExample": "If you need the configuration, just ping me.",
        "descriptionJa": "チャットで簡潔に連絡してほしいと伝えるカジュアルな文脈。",
    },
    {
        "term": "I plan to raise the topic",
        "meaningJa": "その話題を取り上げる予定です",
        "usageExample": "I plan to raise the topic at the next platform meeting.",
        "descriptionJa": "別の会議や議場へ議題を持ち込む予定を伝える。",
    },
    {
        "term": "in order for that to happen",
        "meaningJa": "それを実現するためには",
        "usageExample": "In order for that to happen, we need a network rule change.",
        "descriptionJa": "目標達成に必要な前提条件や前作業を説明する際に動く。",
    },
    {
        "term": "next up",
        "meaningJa": "次は、続いて",
        "usageExample": "Next up, let's review the deployment status.",
        "descriptionJa": "次のアジェンダやヘンジポックへ進む指示語。",
    },
    {
        "term": "before that",
        "meaningJa": "その前に",
        "usageExample": "Before that, does anyone have a question?",
        "descriptionJa": "予定した作業に入る前、点検や確認を促したいときに重宝。",
    },
    {
        "term": "briefly translate",
        "meaningJa": "手短に翻訳する",
        "usageExample": "Let me briefly translate that into Japanese.",
        "descriptionJa": "会議での通訳・要約時の前置きとして有用。",
    },
    {
        "term": "go with that approach",
        "meaningJa": "その方針で進める",
        "usageExample": "If we go with that approach, we'll need an extra check.",
        "descriptionJa": "提案された案を採用する場合の影響を指示する時に。",
    },
    {
        "term": "think what to do if",
        "meaningJa": "もし〜ならどうするか考える",
        "usageExample": "We need to think what to do if the dependency fails.",
        "descriptionJa": "エラーケースや例外処理の設計方針を述べる際の一言。",
    },
    {
        "term": "in that case",
        "meaningJa": "その場合は",
        "usageExample": "In that case, we should reuse the existing resource.",
        "descriptionJa": "条件や前提を踏まえて、次の判断を示す接続表現。",
    },
    {
        "term": "just reiterating",
        "meaningJa": "繰り返し確認すると、要点を言い換えると",
        "usageExample": "So basically, this is like the whole so is just reiterating.",
        "descriptionJa": "議論の要点や重要数値・設定をもう一度明確にする際に使う。",
    },
    {
        "term": "keep an eye on",
        "meaningJa": "〜を注視しておく、監視する",
        "usageExample": "Please keep an eye on any delete operations in the plan.",
        "descriptionJa": "リスクのある現象を継続的に確認して注視するよう促す。",
    },
    {
        "term": "we've got to be cautious",
        "meaningJa": "注意しなければならない",
        "usageExample": "If the plan deletes a resource, we've got to be cautious.",
        "descriptionJa": "意図しない削除など、慎重を要する変更に対して注意を喚起する。",
    },
    {
        "term": "one way is to",
        "meaningJa": "一つの方法は〜することです",
        "usageExample": "One way is to check the existing configuration first.",
        "descriptionJa": "解決策の一つを例示し、選択肢を提示するときに便利。",
    },
    {
        "term": "out of office",
        "meaningJa": "不在、休職中",
        "usageExample": "Several team members are out of office today.",
        "descriptionJa": "開発者の欠席や、勤務状態（OOO）を伝える。",
    },
    {
        "term": "does anyone have any updates they'd like to talk about?",
        "meaningJa": "何か共有したい進捗はありますか？",
        "usageExample": "Does anyone have any updates they'd like to talk about in this meeting?",
        "descriptionJa": "朝会や進捗会で参加者に自発的な発言を促す定番フレーズ。",
    },
    {
        "term": "sounds like we can probably skip",
        "meaningJa": "どうやら省略・スキップしてよさそうです",
        "usageExample": "Sounds like we can probably skip this section today.",
        "descriptionJa": "議題に特記事項がなく、時間を節約するため飛ばす提案。",
    },
    {
        "term": "unless there are any objections",
        "meaningJa": "異論がなければ",
        "usageExample": "Unless there are any objections, we'll proceed with this plan.",
        "descriptionJa": "反対意見や懸念の有無を確かめた上で進める確認の決め台詞。",
    },
    {
        "term": "I agree with you",
        "meaningJa": "あなたに同意します",
        "usageExample": "I agree with you; the simpler option is safer.",
        "descriptionJa": "他者の提案や指摘への明快な同意を表す。",
    },
    {
        "term": "talk to you later",
        "meaningJa": "また後で話し合いましょう",
        "usageExample": "You guys can talk later or next week – I'll talk to you later.",
        "descriptionJa": "短い会話や議論を終える際にとる着地的な表現。",
    },
    {
        "term": "roughly estimate how long it would take",
        "meaningJa": "どのくらいかかるか概算する",
        "usageExample": "Could you roughly estimate how long it would take to fix?",
        "descriptionJa": "正確な工数ではなく、大体の見通しを要求するときに使う。",
    },
    {
        "term": "by next week",
        "meaningJa": "来週までに",
        "usageExample": "I hope to resolve the issue by next week.",
        "descriptionJa": "期限を設定・受託するときに使う。",
    },
    {
        "term": "get the root cause",
        "meaningJa": "根本原因を突き止める",
        "usageExample": "I'll try to get the root cause early next week.",
        "descriptionJa": "単なる表面上の解決ではなく根本調査を行う意思表明。",
    },
    {
        "term": "if anything",
        "meaningJa": "何かあれば、必要なら",
        "usageExample": "If anything changes, you can discuss the progress directly.",
        "descriptionJa": "状況に変化が生じた場合の対応をあらかじめ教える。",
    },
    {
        "term": "share briefly",
        "meaningJa": "簡潔に共有する",
        "usageExample": "I'll share briefly about the investigation.",
        "descriptionJa": "長くならないよう要点だけ要約説明する前置き。",
    },
    {
        "term": "find out how",
        "meaningJa": "どうすればよいか調べる",
        "usageExample": "We need to find out how to retrieve older logs.",
        "descriptionJa": "方法が未定で、調査が必要であることを示す。",
    },
    {
        "term": "if we were to",
        "meaningJa": "仮に私たちが〜するとしたら",
        "usageExample": "If we were to investigate older data, we'd need another storage layer.",
        "descriptionJa": "仮定のシナリオを置いて、想定される影響や追加要件を議論する。",
    },
    {
        "term": "do you have anything else you'd like to share?",
        "meaningJa": "ほかに共有したいことはありますか？",
        "usageExample": "Before we move on, do you have anything else you'd like to share?",
        "descriptionJa": "発言を締めくくる前、または別の人へ振る際の確認。",
    },
    {
        "term": "as soon as possible",
        "meaningJa": "できるだけ早く",
        "usageExample": "We need to release the fix as soon as possible.",
        "descriptionJa": "優先度が高く、緊急対応を要する事態を示す表現。",
    },
    {
        "term": "as you all know",
        "meaningJa": "皆さんご存じのとおり",
        "usageExample": "As you all know, we changed the session validation flow.",
        "descriptionJa": "既に共有済みの情報を前提として、話を展開する際に使用。",
    },
    {
        "term": "currently working on",
        "meaningJa": "現在〜に取り組んでいる",
        "usageExample": "I'm currently working on the fallback implementation.",
        "descriptionJa": "現在進行中の具体的な作業内容を共有する基本表現。",
    },
    {
        "term": "do you happen to know",
        "meaningJa": "もしかしてご存じですか？",
        "usageExample": "Do you happen to know why this request fails?",
        "descriptionJa": "相手が情報を持っているか明確ではないが尋ねてみたいときの丁寧な言い方。",
    },
    {
        "term": "take this to Slack later",
        "meaningJa": "この話は後でSlackで話す",
        "usageExample": "We'll take this item to Slack later for further discussion.",
        "descriptionJa": "会議時間内で解決し切れない議論をチャットへ逃がす標準。",
    },
    {
        "term": "get back to",
        "meaningJa": "〜に戻る、改めて対応する",
        "usageExample": "Once this is done, I'll get back to the security task.",
        "descriptionJa": "中断していた本来の作業や議論へ戻る際に使える。",
    },
    {
        "term": "put on hold",
        "meaningJa": "保留にする、保留中である",
        "usageExample": "I put the refactoring work on hold to handle a production issue.",
        "descriptionJa": "優先度の関係で作業を一時中断している状態を説明。",
    },
    {
        "term": "higher-priority tickets",
        "meaningJa": "優先度が高いチケット",
        "usageExample": "I had to deal with a few higher-priority tickets first.",
        "descriptionJa": "他の重要な課題対応が発生したことを理由として提示する際。",
    },
    {
        "term": "as far as I could tell",
        "meaningJa": "私が確認できた限りでは",
        "usageExample": "As far as I could tell, there's no technical blocker.",
        "descriptionJa": "自身の調査範囲に限定して判断結果を共有する表現。",
    },
    {
        "term": "as I mentioned",
        "meaningJa": "先述した通り、前述したように",
        "usageExample": "As I mentioned, the KC auth is not the source of truth.",
        "descriptionJa": "すでに述べた要点を繰り返して強調する時に使う。",
    },
    {
        "term": "instead of what I proposed",
        "meaningJa": "私が提案した内容の代わりに",
        "usageExample": "Could we retry the request instead of what I proposed?",
        "descriptionJa": "自身の案と比較し、別の代案を検討・比較する際に使用。",
    },
    {
        "term": "source of truth",
        "meaningJa": "正確な情報源、信頼できる基本データ",
        "usageExample": "The database remains the source of truth.",
        "descriptionJa": "システム間でデータ乖離が生じる際、真のデータ保持側がどれか示す基本用語。",
    },
    {
        "term": "make a final decision",
        "meaningJa": "最終判断を下す",
        "usageExample": "Let's collect the metrics before we make a final decision.",
        "descriptionJa": "最終決定を行うステップであることを指す。",
    },
    {
        "term": "side note",
        "meaningJa": "補足ですが、余談ですが",
        "usageExample": "Side note: the service has a 99.99% availability target.",
        "descriptionJa": "主題とは直接関係ないが、関連する補足情報を添える会話。",
    },
    {
        "term": "we could do that too",
        "meaningJa": "それも可能ですが、それも可能ではあります",
        "usageExample": "We could do that too, but it would add operational overhead.",
        "descriptionJa": "相手の提案を可能と認めつつも、コストなどの理由で積極的にお勧めしない。",
    },
    {
        "term": "as much as possible",
        "meaningJa": "できる限り",
        "usageExample": "We want to avoid unnecessary exceptions as much as possible.",
        "descriptionJa": "最大限回避・努力する方針を明示する表現。",
    },
    {
        "term": "Given all that",
        "meaningJa": "以上を踏まえると",
        "usageExample": "Given all that, I think the fallback is justified.",
        "descriptionJa": "前述の諸条件・背景を考慮した結論へ移行する指示語。",
    },
    {
        "term": "I would prefer it that way",
        "meaningJa": "私はそのやり方を論じたいです",
        "usageExample": "If we can handle it internally, I would prefer it that way.",
        "descriptionJa": "複数の選択肢の中で、自分の望ましい選択肢を明確に述べる。",
    },
    {
        "term": "if there's no solution",
        "meaningJa": "解決策がなければ",
        "usageExample": "If there's no solution, we'll return an error to the client.",
        "descriptionJa": "代替手段が尽きた場合のフォールバック処理を規定する。",
    },
    {
        "term": "proceed with",
        "meaningJa": "〜を進める、〜に移る",
        "usageExample": "If frontend agrees, we'll proceed with the fallback.",
        "descriptionJa": "合意後に実際に作業や処理を実行する段階で使う。",
    },
    {
        "term": "quick update",
        "meaningJa": "手短な進捗報告",
        "usageExample": "A quick update: the dashboard is ready in development.",
        "descriptionJa": "長い報告ではなく、手短に要点を共有するための前置き。",
    },
    {
        "term": "hopefully by the end of today",
        "meaningJa": "うまくいけば今日中に",
        "usageExample": "Hopefully, we can finish the alert setup by the end of today.",
        "descriptionJa": "確約ではないが、目標とする完了タイミングを伝える。",
    },
    {
        "term": "that's all from me",
        "meaningJa": "私からは以上です",
        "usageExample": "That's all from me. Let's move to the next update.",
        "descriptionJa": "発言・報告の終わりを告げ、次の発表者へ渡す合図。",
    },
    {
        "term": "if there is an alternative",
        "meaningJa": "代替案があるなら",
        "usageExample": "If there is an alternative, it would be great to compare it.",
        "descriptionJa": "現在の案以外に選択肢があるか尋ねる表現。",
    },
    {
        "term": "let's wrap things up here",
        "meaningJa": "ここで区切りにしましょう",
        "usageExample": "It's almost noon, so let's wrap things up here.",
        "descriptionJa": "時間切れや区切りの良いところで会議を締めくくる表現。",
    },
    {
        "term": "is English okay with you?",
        "meaningJa": "英語で大丈夫ですか？",
        "usageExample": "Before we start, is English okay with you?",
        "descriptionJa": "相手の使用言語を確認し、英語で進行する意思を示す。",
    },
    {
        "term": "that's fine too",
        "meaningJa": "それでも構いません、それも大丈夫です",
        "usageExample": "If you'd rather discuss it next week, that's fine too.",
        "descriptionJa": "相手の提案や選択を受け入れる、柔軟さを示す表現。",
    },
    {
        "term": "looking into",
        "meaningJa": "調査している、検討している",
        "usageExample": "I'm looking into the new deployment approach.",
        "descriptionJa": "課題や新技術の調査を進行させている状況を表す。",
    },
    {
        "term": "give that a try",
        "meaningJa": "それを試してみる",
        "usageExample": "Let's give that a try for one sprint.",
        "descriptionJa": "提案や技術を試験的に導入してみる時に使う。",
    },
    {
        "term": "if it's too complicated",
        "meaningJa": "もし複雑すぎるなら",
        "usageExample": "If it's too complicated, we can use the current process.",
        "descriptionJa": "導入コストが高い場合の安全策や別方針へ促す。",
    },
    {
        "term": "just fyi",
        "meaningJa": "念のための共有ですが",
        "usageExample": "Just FYI, the release window is in March.",
        "descriptionJa": "返信を求めない、参考情報の共有として便利。",
    },
    {
        "term": "straightforward",
        "meaningJa": "シンプルでわかりやすい、直接的",
        "usageExample": "It's straightforward when both services use the same approach.",
        "descriptionJa": "実装や設定が複雑でなく、扱いやすいことを評価する表現。",
    },
    {
        "term": "an important point",
        "meaningJa": "重要な点",
        "usageExample": "This is an important point we should capture in the design.",
        "descriptionJa": "議論の中で見落とせない重要ポイントを強調して伝える。",
    },
    {
        "term": "a more conservative approach",
        "meaningJa": "より慎重な方法",
        "usageExample": "A more conservative approach is to keep both options for now.",
        "descriptionJa": "リスクを抑えた安全側の選択肢を提示するときに使う。",
    },
    {
        "term": "it depends on",
        "meaningJa": "〜による、〜次第だ",
        "usageExample": "It depends on what we learn from the trial.",
        "descriptionJa": "結果や要件が他の要素に依存して決定することを示す。",
    },
    {
        "term": "in terms of",
        "meaningJa": "〜の観点では、〜に関しては",
        "usageExample": "In terms of deployment, we should be consistent.",
        "descriptionJa": "特定の観点やテーマに絞って判断や意見を述べる。",
    },
    {
        "term": "in advance",
        "meaningJa": "あらかじめ、事前に",
        "usageExample": "I'll prepare the required dependencies in advance.",
        "descriptionJa": "前もって進めておく作業や準備事項を伝える。",
    },
    {
        "term": "assign this to someone else",
        "meaningJa": "これを他の人に割り当てる",
        "usageExample": "Since you are occupied, I'll assign this to someone else.",
        "descriptionJa": "タスクの負荷分散や担当変更を行う際の表現。",
    },
    {
        "term": "no dedicated",
        "meaningJa": "専用のものが存在しない",
        "usageExample": "Currently, no dedicated environment exists yet.",
        "descriptionJa": "特定用途に特化した環境やリソースがない現状を報告する。",
    },
    {
        "term": "take a look at",
        "meaningJa": "〜を確認する、〜を見る",
        "usageExample": "Let's take a look at the logs after this meeting.",
        "descriptionJa": "ログや資料などの確認・チェックを提案する表現。",
    },
    {
        "term": "it would be great if",
        "meaningJa": "〜していただけると助かります、〜だとありがたいです",
        "usageExample": "It would be great if you could provide a diagram.",
        "descriptionJa": "相手に資料の提示や協力を依頼する際の丁寧な表現。",
    },
    {
        "term": "pick up",
        "meaningJa": "（タスクなどを）着手する、取り上げる",
        "usageExample": "I can pick up this testing task next sprint.",
        "descriptionJa": "優先度リスト等からタスクを拾って担当・着手すること。",
    },
    {
        "term": "comments so far?",
        "meaningJa": "ここまでに質問やコメントはありますか？",
        "usageExample": "Do you have any questions or comments so far?",
        "descriptionJa": "報告の途中で参加者の理解や疑問を確認するフレーズ。",
    },
    {
        "term": "one thing, and the other thing is",
        "meaningJa": "一つ目は〜で、もう一つは〜です",
        "usageExample": "One thing is the cost, and the other thing is maintenance.",
        "descriptionJa": "伝えたいポイントが2点あることをあらかじめ整理して話す構成。",
    },
    {
        "term": "from what I could find out",
        "meaningJa": "私が調べられた範囲では",
        "usageExample": "From what I could find out, the tool supports contract testing.",
        "descriptionJa": "調査結果を報告する際、調べた限界を前提として示す表現。",
    },
    {
        "term": "the only difference is",
        "meaningJa": "唯一の違いは〜です",
        "usageExample": "The only difference is how the token is validated.",
        "descriptionJa": "2つの案や仕様を比較し、相違点をピンポイントで指摘する。",
    },
    {
        "term": "sounds good",
        "meaningJa": "よさそうです、それで進めましょう",
        "usageExample": "Sounds good; let me proceed with the simpler option.",
        "descriptionJa": "提案や回答に対して同意・賛同を示す軽快な返答。",
    },
    {
        "term": "do the heavy lifting",
        "meaningJa": "負担の大きい作業を担当する",
        "usageExample": "We can let the base framework do the heavy lifting.",
        "descriptionJa": "処理や作業の大半を担うフレームワーク・仕組みに委ねる比喩表現。",
    },
    {
        "term": "take a look at that when the time comes",
        "meaningJa": "その時が来たら確認する・対応する",
        "usageExample": "We will take a look at that when the time comes.",
        "descriptionJa": "今すぐ決める必要がなく、段階が進んでから対処する方針を示す。",
    },
    {
        "term": "split things up",
        "meaningJa": "作業や品目を分割する・切り分ける",
        "usageExample": "Let's split things up so we can work in parallel.",
        "descriptionJa": "複雑なタスクや巨大な変更を細分化し、手分けして進める。",
    },
    {
        "term": "take over",
        "meaningJa": "担当を引き継ぐ",
        "usageExample": "Another engineer will take over while she is away.",
        "descriptionJa": "担当者の移動や休暇に伴い、別のメンバーが仕事を引き継ぐ。",
    },
    {
        "term": "good to know",
        "meaningJa": "それを知ることができてよかった、参考になります",
        "usageExample": "Good to know. I'll update the ownership list.",
        "descriptionJa": "相手の情報提供に対して感謝を示しつつ、有益であったと伝える返答。",
    },
    {
        "term": "on my side",
        "meaningJa": "私の側では、私の担当範囲については",
        "usageExample": "On my side, the implementation is complete.",
        "descriptionJa": "自分の担当範囲やチーム側の状況を切り出して報告する基本表現。",
    },
    {
        "term": "my thought process was",
        "meaningJa": "私の考え方・判断過程としては",
        "usageExample": "My thought process was that we could reuse the existing setup.",
        "descriptionJa": "なぜその設計や提案に至ったか、思考の過程や理由を説明する際に使用。",
    },
    {
        "term": "bring that up",
        "meaningJa": "その話題を出す、問題提起する",
        "usageExample": "I'm glad you brought that up; it's a valid point.",
        "descriptionJa": "議場や議論で話題・懸念点を提示・提起することを指す。",
    },
    {
        "term": "I found out later that",
        "meaningJa": "後になって〜だと分かりました",
        "usageExample": "I found out later that all services share one registration.",
        "descriptionJa": "会議や調査の途中で新事実が判明した際の状況報告。",
    },
    {
        "term": "the lesson learned here is",
        "meaningJa": "ここから得られた教訓・学びは",
        "usageExample": "The lesson learned here is to keep credentials separate.",
        "descriptionJa": "トラブルや失敗の振り返り（Post-mortem）等で学びを共有・教訓化する。",
    },
    {
        "term": "from that angle",
        "meaningJa": "その角度から見ると、その観点からは",
        "usageExample": "From that angle, it makes sense to keep the current setup.",
        "descriptionJa": "特定の視点や切り口から物事を評価・判断する際に使用。",
    },
    {
        "term": "set up a guideline",
        "meaningJa": "ガイドラインを設定・策定する",
        "usageExample": "We need to set up a guideline for cross-service testing.",
        "descriptionJa": "運用基準や開発ガイドラインを新しく設けることを指す。",
    },
    {
        "term": "comply with",
        "meaningJa": "〜に準拠する、従う",
        "usageExample": "All teams need to comply with the guideline.",
        "descriptionJa": "規定やルール、方針に沿って実装や運用を行う。",
    },
    {
        "term": "that requires a slight change to our plan",
        "meaningJa": "それにより計画のわずかな変更が必要になります",
        "usageExample": "That requires a slight change to our plan for next week.",
        "descriptionJa": "条件変更に伴い、計画の一部を調整する必要が生じたことを報告。",
    },
    {
        "term": "the downside is",
        "meaningJa": "デメリット・短所は〜です",
        "usageExample": "The downside is that the code is managed outside our repository.",
        "descriptionJa": "案や手法の欠点・懸念点を明確に示す。",
    },
    {
        "term": "there shouldn't be any technical reason why",
        "meaningJa": "〜できない技術的な理由はないはずです",
        "usageExample": "There shouldn't be any technical reason why we can't move the script.",
        "descriptionJa": "技術的障害がないことを指摘し、移設や実行を肯定的に促す。",
    },
    {
        "term": "in the meantime",
        "meaningJa": "その合間に、それまでの間",
        "usageExample": "In the meantime, we can keep the existing behavior.",
        "descriptionJa": "本格対応までの接続期間中に行う暫定対応を述べる。",
    },
    {
        "term": "it's not a rush",
        "meaningJa": "急ぎではありません",
        "usageExample": "It's not a rush, so we can address it after the current release.",
        "descriptionJa": "タスクの緊急度が低く、優先度を下げて構わないと伝える。",
    },
    {
        "term": "I'm not 100% sure",
        "meaningJa": "完全に確信があるわけではありません",
        "usageExample": "I'm not 100% sure, so I'll verify the flow.",
        "descriptionJa": "確実性に欠けることを事前に示し、誤解を防ぐ配慮表現。",
    },
    {
        "term": "if that doesn't work",
        "meaningJa": "それがうまくいかなければ",
        "usageExample": "If that doesn't work, we'll use the next window.",
        "descriptionJa": "試みた手段が失敗した場合のフォールバック策を提示する。",
    },
    {
        "term": "we're trying to figure out",
        "meaningJa": "私たちは〜を解明・明確にしようとしています",
        "usageExample": "We're trying to figure out which ticket to assign to QA.",
        "descriptionJa": "課題解決や分析に向けて試行錯誤している最中であることを伝える。",
    },
    {
        "term": "sorry for cutting in",
        "meaningJa": "割り込んですみません",
        "usageExample": "Sorry for cutting in, but could you clarify the timeline?",
        "descriptionJa": "会議で相手の発言に割り込む際、失礼を詫びてから意見や質問を述べる表現。",
    },
]
