"""User-provided Technical Writing vocabulary fields (107 entries)."""

USER_ENTRIES: list[dict] = [
    {
        "term": 'be called to retrieve',
        "meaningJa": '取得するために呼び出される',
        "usageExample": "This endpoint is called to retrieve the user's current settings.",
        "descriptionJa": 'ユーザー設定取得など、処理を同期で取得する文脈。',
    },
    {
        "term": 'given a post code',
        "meaningJa": '郵便番号を指定して',
        "usageExample": 'The service returns address candidates given a post code.',
        "descriptionJa": '入力条件を指定して結果を取得する文脈。',
    },
    {
        "term": 'during the signup flow',
        "meaningJa": '登録フロー中に',
        "usageExample": 'The error occurs during the signup flow.',
        "descriptionJa": '画面遷移や処理タイミングを指定する表現。',
    },
    {
        "term": 'have a couple of',
        "meaningJa": 'いくつかある',
        "usageExample": 'We have a couple of compatibility concerns to address.',
        "descriptionJa": '少数の問題点や懸念をまとめて報告する表現。',
    },
    {
        "term": 'get rid of',
        "meaningJa": '取り除く、廃止する',
        "usageExample": 'We would like to get rid of the redundant conversion layer.',
        "descriptionJa": '不必要な構成要素を取り除く意図を伝える表現。',
    },
    {
        "term": 'place ... instead',
        "meaningJa": '代わりに〜へ置く',
        "usageExample": 'We should place this validation in the backend instead.',
        "descriptionJa": '実装箇所の変更や代替案を提案する表現。',
    },
    {
        "term": 'here is a list of',
        "meaningJa": '以下が〜の一覧です',
        "usageExample": 'Here is a list of fields that must be validated.',
        "descriptionJa": '列挙するリストの内容を提示する定型表現。',
    },
    {
        "term": 'be ideally required',
        "meaningJa": '理想的には必須である',
        "usageExample": 'These fields would ideally be required in the schema.',
        "descriptionJa": '望ましい仕様、修正後提案する表現。',
    },
    {
        "term": 'if there is a reason',
        "meaningJa": '理由がある場合',
        "usageExample": 'If there is a reason to retain this behavior, please document it.',
        "descriptionJa": '例外や例外条件の理由を求めて指示表現。',
    },
    {
        "term": 'cannot be required',
        "meaningJa": '必須にできない',
        "usageExample": 'Please explain why this field cannot be required.',
        "descriptionJa": '仕様上の制約や理由を尋ねる表現。',
    },
    {
        "term": 'the following is',
        "meaningJa": '以下は〜である',
        "usageExample": 'The following is the expected response format.',
        "descriptionJa": '仕様・例説・例示を指示する導入表現。',
    },
    {
        "term": 'previously classified as out of scope',
        "meaningJa": '以前は対象外と分類されていた',
        "usageExample": 'This process was previously classified as out of scope.',
        "descriptionJa": '過去のスコープ判断と現在の変更を対比する表現。',
    },
    {
        "term": 'be required for',
        "meaningJa": '〜に必要である',
        "usageExample": 'This change is required for the next release.',
        "descriptionJa": '特定のリリースや不具合に対応を示す表現。',
    },
    {
        "term": 'provide detail about',
        "meaningJa": '〜について詳細を提供する',
        "usageExample": 'The document should provide detail about the failure conditions.',
        "descriptionJa": '障害原因等の詳細を求める際に使う表現。',
    },
    {
        "term": 'where it is used',
        "meaningJa": 'どこで使用されているか',
        "usageExample": 'The document should explain where it is used.',
        "descriptionJa": 'コンポーネントやプロパティの使用箇所を示す表現。',
    },
    {
        "term": 'seem to be',
        "meaningJa": '〜のようである',
        "usageExample": 'The issue seems to be limited to migrated accounts.',
        "descriptionJa": '現状の推論や調査中の見解を述べる定型表現。',
    },
    {
        "term": 'be called when',
        "meaningJa": '〜のときに呼び出される',
        "usageExample": 'The API is called when the user confirms the change.',
        "descriptionJa": 'トリガーとなる操作やイベントを指定する表現。',
    },
    {
        "term": 'in addition to',
        "meaningJa": '〜に加えて',
        "usageExample": 'In addition to the timeout, we observed duplicate requests.',
        "descriptionJa": '複数の問題や要件を並列で追加する表現。',
    },
    {
        "term": 're-raise',
        "meaningJa": '再度提起する、再度の議論を促す',
        "usageExample": 'I want to re-raise this requirement before implementation starts.',
        "descriptionJa": '以前却下された提案等を再度確認するための要請。',
    },
    {
        "term": 'be relevant to',
        "meaningJa": '〜に関連している',
        "usageExample": 'These points are relevant to the account recovery flow.',
        "descriptionJa": '関連する領域や機能を指摘する表現。',
    },
    {
        "term": 'still out of scope',
        "meaningJa": 'まだ対象外である',
        "usageExample": 'If this scenario is still out of scope, please confirm it.',
        "descriptionJa": '現状でもスコープ外か確認を促す表現。',
    },
    {
        "term": 'be used in some screens',
        "meaningJa": 'いくつかの画面で使用されている',
        "usageExample": 'This status is used in some screens to control navigation.',
        "descriptionJa": '影響範囲の広がりを示すための表現。',
    },
    {
        "term": 'return a URL string',
        "meaningJa": 'URL文字列を返す',
        "usageExample": 'The endpoint returns a URL string for the next step.',
        "descriptionJa": '返り値の型と用途を説明する表現。',
    },
    {
        "term": 'be opened in a webview',
        "meaningJa": 'WebViewで開かれる',
        "usageExample": 'The returned URL will be opened in a webview.',
        "descriptionJa": 'クライアント側での利用方法を説明する表現。',
    },
    {
        "term": 'this issue is to create',
        "meaningJa": 'このIssueの目的は〜を作成することです',
        "usageExample": 'This issue is to create an endpoint for account recovery.',
        "descriptionJa": 'Issueの目的を概要で提示する表現。',
    },
    {
        "term": 'the steps are',
        "meaningJa": '手順は以下のとおり',
        "usageExample": 'The steps are as follows.',
        "descriptionJa": '処理フローや再現手順の開始を告げる表現。',
    },
    {
        "term": 'send a POST request',
        "meaningJa": 'POSTリクエストを送信する',
        "usageExample": 'The client sends a POST request after the user confirms.',
        "descriptionJa": 'HTTPメソッドを指定した処理を説明する表現。',
    },
    {
        "term": 'generate random values',
        "meaningJa": 'ランダムな値を生成する',
        "usageExample": 'The system generates two random values for request validation.',
        "descriptionJa": '暗号化やセキュリティ処理の挙動を説明する表現。',
    },
    {
        "term": 'open a modal',
        "meaningJa": 'モーダルを開く',
        "usageExample": 'The application opens a modal for external authentication.',
        "descriptionJa": 'UI上の挙動を指定する表現。',
    },
    {
        "term": 'redirect URL',
        "meaningJa": 'リダイレクトURL',
        "usageExample": 'The provider returns the result through a redirect URL.',
        "descriptionJa": '外部検証など戻り先を示す定型表現。',
    },
    {
        "term": 'with data in query parameters',
        "meaningJa": 'クエリパラメータにデータを含めて',
        "usageExample": 'The provider sends the result with data in query parameters.',
        "descriptionJa": 'リクエスト/レスポンスのデータ受け渡し方法を示す表現。',
    },
    {
        "term": 'call the following endpoints',
        "meaningJa": '以下のエンドポイントを呼び出す',
        "usageExample": 'The client then calls the following endpoints.',
        "descriptionJa": '後続処理のAPI呼び出し順番を指定する表現。',
    },
    {
        "term": 'be combined into one',
        "meaningJa": '統合できる',
        "usageExample": 'These two checks can be combined into one request.',
        "descriptionJa": '複数処理の統合や統合を提案する表現。',
    },
    {
        "term": 'using this algorithm',
        "meaningJa": 'このアルゴリズムを使って',
        "usageExample": 'We should validate this data using this algorithm.',
        "descriptionJa": '特定のロジックやアルゴリズムへの言及。',
    },
    {
        "term": 'for the scope of',
        "meaningJa": '〜のスコープでは',
        "usageExample": 'For the scope of this release, only the new flow is supported.',
        "descriptionJa": '適用範囲・明確化に限定する表現。',
    },
    {
        "term": 'need to pass through',
        "meaningJa": 'そのまま通過させる必要がある',
        "usageExample": 'The BFF needs to pass through the correlation header to the upstream service.',
        "descriptionJa": 'ヘッダーや値を中継する指示を表す表現。',
    },
    {
        "term": 'create tasks for',
        "meaningJa": '〜のタスクを作成する',
        "usageExample": 'We should create tasks for updating the contract and implementation.',
        "descriptionJa": '作業の分割や関連して発生する作業の割り振り表現。',
    },
    {
        "term": 'update the specification',
        "meaningJa": '仕様書を更新する',
        "usageExample": 'We need to update the specification before implementation.',
        "descriptionJa": '契約/OpenAPI文書の変更更新を指示する表現。',
    },
    {
        "term": 'the actual implementation',
        "meaningJa": '実際の実装',
        "usageExample": 'The specification and the actual implementation must remain aligned.',
        "descriptionJa": '仕様上の定義と実装をコードを対比する表現。',
    },
    {
        "term": 'revise the implementation',
        "meaningJa": '実装を見直す',
        "usageExample": 'Revise the implementation to use a shared client.',
        "descriptionJa": '既存コードの変更方針を促す表現。',
    },
    {
        "term": 'support ... with ...',
        "meaningJa": '一括で〜をサポートする',
        "usageExample": 'The client should support shared configuration with individual error handlers.',
        "descriptionJa": '共通処理と固有設定を併存させる要件構造。',
    },
    {
        "term": 'make a few requests related to',
        "meaningJa": '〜に関する要望をいくつか出す',
        "usageExample": "I'd like to make a few requests related to the signup API.",
        "descriptionJa": '複数の変更要望をまとめて導入する丁寧な表現。',
    },
    {
        "term": 'make ... the same as',
        "meaningJa": '〜を〜と同じにする',
        "usageExample": 'Can we make this schema the same as the existing request schema?',
        "descriptionJa": '重複する型やプロパティの一致を要請する表現。',
    },
    {
        "term": 'have the same meaning as',
        "meaningJa": '〜と同じ意味を持つ',
        "usageExample": 'This tag has the same meaning as the existing status field.',
        "descriptionJa": '属性の用途や概念の共通性を示す表現。',
    },
    {
        "term": 'perform logic related to',
        "meaningJa": '〜に関連するロジックを実行する',
        "usageExample": 'The backend needs to perform logic related to campaign eligibility.',
        "descriptionJa": 'ビジネスロジック処理を指示する表現。',
    },
    {
        "term": 'rename ... to ...',
        "meaningJa": '〜を〜に名前変更する',
        "usageExample": 'Can we rename this field to reflect its actual meaning?',
        "descriptionJa": '意図に沿ったプロパティ名の変更提案。',
    },
    {
        "term": 'fill ... using',
        "meaningJa": '〜を使って埋める/設定する',
        "usageExample": 'We can fill this field using the upstream response.',
        "descriptionJa": '情報の取得元や設定方法を示す表現。',
    },
    {
        "term": 'on the backend side',
        "meaningJa": 'バックエンド側で',
        "usageExample": 'Validation should be performed on the backend side.',
        "descriptionJa": '処理を行う側を明確にする表現。',
    },
    {
        "term": 'only necessary to',
        "meaningJa": '〜するだけでよい',
        "usageExample": 'It is only necessary to set this field during creation.',
        "descriptionJa": '必要最小限の処理条件を示す表現。',
    },
    {
        "term": 'not during',
        "meaningJa": '〜の間は行わない',
        "usageExample": 'The value should be set on creation, but not during partial updates.',
        "descriptionJa": '適用を制限したいタイミングを明示して示す表現。',
    },
    {
        "term": 'partial updates',
        "meaningJa": '部分更新',
        "usageExample": 'Add a PATCH endpoint to support partial updates.',
        "descriptionJa": 'PATCHなど更新範囲を限定する文脈に使う表現。',
    },
    {
        "term": 'replace ... with ...',
        "meaningJa": '〜を〜に置き換える',
        "usageExample": 'Replace the success payload with a no-content response.',
        "descriptionJa": 'レスポンス構造や挙動の置き換え。',
    },
    {
        "term": 'no-content status',
        "meaningJa": '本文なしのステータス',
        "usageExample": 'A no-content status is appropriate when the response has no payload.',
        "descriptionJa": '204などデータなしの判定を示す表現。',
    },
    {
        "term": "returning ... isn't meaningful",
        "meaningJa": '〜を返すのは意味がない',
        "usageExample": "Returning an empty success message isn't meaningful.",
        "descriptionJa": '非推奨なレスポンス設計を指摘する際の使用。',
    },
    {
        "term": 'thus',
        "meaningJa": 'したがって',
        "usageExample": 'The response has no body; thus, a no-content status is suitable.',
        "descriptionJa": '論理的な結論へつなぐ（やや硬めの）表現。',
    },
    {
        "term": 'be suitable',
        "meaningJa": '適切である',
        "usageExample": 'A no-content response is suitable for this operation.',
        "descriptionJa": '提案した選択肢が要件に合うことを述べる表現。',
    },
    {
        "term": 'required endpoints',
        "meaningJa": '必要なエンドポイント',
        "usageExample": 'The required endpoints are listed below.',
        "descriptionJa": '実装対象の一覧を導入する指示文頭。',
    },
    {
        "term": 'current flow',
        "meaningJa": '現在のフロー',
        "usageExample": 'The current flow requires three upstream calls.',
        "descriptionJa": '現状の動作・処理フローを記述する見出し表題。',
    },
    {
        "term": 'check if ... is available',
        "meaningJa": '〜が利用可能か確認する',
        "usageExample": 'Check if the external service is available.',
        "descriptionJa": '前処理や外部機能の状態確認を示す表現。',
    },
    {
        "term": 'not undergoing maintenance',
        "meaningJa": 'メンテナンス中ではない',
        "usageExample": 'Request proceeds only when the service is not undergoing maintenance.',
        "descriptionJa": '利用条件・利用不可条件を明示する表現。',
    },
    {
        "term": 'encrypt ... using ...',
        "meaningJa": '〜を使って〜を暗号化する',
        "usageExample": 'Encrypt the identifier using the configured key.',
        "descriptionJa": '処理ロジックや指定パラメタを明確にする表現。',
    },
    {
        "term": 'log in ... using ...',
        "meaningJa": '〜を使ってログインする',
        "usageExample": 'Log in to the provider using the encrypted identifier.',
        "descriptionJa": '外部サービスログイン処理を指示する表現。',
    },
    {
        "term": 'update records with',
        "meaningJa": '〜を使ってレコードを更新する',
        "usageExample": 'Update the authentication records with the returned identifier.',
        "descriptionJa": '変更に更新するパラメータを指定する表現。',
    },
    {
        "term": 'response body is ignored',
        "meaningJa": 'レスポンス本文は無視される',
        "usageExample": 'The response body is ignored because only the status code is needed.',
        "descriptionJa": '取得した値を無視した処理実行を指示する表現。',
    },
    {
        "term": 'even though',
        "meaningJa": '〜であるにもかかわらず',
        "usageExample": 'The endpoint retrieves data even though it uses POST.',
        "descriptionJa": '仕様上の例外的な挙動を補足する技術表現。',
    },
    {
        "term": 'user might need to',
        "meaningJa": 'ユーザーは〜する必要があるかもしれない',
        "usageExample": 'The user might need to authenticate again after migration.',
        "descriptionJa": '発生し得るケースの前提条件や注意点。',
    },
    {
        "term": 'through a third-party page',
        "meaningJa": '外部のページを介して',
        "usageExample": 'Authentication is completed through a third-party page.',
        "descriptionJa": '外部サービスを経由するフローを説明する表現。',
    },
    {
        "term": 'must consent to',
        "meaningJa": '〜に同意しなければならない',
        "usageExample": 'The user must consent to information sharing before continuing.',
        "descriptionJa": 'フロー上で必須となる同意ステップを明確にする表現。',
    },
    {
        "term": 'validate ... against ...',
        "meaningJa": '〜を〜と照合する',
        "usageExample": 'Validate the submitted profile against the verified identity data.',
        "descriptionJa": '二つのデータを照合する操作を表す表現。',
    },
    {
        "term": 'be sent',
        "meaningJa": '送信される',
        "usageExample": 'The user will be sent a one-time authorization code.',
        "descriptionJa": '自動コードの送出やSMS送信を説明する文脈。',
    },
    {
        "term": 'finalize',
        "meaningJa": '完了させる',
        "usageExample": 'Finalize the account linkage after verification succeeds.',
        "descriptionJa": '手続の最終処理に段階を移行させる表現。',
    },
    {
        "term": 'for the first step',
        "meaningJa": '最初のステップでは',
        "usageExample": 'For the first step, the client should reuse the cached identifier.',
        "descriptionJa": '段階的処理の初期段階に条件を設ける表現。',
    },
    {
        "term": 'provide a fallback',
        "meaningJa": '代替策・代替手段を提供する',
        "usageExample": 'The client should provide a fallback when the primary value is absent.',
        "descriptionJa": '障害発生時や値が存在しない場合に対応する代替手段。',
    },
    {
        "term": 'if available',
        "meaningJa": '利用可能であれば',
        "usageExample": 'Use the cached identifier if available.',
        "descriptionJa": '任意パラメータや、データが存在する場合だけ適用する条件。',
    },
    {
        "term": 'not ... but a request for ...',
        "meaningJa": '〜ではなく〜の要請である',
        "usageExample": 'This is not a backend defect but a request for platform support.',
        "descriptionJa": 'Issueの分類や期待値を正しく提示する表現。',
    },
    {
        "term": 'when performing',
        "meaningJa": '〜を行う際に',
        "usageExample": 'When performing account linkage, preserve the original state value.',
        "descriptionJa": '特定の操作を行う実行中の文脈を限定する要件。',
    },
    {
        "term": 'redirect back to',
        "meaningJa": '〜へリダイレクトして戻す',
        "usageExample": 'The provider redirects the user back to the callback page.',
        "descriptionJa": '認証処理後の元の画面遷移を説明。',
    },
    {
        "term": 'however',
        "meaningJa": 'しかしながら',
        "usageExample": 'However, the callback path does not exist in the new application.',
        "descriptionJa": '前言の前提と相反する問題点を指摘。',
    },
    {
        "term": 'the true target is',
        "meaningJa": '実際の遷移先は〜である',
        "usageExample": 'The true target is the account setup page.',
        "descriptionJa": '見かけ上の値と正しい到達先を対比する表現。',
    },
    {
        "term": 'with an extra action before',
        "meaningJa": 'その前に追加のアクションを行って',
        "usageExample": 'The target is the same page, with an extra action before redirection.',
        "descriptionJa": '遷移フローの途中で行う補足アクションを指示。',
    },
    {
        "term": 'easy to set up',
        "meaningJa": '簡単に設定できる',
        "usageExample": 'The redirect is easy to set up in the client service.',
        "descriptionJa": '実装・設定が容易であることを言及する表現。',
    },
    {
        "term": 'lose some information',
        "meaningJa": '一部の情報が失われる',
        "usageExample": 'Without this parameter, we lose some information during redirection.',
        "descriptionJa": '移行方式の弊害や不具合点を具体的に示す表現。',
    },
    {
        "term": 'it would be nice if',
        "meaningJa": '〜であるとよい',
        "usageExample": 'It would be nice if the redirect preserved the original action.',
        "descriptionJa": '必須ではないが改善あるいは要望を示す表現。',
    },
    {
        "term": 'include ... in ...',
        "meaningJa": '〜を〜に含める',
        "usageExample": 'Include the source identifier in the launch parameters.',
        "descriptionJa": '送信情報にどこへあらかじめ入れるか明示する表現。',
    },
    {
        "term": 'solve this minor problem',
        "meaningJa": 'この軽微な問題を解決する',
        "usageExample": 'The additional parameter would solve this minor problem.',
        "descriptionJa": '影響範囲の小さい問題と解決策を提案し提示する表現。',
    },
    {
        "term": 'caused by',
        "meaningJa": '〜によって引き起こされた',
        "usageExample": 'The regression was caused by a contract change.',
        "descriptionJa": '根本原因を明確に示す表現。',
    },
    {
        "term": 'missing required non-nullable field',
        "meaningJa": '必須のnull不可フィールドの欠落',
        "usageExample": 'The response contains a missing required non-nullable field.',
        "descriptionJa": 'スキーマ不整合の問題を具体的に定義する表現。',
    },
    {
        "term": 'be thrown',
        "meaningJa": 'スローされる',
        "usageExample": 'A deserialization exception will be thrown in this case.',
        "descriptionJa": '例外が発生する実際の動作と受動態で説明する表現。',
    },
    {
        "term": 'apparently',
        "meaningJa": '見たところ、どうやら',
        "usageExample": 'The client apparently wraps the original exception.',
        "descriptionJa": '未確認の推測や観察結果に確証を付ける文脈。',
    },
    {
        "term": 're-throw ... as ...',
        "meaningJa": '〜として再度スローする',
        "usageExample": 'The client re-throws the parsing error as a generic exception.',
        "descriptionJa": '例外変換の実際の動作を説明する表現。',
    },
    {
        "term": 'cause ... to be ...',
        "meaningJa": '〜が〜という結果になる',
        "usageExample": 'This mapping causes the error message to be misleading.',
        "descriptionJa": '結果・影響関係を示す表現。',
    },
    {
        "term": 'the request succeeded',
        "meaningJa": 'リクエストは成功したが',
        "usageExample": 'The request succeeded, but response parsing failed.',
        "descriptionJa": '通信自体の成否と処理異常を分ける説明。',
    },
    {
        "term": 'the caller is expecting',
        "meaningJa": '呼び出し側は〜を期待している',
        "usageExample": 'The caller is expecting fields that the provider no longer returns.',
        "descriptionJa": '消費側の期待値と実際の挙動の齟齬。',
    },
    {
        "term": 'not provided by upstream anymore',
        "meaningJa": '上流からはもう提供されていない',
        "usageExample": 'These fields are not provided by upstream anymore.',
        "descriptionJa": '外部依存先の変更の変更を明確に述べる表現。',
    },
    {
        "term": 'slightly misleading',
        "meaningJa": 'やや誤解を招く',
        "usageExample": 'The current error message is slightly misleading.',
        "descriptionJa": '完全な誤りではないが改善が必要な表現を指摘する言い方。',
    },
    {
        "term": 'detect ... was caused by ...',
        "meaningJa": '〜が〜によって起こったと検出する',
        "usageExample": 'We should detect whether the failure was caused by missing data.',
        "descriptionJa": '根本原因を検出する攻撃要件を示す表現。',
    },
    {
        "term": 'identify this issue',
        "meaningJa": 'この問題を検出する',
        "usageExample": 'The changeset helped identify this issue.',
        "descriptionJa": '問題を発見した手段を説明する表現。',
    },
    {
        "term": 'be missing from',
        "meaningJa": '〜から欠落している',
        "usageExample": 'The required property is missing from the request schema.',
        "descriptionJa": '期待される要素が存在しない状態を示す表現。',
    },
    {
        "term": 'expect ... in a request',
        "meaningJa": 'リクエストに〜を要求する',
        "usageExample": 'The API expects this status in a request.',
        "descriptionJa": 'API定義上の要求の期待値を説明する表現。',
    },
    {
        "term": 'as seen here',
        "meaningJa": 'ここで確認できるように',
        "usageExample": 'The handler requires the field, as seen here.',
        "descriptionJa": '根拠となる実装や例を示す表示。',
    },
    {
        "term": 'in the request schema',
        "meaningJa": 'リクエストスキーマでは',
        "usageExample": 'In the request schema, the property is marked as required.',
        "descriptionJa": '仕様上の定義上の状態を説明する前提表現。',
    },
    {
        "term": 'be defined',
        "meaningJa": '定義されている',
        "usageExample": 'The field is defined in the request schema.',
        "descriptionJa": '仕様上の存在を明確に述べる表現。',
    },
    {
        "term": 'reference another schema',
        "meaningJa": '別のスキーマを参照する',
        "usageExample": 'This schema references another schema for shared fields.',
        "descriptionJa": 'スキーマ間の依存関係を説明する表現。',
    },
    {
        "term": 'add the property',
        "meaningJa": 'そのプロパティを追加する',
        "usageExample": 'Could we add the property to the shared schema?',
        "descriptionJa": '不足項目に対する具体的提案を行う表現。',
    },
    {
        "term": 'resolve this issue',
        "meaningJa": 'この問題を解決する',
        "usageExample": 'Adding the missing field to resolve this issue.',
        "descriptionJa": '提案した変更と解決の結び付けを行う表現。',
    },
    {
        "term": 'improve test coverage',
        "meaningJa": 'テストカバレッジを改善する',
        "usageExample": "We'd like to improve test coverage for error handling.",
        "descriptionJa": 'テスト改善の目的を提示する標準表現。',
    },
    {
        "term": 'leverage the power of',
        "meaningJa": '〜の力を活用する',
        "usageExample": 'We can leverage the power of generated tests to cover edge cases.',
        "descriptionJa": 'ツールや仕組みの強力さを活かす方針を示す表現。',
    },
]
